import {z} from 'zod';
import {createHash} from 'node:crypto';
import {one,rows,transaction,parseJson} from './db.js';
import {body,reply,projectFor,positiveId,WorkError} from './work-common.js';
import {flowSchema} from './agent-flow.js';
import {expandFlowParts} from './agent-parts-flow.js';
// Загружает неизменяемую версию только в проекте вызывающего агента.
export async function resolveFlowParts(user,projectId,flow){return expandFlowParts(flow,async(id,version)=>{await projectFor(user,projectId);await projectFor(user,projectId,'agent.view');const part=await one('SELECT v.flow_json FROM ai_agent_part_versions v JOIN ai_agent_parts p ON p.id=v.part_id WHERE p.id=? AND v.version=? AND p.project_id=? AND p.workspace_id=?',[id,version,projectId,user.workspace_id]);if(!part)throw new WorkError(403,'Версия общей части недоступна в этом проекте');return {flow:flowSchema.parse(parseJson(part.flow_json))};});}
// Проверяет общий бюджет и разрешённые операции после раскрытия частей.
export function checkExpandedFlow(config,flow){if(flow.nodes.filter(n=>['analyze','action'].includes(n.type)).length+1>config.flow.max_calls)throw new WorkError(422,'Лимит вызовов не покрывает вложенные части и итоговый ответ');for(const node of flow.nodes)if(node.type==='action'&&!config.actions.includes(node.action))throw new WorkError(422,'Разрешите действие из общей части: '+node.action);}
// Хранит библиотеку проекта с неизменяемыми версиями и защитой повторного сохранения.
export async function agentPartsApi(request,path,user){
 if(request.method==='GET'){const projectId=positiveId.parse(new URL(request.url).searchParams.get('project_id'));await projectFor(user,projectId);await projectFor(user,projectId,'agent.view');return reply(await rows('SELECT p.id,p.name,p.version,v.flow_json FROM ai_agent_parts p JOIN ai_agent_part_versions v ON v.part_id=p.id AND v.version=p.version WHERE p.project_id=? AND p.workspace_id=? ORDER BY p.name LIMIT 200',[projectId,user.workspace_id]).then(list=>list.map(({flow_json,...part})=>({...part,flow:parseJson(flow_json)}))));}
 if(request.method!=='POST'||path.length!==2)throw new WorkError(404,'Метод библиотеки не найден');
 const data=z.object({project_id:positiveId,part_id:positiveId.nullable().default(null),version:z.number().int().min(0).default(0),name:z.string().trim().min(2).max(160),flow:flowSchema,request_id:z.string().uuid()}).strict().parse(await body(request));
 await projectFor(user,data.project_id);await projectFor(user,data.project_id,'agent.manage',true);if(!data.flow.nodes.length)throw new WorkError(422,'Добавьте блоки общей части');const expanded=await resolveFlowParts(user,data.project_id,data.flow);if(expanded.nodes.filter(n=>['analyze','action'].includes(n.type)).length+1>data.flow.max_calls)throw new WorkError(422,'Увеличьте общий лимит вызовов');const fingerprint=createHash('sha256').update(JSON.stringify(data)).digest('hex');
 return transaction(async c=>{await c.query('SELECT id FROM projects WHERE id=? FOR UPDATE',[data.project_id]);const [[old]]=await c.query('SELECT * FROM ai_agent_part_versions WHERE request_id=?',[data.request_id]);if(old){if(Number(old.created_by)!==Number(user.id)||old.fingerprint!==fingerprint)throw new WorkError(409,'Этот запрос уже использован');return reply({id:old.part_id,version:old.version,replayed:true});}
  let id=data.part_id,version=1;if(id){const [[part]]=await c.query('SELECT * FROM ai_agent_parts WHERE id=? AND project_id=? AND workspace_id=?',[id,data.project_id,user.workspace_id]);if(!part)throw new WorkError(404,'Общая часть не найдена');if(part.version!==data.version)throw new WorkError(409,'Библиотека изменена другим сотрудником');version=part.version+1;await c.query('UPDATE ai_agent_parts SET name=?,version=? WHERE id=?',[data.name,version,id]);}
  else {const [[count]]=await c.query('SELECT COUNT(*) AS total FROM ai_agent_parts WHERE project_id=?',[data.project_id]);if(count.total>=200)throw new WorkError(409,'В проекте уже 200 общих частей');const [created]=await c.query('INSERT INTO ai_agent_parts(workspace_id,project_id,name) VALUES(?,?,?)',[user.workspace_id,data.project_id,data.name]);id=created.insertId;}
  await c.query('INSERT INTO ai_agent_part_versions(part_id,version,name,flow_json,created_by,request_id,fingerprint) VALUES(?,?,?,?,?,?,?)',[id,version,data.name,JSON.stringify(data.flow),user.id,data.request_id,fingerprint]);await c.query("INSERT INTO audit_log(workspace_id,actor_id,action,entity_type,entity_id,details_json) VALUES(?,?,'agent.part.saved','agent_part',?,?)",[user.workspace_id,user.id,String(id),JSON.stringify({version})]);return reply({id,version},201);
 });
}
