const DAY=86400000,formatters=new Map();
export function utc(value){if(value instanceof Date)return value.getTime();if(typeof value==='number')return value;if(!value)return NaN;return Date.parse(/[TZ]|[+-]\d\d:\d\d$/.test(value)?value:String(value).replace(' ','T')+'Z');}
function formatter(zone){if(!formatters.has(zone))formatters.set(zone,new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}));return formatters.get(zone);}
export function localParts(stamp,zone='UTC'){return Object.fromEntries(formatter(zone).formatToParts(new Date(stamp)).filter(p=>p.type!=='literal').map(p=>[p.type,Number(p.value)]));}
function dateKey(p){return `${p.year}-${String(p.month).padStart(2,'0')}-${String(p.day).padStart(2,'0')}`;}
function shiftDate(key,days){return new Date(Date.parse(key+'T12:00:00Z')+days*DAY).toISOString().slice(0,10);}
export function zonedMinute(date,minute,zone){const desired=Date.parse(date+'T00:00:00Z')+minute*60000;let stamp=desired;const visited=[];for(let i=0;i<6;i++){const p=localParts(stamp,zone),delta=desired-Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second);if(!delta)return stamp;visited.push(stamp);stamp+=delta;if(visited.includes(stamp))return Math.max(stamp,visited.at(-1));}return stamp;}
export function normalizeCalendar(c){return c?{...c,timezone:c.timezone||'UTC',weekly:typeof c.weekly_json==='string'?JSON.parse(c.weekly_json):c.weekly_json||c.weekly,holidays:typeof c.holidays_json==='string'?JSON.parse(c.holidays_json):c.holidays_json||c.holidays||[]}:null;}
function rangesFor(date,c,cache){const key=`${c.id||c.name}:${c.revision||0}:${c.timezone}:${date}`;if(cache?.has(key))return cache.get(key);const weekday=new Date(date+'T12:00:00Z').getUTCDay(),ranges=c.holidays.includes(date)?[]:(c.weekly?.[weekday]||[]).map(([a,b])=>[zonedMinute(date,a,c.timezone),zonedMinute(date,b,c.timezone)]);cache?.set(key,ranges);return ranges;}
export function businessMinutes(from,to,calendar=null,cache=new Map()){const start=utc(from),end=utc(to);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return 0;if(!calendar)return (end-start)/60000;calendar=normalizeCalendar(calendar);let date=dateKey(localParts(start,calendar.timezone)),last=dateKey(localParts(end,calendar.timezone)),ms=0;for(let n=0;date<=last&&n<36600;n++,date=shiftDate(date,1))for(const [a,b]of rangesFor(date,calendar,cache))ms+=Math.max(0,Math.min(end,b)-Math.max(start,a));return ms/60000;}
export function businessDeadline(from,minutes,calendar=null,cache=new Map()){const start=utc(from);if(!Number.isFinite(start))return null;if(minutes<=0)return new Date(start).toISOString();if(!calendar)return new Date(start+minutes*60000).toISOString();calendar=normalizeCalendar(calendar);let date=dateKey(localParts(start,calendar.timezone)),remaining=minutes;for(let n=0;n<3660;n++,date=shiftDate(date,1))for(const [a,b]of rangesFor(date,calendar,cache)){const begin=Math.max(start,a),available=Math.max(0,(b-begin)/60000);if(available&&remaining<=available)return new Date(begin+remaining*60000).toISOString();remaining-=available;}return null;}
