import { businessMinutes,businessDeadline,utc,normalizeCalendar } from './business-time.js';
const parse=(value,fallback)=>typeof value==='string'?JSON.parse(value):value??fallback;
function valueOf(task,field){return field.startsWith('custom.')?task.custom_values?.[field.slice(7)]:task[field];}
export function slaConditionMatches(task,condition){const actual=valueOf(task,condition.field),expected=condition.value;if(condition.operator==='not_equals')return String(actual??'')!==String(expected??'');if(condition.operator==='contains')return Array.isArray(actual)?actual.map(String).includes(String(expected)):String(actual??'').toLowerCase().includes(String(expected??'').toLowerCase());if(condition.operator==='in')return (Array.isArray(expected)?expected:String(expected??'').split(',')).map(String).includes(String(actual));if(condition.operator==='gte')return Number(actual)>=Number(expected);if(condition.operator==='lte')return Number(actual)<=Number(expected);return String(actual??'')===String(expected??'');}
export function normalizeTaskSlaPolicy(policy){return {...policy,counter_key:policy.counter_key||'completion',conditions:parse(policy.conditions_json,policy.conditions||[]),config:parse(policy.config_json,policy.config||{})};}
export function calculateTaskSla(task,rawPolicy,events=[],calendar=null,now=new Date(),cache=new Map()){
 const policy=normalizeTaskSlaPolicy(rawPolicy),config=policy.config,created=utc(task.created_at),end=now.getTime();if(!Number.isFinite(created)||end<created)return null;
 const ordered=events.filter(e=>Number(e.task_id)===Number(task.id)&&utc(e.occurred_at)<=end).sort((a,b)=>utc(a.occurred_at)-utc(b.occurred_at)||Number(a.id)-Number(b.id));const complete=ordered.length>0&&ordered[0].source==='recorded',hadEvents=ordered.length>0;
 if(!ordered.length)ordered.push({task_id:task.id,stage_id:task.stage_id,is_done:false,occurred_at:task.created_at,source:'baseline'});
 if(utc(ordered[0].occurred_at)>created)ordered.unshift({task_id:task.id,stage_id:0,is_done:false,occurred_at:task.created_at,source:'baseline'});
 if(!hadEvents&&task.is_done&&(task.completed_at||task.updated_at))ordered.push({stage_id:task.stage_id,is_done:true,occurred_at:task.completed_at||task.updated_at,source:'baseline'});
 let started=!config.start_stage_ids?.length,stopped=false,cycle=1,elapsed=0,finished=null,breachAt=null,phase=started?'running':'not_started';const segments=[];
 for(let i=0;i<ordered.length;i++){
  const event=ordered[i],from=Math.max(created,utc(event.occurred_at)),to=Math.max(from,Math.min(end,i+1<ordered.length?utc(ordered[i+1].occurred_at):end)),isStop=config.stop_stage_ids?.length?config.stop_stage_ids.map(Number).includes(Number(event.stage_id)):Boolean(event.is_done);
  if(stopped&&!isStop&&config.reopen!=='keep'){stopped=false;finished=null;cycle++;if(config.reopen==='restart'){elapsed=0;breachAt=null;started=!config.start_stage_ids?.length;}}
  if(config.start_stage_ids?.map(Number).includes(Number(event.stage_id)))started=true;
  if(isStop&&started&&!stopped){stopped=true;finished=from;}
  phase=!started?'not_started':stopped?'completed':config.pause_stage_ids?.map(Number).includes(Number(event.stage_id))?'paused':'running';
  const minutes=phase==='running'?businessMinutes(from,to,calendar,cache):0;if(!breachAt&&minutes>0&&elapsed+minutes>=Number(policy.goal_minutes))breachAt=businessDeadline(from,Number(policy.goal_minutes)-elapsed,calendar,cache);elapsed+=minutes;
  if(to>from)segments.push({from:new Date(from).toISOString(),to:new Date(to).toISOString(),stage_id:event.stage_id,phase,cycle,minutes:Math.round(minutes*100)/100,source:event.source});
 }
 const goal=Number(policy.goal_minutes),ratio=goal?elapsed/goal:1,remaining=goal-elapsed,status=stopped&&ratio<=1?'achieved':ratio>=1?'breached':ratio*100>=Number(policy.warning_percent)?'warning':'on_track';
 return {task_id:task.id,project_id:task.project_id,policy_id:policy.id,policy_name:policy.name,counter_key:policy.counter_key,policy_revision:policy.revision||1,calendar_revision:calendar?.revision||null,goal_minutes:goal,elapsed_minutes:Math.floor(elapsed),remaining_minutes:Math.ceil(remaining),due_at:breachAt||(phase==='running'?businessDeadline(end,remaining,calendar,cache):null),completed_at:finished!==null?new Date(finished).toISOString():null,status,phase,cycle,history_complete:complete,segments};
}
export function evaluateTaskSlas(tasks,policies,now=new Date(),context={}){const active=policies.map(normalizeTaskSlaPolicy).filter(p=>p.enabled).sort((a,b)=>Number(a.position)-Number(b.position)||Number(a.id)-Number(b.id)),calendars=new Map((context.calendars||[]).map(c=>[Number(c.id),normalizeCalendar(c)])),cache=new Map(),byTask=new Map();for(const e of context.events||[]){const key=Number(e.task_id);if(!byTask.has(key))byTask.set(key,[]);byTask.get(key).push(e);}return tasks.flatMap(task=>{const selected=new Set();return active.filter(p=>{if(selected.has(p.counter_key)||(p.project_id&&Number(p.project_id)!==Number(task.project_id))||!p.conditions.every(c=>slaConditionMatches(task,c)))return false;selected.add(p.counter_key);return true;}).map(p=>calculateTaskSla(task,p,byTask.get(Number(task.id))||[],calendars.get(Number(p.calendar_id))||null,now,cache)).filter(Boolean);});}
