-- Добавляет ту же структуру компании и проектов, что миграция MySQL 044.
ALTER TABLE users DROP CONSTRAINT users_global_role_check;
ALTER TABLE users ADD CONSTRAINT users_global_role_check CHECK(global_role IN ('owner','admin','project_manager','tribe_leader','member','viewer'));
CREATE TABLE tribes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workspace_id bigint NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  leader_id bigint NOT NULL REFERENCES users(id),
  name varchar(160) COLLATE kontur_text NOT NULL,
  description varchar(2000) NOT NULL DEFAULT '',
  color varchar(16) NOT NULL DEFAULT '#e30611',
  revision bigint NOT NULL DEFAULT 1,
  created_by bigint NOT NULL REFERENCES users(id),
  created_at timestamp(0) NOT NULL DEFAULT date_trunc('second',statement_timestamp() AT TIME ZONE 'UTC'),
  updated_at timestamp(0) NOT NULL DEFAULT date_trunc('second',statement_timestamp() AT TIME ZONE 'UTC'),
  UNIQUE(workspace_id,name)
);
CREATE INDEX tribes_leader ON tribes(leader_id);
CREATE TABLE tribe_members (
  tribe_id bigint NOT NULL REFERENCES tribes(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  can_manage_space smallint NOT NULL DEFAULT 0 CHECK(can_manage_space IN (0,1)),
  can_manage_members smallint NOT NULL DEFAULT 0 CHECK(can_manage_members IN (0,1)),
  can_create_projects smallint NOT NULL DEFAULT 0 CHECK(can_create_projects IN (0,1)),
  can_manage_projects smallint NOT NULL DEFAULT 0 CHECK(can_manage_projects IN (0,1)),
  created_at timestamp(0) NOT NULL DEFAULT date_trunc('second',statement_timestamp() AT TIME ZONE 'UTC'),
  PRIMARY KEY(tribe_id,user_id)
);
CREATE INDEX tribe_member_user ON tribe_members(user_id,tribe_id);
ALTER TABLE projects ADD COLUMN tribe_id bigint REFERENCES tribes(id),
  ADD COLUMN owner_id bigint REFERENCES users(id),
  ADD COLUMN access_mode text NOT NULL DEFAULT 'scheme' CHECK(access_mode IN ('members','scheme')),
  ADD COLUMN access_revision bigint NOT NULL DEFAULT 1;
CREATE INDEX project_tribe ON projects(tribe_id);
CREATE INDEX project_owner ON projects(owner_id);
-- Миграция не закрывает проекты, для которых компания уже настроила собственную схему.
UPDATE projects SET owner_id=u.id FROM users u WHERE u.id=projects.created_by AND u.workspace_id=projects.workspace_id AND u.is_service=0;
ALTER TABLE projects ALTER COLUMN access_mode SET DEFAULT 'members';
