CREATE TABLE sla_notification_settings (
 policy_id BIGINT UNSIGNED PRIMARY KEY, revision INT UNSIGNED NOT NULL DEFAULT 1,
 enabled BOOLEAN NOT NULL DEFAULT FALSE, notify_assignee BOOLEAN NOT NULL DEFAULT TRUE,
 warning BOOLEAN NOT NULL DEFAULT TRUE, breached BOOLEAN NOT NULL DEFAULT TRUE,
 escalation_minutes INT UNSIGNED NULL, escalation_user_ids_json JSON NOT NULL,
 updated_by BIGINT UNSIGNED NOT NULL, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(policy_id) REFERENCES task_sla_policies(id) ON DELETE CASCADE,
 FOREIGN KEY(updated_by) REFERENCES users(id)
);
CREATE TABLE sla_notification_dispatches (
 fingerprint CHAR(64) PRIMARY KEY, task_id BIGINT UNSIGNED NOT NULL, policy_id BIGINT UNSIGNED NOT NULL,
 event_type VARCHAR(80) NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY(task_id,created_at), FOREIGN KEY(task_id) REFERENCES tasks(id) ON DELETE CASCADE,
 FOREIGN KEY(policy_id) REFERENCES task_sla_policies(id) ON DELETE CASCADE
);
CREATE TABLE maintenance_cursors (
 name VARCHAR(80) PRIMARY KEY, last_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
