CREATE TABLE ai_agent_versions (
 agent_id BIGINT UNSIGNED NOT NULL, revision INT UNSIGNED NOT NULL,
 name VARCHAR(160) NOT NULL, enabled BOOLEAN NOT NULL, config_json JSON NOT NULL,
 saved_by BIGINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(agent_id,revision), FOREIGN KEY(agent_id) REFERENCES ai_agents(id), FOREIGN KEY(saved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE ai_agent_run_state (
 run_id BIGINT UNSIGNED PRIMARY KEY, dry_run BOOLEAN NOT NULL DEFAULT FALSE,
 context_fingerprint CHAR(64) NOT NULL, heartbeat_at DATETIME NULL,
 FOREIGN KEY(run_id) REFERENCES ai_agent_runs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE ai_agent_run_steps (
 run_id BIGINT UNSIGNED NOT NULL, node_id VARCHAR(40) NOT NULL, position INT UNSIGNED NOT NULL,
 name VARCHAR(100) NOT NULL, node_type VARCHAR(30) NOT NULL,
 status ENUM('running','completed','failed') NOT NULL,
 input_count INT UNSIGNED NOT NULL DEFAULT 0, output_json JSON NULL,
 duration_ms INT UNSIGNED NULL, error_text VARCHAR(1000) NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(run_id,node_id), FOREIGN KEY(run_id) REFERENCES ai_agent_runs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE ai_agent_run_feedback (
 run_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL,
 rating TINYINT UNSIGNED NOT NULL, note VARCHAR(2000) NOT NULL DEFAULT '',
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(run_id,user_id), FOREIGN KEY(run_id) REFERENCES ai_agent_runs(id) ON DELETE CASCADE,
 FOREIGN KEY(user_id) REFERENCES users(id), CHECK(rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
