"use client";
import {useState} from 'react';
import ToolDialog from './ToolDialog.jsx';
import {useWork,useAction,workApi,Field,ErrorLine} from './WorkUI.jsx';
// Позволяет закрепить опубликованную часть проекта или сохранить текущую схему новой версией библиотеки.
export default function AgentPartsLibrary({projectId,flow,onAdd,onClose,notify}){
 const api=useWork(`agents/parts?project_id=${projectId}`),[name,setName]=useState(''),[partId,setPartId]=useState(''),[busy,act]=useAction(notify),[requestId,setRequestId]=useState(null);
 // Публикует неизменяемую версию без обновления уже добавленных в другие схемы блоков.
 function save(event){event.preventDefault();act(async()=>{const id=requestId||crypto.randomUUID();setRequestId(id);const part=api.value?.find(p=>String(p.id)===partId);await workApi('agents/parts',{method:'POST',body:JSON.stringify({project_id:projectId,part_id:part?.id||null,version:part?.version||0,name,flow,request_id:id})});setRequestId(null);setName('');await api.reload();notify('Версия общей части сохранена');});}
 return <ToolDialog title="Общие части сценариев" onClose={onClose}><ErrorLine error={api.error}/><p className="work-muted">Часть использует параметры, источники и разрешённые действия вызывающего агента. Вызовы модели входят в его общий лимит. До трёх уровней вложенности.</p><div className="agent-parts-list">{api.value?.map(part=><article className="work-card" key={part.id}><strong>{part.name}</strong><p>Версия {part.version} · {part.flow.nodes.length} блоков</p><button type="button" className="secondary" disabled={flow.nodes.length>=32} onClick={()=>{onAdd(part);onClose();}}>Добавить версию {part.version}</button></article>)}</div><form onSubmit={save}><h3>Сохранить текущую схему в библиотеку</h3><Field label="Куда сохранить"><select disabled={Boolean(requestId)||busy} value={partId} onChange={e=>setPartId(e.target.value)}><option value="">Новая общая часть</option>{api.value?.map(p=><option key={p.id} value={p.id}>{p.name} · следующая версия</option>)}</select></Field><Field label="Название общей части"><input required disabled={Boolean(requestId)||busy} minLength={2} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></Field><button className="primary" disabled={busy||!flow.nodes.length}>Сохранить версию</button>{requestId&&!busy&&<button type="button" className="text-button" onClick={()=>setRequestId(null)}>Изменить запрос</button>}</form><p className="work-muted">Обновление библиотеки не меняет существующие схемы. Для перехода на новую версию добавьте её явно и проверьте связи.</p></ToolDialog>;
}
