"use client";
import AgentCanvas from "./AgentCanvas.jsx";
import {useState} from 'react';
import {Field,workApi,useWork,useAction,ErrorLine,Empty} from './WorkUI.jsx';
import ToolDialog from './ToolDialog.jsx';
import {AGENT_METRICS,AGENT_OPERATOR_LABELS,AGENT_NODE_LABELS,AGENT_SOURCE_LABELS,AGENT_ACTION_CATALOG,AGENT_FIELD_LABELS} from '../lib/agent-catalog.js';

const toggle=(list,key,on)=>on?[...new Set([...list,key])]:list.filter(k=>k!==key);
const types={string:'Текст',number:'Число',boolean:'Да / нет'};
const numberIds=value=>[...new Set(value.split(/[,\s]+/).map(Number).filter(n=>Number.isSafeInteger(n)&&n>0))];
export function downloadAgentJson(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function defaultAgentInputs(defs){return Object.fromEntries((defs||[]).filter(d=>d.default!==undefined).map(d=>[d.key,d.default]));}
export function InputValues({definitions,value,onChange}){return <div className="studio-inputs">{definitions.map(d=><Field key={d.key} label={`${d.label}${d.required?' *':''}`}>
 {d.type==='boolean'?<select value={value[d.key]===undefined?'':String(value[d.key])} onChange={e=>{const v={...value};if(e.target.value==='')delete v[d.key];else v[d.key]=e.target.value==='true';onChange(v);}}><option value="">Не задано</option><option value="true">Да</option><option value="false">Нет</option></select>:<input type={d.type==='number'?'number':'text'} step="any" maxLength={4000} required={d.required} value={value[d.key]??''} onChange={e=>{const v={...value};if(e.target.value==='')delete v[d.key];else v[d.key]=d.type==='number'?Number(e.target.value):e.target.value;onChange(v);}}/>}
 </Field>)}</div>;}
export function InputDefinitions({value,onChange}){
 const set=(i,p)=>onChange(value.map((d,j)=>i===j?{...d,...p}:d));
 return <details className="agent-source"><summary>Входные параметры · {value.length}</summary><p className="work-muted">Заполняются при запуске или через API. Для событий и расписаний задайте значения обязательных параметров по умолчанию.</p>
 {value.map((d,i)=><div className="studio-variable" key={i}><div className="studio-grid"><Field label="Ключ (латиница)"><input maxLength={32} value={d.key} onChange={e=>set(i,{key:e.target.value})}/></Field><Field label="Название"><input maxLength={100} value={d.label} onChange={e=>set(i,{label:e.target.value})}/></Field><Field label="Тип"><select value={d.type} onChange={e=>set(i,{type:e.target.value,default:e.target.value==='boolean'?false:e.target.value==='number'?0:''})}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field></div>
 <InputValues definitions={[{...d,label:'Значение по умолчанию',required:false}]} value={d.default===undefined?{}:{[d.key]:d.default}} onChange={v=>{const next={...d};if(v[d.key]===undefined)delete next.default;else next.default=v[d.key];onChange(value.map((x,j)=>j===i?next:x));}}/>
 <div className="studio-toolbar"><label className="connector-check"><input type="checkbox" checked={d.required} onChange={e=>set(i,{required:e.target.checked})}/>Обязательный</label><button className="text-button" onClick={()=>onChange(value.filter((_,j)=>i!==j))}>Удалить параметр</button></div></div>)}
 <button className="secondary" disabled={value.length>=12} onClick={()=>{let n=value.length+1;while(value.some(d=>d.key===`param_${n}`))n++;onChange([...value,{key:`param_${n}`,label:`Параметр ${n}`,type:'string',required:false}]);}}>+ Параметр</button></details>;
}
export function ConditionEditor({value,onChange,inputs=[],nodes=[]}){
 const paths=[...Object.entries(AGENT_METRICS).map(([k,v])=>[`metrics.${k}`,v]),...inputs.map(d=>[`inputs.${d.key}`,d.label]),['trigger.event_type','Тип события'],['trigger.task_id','ID задачи события'],...nodes.flatMap(n=>n.type==='analyze'?[{key:'summary',label:'вывод'},...n.fields.map(f=>({key:`values.${f.key}`,label:f.key}))].map(f=>[`steps.${n.id}.${f.key}`,`${n.name} · ${f.label}`]):n.type==='condition'?[[`steps.${n.id}.matched`,`${n.name} · результат`]]:n.type==='filter'?[[`steps.${n.id}.count`,`${n.name} · количество`]]:[[`steps.${n.id}.summary`,`${n.name} · текст`]])];
 const set=(i,patch)=>onChange({...value,rules:value.rules.map((r,j)=>i===j?{...r,...patch}:r)});
 return <div className="studio-conditions"><Field label="Условие выполняется, если"><select value={value.mode} onChange={e=>onChange({...value,mode:e.target.value})}><option value="all">Совпали все правила</option><option value="any">Совпало любое правило</option></select></Field>
 {value.rules.map((r,i)=><div className="studio-rule" key={i}><Field label="Значение"><select value={r.path} onChange={e=>set(i,{path:e.target.value})}>{!paths.some(p=>p[0]===r.path)&&<option value={r.path}>{r.path}</option>}{paths.map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Сравнение"><select value={r.operator} onChange={e=>set(i,{operator:e.target.value})}>{Object.entries(AGENT_OPERATOR_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>
 {!['empty','not_empty'].includes(r.operator)&&<><Field label="Тип"><select value={typeof r.value==='undefined'?'string':typeof r.value} onChange={e=>set(i,{value:e.target.value==='number'?0:e.target.value==='boolean'?true:''})}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="С чем сравнить">{typeof r.value==='boolean'?<select value={String(r.value)} onChange={e=>set(i,{value:e.target.value==='true'})}><option value="true">Да</option><option value="false">Нет</option></select>:<input type={typeof r.value==='number'?'number':'text'} step="any" maxLength={4000} value={r.value??''} onChange={e=>set(i,{value:typeof r.value==='number'?Number(e.target.value):e.target.value})}/>}</Field></>}
 <button className="text-button" aria-label={`Удалить правило ${i+1}`} onClick={()=>onChange({...value,rules:value.rules.filter((_,j)=>j!==i)})}>Удалить</button></div>)}
 <button className="secondary" disabled={value.rules.length>=12} onClick={()=>onChange({...value,rules:[...value.rules,{path:'metrics.task_count',operator:'greater',value:0}]})}>+ Правило</button><p className="work-muted">Без правил условие истинно. Метрики считаются по данным, вошедшим в контекст; для сроков выберите атрибут «Срок».</p></div>;
}
export function SchedulePanel({trigger,onChange}){const s=trigger.schedule,set=p=>onChange({...trigger,schedule:{...s,...p}});return <div className="agent-source"><Field label="Повторение"><select value={s.mode} onChange={e=>set({mode:e.target.value})}><option value="interval">Через интервал</option><option value="daily">Ежедневно</option><option value="weekly">По дням недели</option></select></Field>{s.mode==='interval'?<Field label="Интервал в минутах (15–10080)"><input type="number" min={15} max={10080} value={trigger.interval_minutes} onChange={e=>onChange({...trigger,interval_minutes:Number(e.target.value)})}/></Field>:<><div className="studio-grid"><Field label="Время"><input type="time" value={s.time} onChange={e=>set({time:e.target.value})}/></Field><Field label="Часовой пояс IANA"><input value={s.timezone} maxLength={100} placeholder="Europe/Moscow" onChange={e=>set({timezone:e.target.value})}/></Field></div><button className="text-button" onClick={()=>set({timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})}>Взять часовой пояс браузера</button>{s.mode==='weekly'&&<div className="agent-inline-checks">{[[1,'Пн'],[2,'Вт'],[3,'Ср'],[4,'Чт'],[5,'Пт'],[6,'Сб'],[0,'Вс']].map(([d,label])=><label key={d}><input type="checkbox" checked={s.weekdays.includes(d)} onChange={e=>set({weekdays:toggle(s.weekdays,d,e.target.checked)})}/>{label}</label>)}</div>}</>}</div>;}
export function FlowEditor({config,onChange,profiles,people=[]}){
 const flow=config.flow,nodes=flow.nodes,[kind,setKind]=useState('analyze'),[selected,setSelected]=useState(nodes[0]?.id||null),setNodes=next=>onChange({...flow,nodes:next,positions:Object.fromEntries(Object.entries(flow.positions||{}).filter(([id])=>next.some(n=>n.id===id)))}),set=(i,p)=>setNodes(nodes.map((n,j)=>i===j?{...n,...p}:n));
 const add=()=>{let n=1;while(nodes.some(x=>x.id===`step_${n}`))n++;const base={id:`step_${n}`,name:AGENT_NODE_LABELS[kind],type:kind,next:''},extra=kind==='approval'?{message:'Проверьте промежуточные выводы и разрешите продолжение.',reviewer_ids:[],timeout_hours:48}:kind==='analyze'?{profile_id:null,prompt:'Проанализируй источники и выдели факты, необходимые для следующего шага.',fields:[]}:kind==='condition'?{condition:{mode:'all',rules:[]},on_true:'',on_false:'$end'}:kind==='filter'?{kinds:['task'],limit:100}:{text:'{{steps.step_1.summary}}'};setNodes([...nodes,{...base,...extra}]);setSelected(base.id);};
 const target=(i,key,label)=><Field label={label}><select value={nodes[i][key]} onChange={e=>set(i,{[key]:e.target.value})}><option value="">Следующий шаг по порядку</option><option value="$end">Перейти к итоговому ответу</option>{nodes.slice(i+1).map(n=><option key={n.id} value={n.id}>{n.name} · {n.id}</option>)}</select></Field>;
 return <div className="studio-flow"><p>Шаги выполняются сверху вниз. Условие выбирает ветку; каждый шаг может перейти вперёд или к итоговому ответу. После цепочки итоговая модель формирует сводку и предложения действий.</p>
 <AgentCanvas flow={flow} onChange={onChange} selected={selected} onSelect={setSelected}/><Field label="Настройка шага"><select value={selected||''} onChange={e=>setSelected(e.target.value)}><option value="">Выберите блок на схеме</option>{nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></Field>
 <div className="studio-flow-bookend"><span>Начало</span><strong>Источники + входные параметры</strong></div>
 {nodes.map((n,i)=>selected===n.id&&<article className={`studio-node studio-node-${n.type}`} key={n.id}><header><span className="studio-node-number">{i+1}</span><div><strong>{AGENT_NODE_LABELS[n.type]}</strong><code>{n.id}</code></div><button className="text-button" onClick={()=>setNodes(nodes.filter((_,j)=>j!==i).map(v=>({...v,...(v.next===n.id?{next:''}:{}),...(v.type==='condition'?{on_true:v.on_true===n.id?'':v.on_true,on_false:v.on_false===n.id?'':v.on_false}:{})})))}>Удалить</button></header>
 <Field label="Название шага"><input value={n.name} maxLength={100} onChange={e=>set(i,{name:e.target.value})}/></Field>
 {n.type==='analyze'&&<><Field label="Модель шага"><select value={n.profile_id||''} onChange={e=>set(i,{profile_id:e.target.value||null})}><option value="">Основная модель агента</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.name} · {p.model}</option>)}</select></Field><Field label="Задание"><textarea rows={4} minLength={10} maxLength={6000} value={n.prompt} onChange={e=>set(i,{prompt:e.target.value})}/></Field>
 <details><summary>Структурированные поля ответа · {n.fields.length}</summary>{n.fields.map((f,j)=><div className="studio-field-row" key={j}><Field label="Ключ поля"><input value={f.key} maxLength={32} onChange={e=>set(i,{fields:n.fields.map((v,k)=>k===j?{...v,key:e.target.value}:v)})}/></Field><Field label="Тип"><select value={f.type} onChange={e=>set(i,{fields:n.fields.map((v,k)=>k===j?{...v,type:e.target.value}:v)})}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><button className="text-button" onClick={()=>set(i,{fields:n.fields.filter((_,k)=>j!==k)})}>Удалить поле</button></div>)}<button className="secondary" disabled={n.fields.length>=10} onClick={()=>{let k=n.fields.length+1;while(n.fields.some(f=>f.key===`value_${k}`))k++;set(i,{fields:[...n.fields,{key:`value_${k}`,type:'number'}]});}}>+ Поле результата</button></details></>}
 {n.type==='approval'&&<><Field label="Что должен проверить согласующий"><textarea rows={3} maxLength={2000} value={n.message} onChange={e=>set(i,{message:e.target.value})}/></Field><Field label="Ожидание, часов (1–168)"><input type="number" min={1} max={168} value={n.timeout_hours} onChange={e=>set(i,{timeout_hours:Number(e.target.value)})}/></Field><p className="work-muted">Без выбора сотрудника согласовать может любой пользователь с правом «Подтверждение действий агента».</p><div className="agent-inline-checks">{people.map(u=><label key={u.id}><input type="checkbox" checked={n.reviewer_ids.includes(Number(u.id))} onChange={e=>set(i,{reviewer_ids:toggle(n.reviewer_ids,Number(u.id),e.target.checked)})}/>{u.display_name}</label>)}</div></>}
 {n.type==='condition'&&<><ConditionEditor value={n.condition} inputs={config.inputs} nodes={nodes.slice(0,i)} onChange={condition=>set(i,{condition})}/><div className="studio-grid">{target(i,'on_true','Да →')}{target(i,'on_false','Нет →')}</div></>}
 {n.type==='filter'&&<><div className="agent-inline-checks">{Object.entries(AGENT_SOURCE_LABELS).map(([k,label])=><label key={k}><input type="checkbox" checked={n.kinds.includes(k)} onChange={e=>set(i,{kinds:toggle(n.kinds,k,e.target.checked)})}/>{label}</label>)}</div><Field label="Максимум источников после фильтра"><input type="number" min={1} max={200} value={n.limit} onChange={e=>set(i,{limit:Number(e.target.value)})}/></Field></>}
 {['template','stop'].includes(n.type)&&<Field label={n.type==='stop'?'Итог без дальнейших обращений к модели':'Текст для следующих шагов'}><textarea rows={4} maxLength={8000} value={n.text} onChange={e=>set(i,{text:e.target.value})}/></Field>}
 {!['condition','stop'].includes(n.type)&&target(i,'next','Далее →')}
 </article>)}
 <div className="studio-add"><Field label="Тип нового шага"><select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(AGENT_NODE_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><button className="secondary" disabled={nodes.length>=16} onClick={add}>+ Добавить шаг</button></div>
 <div className="studio-flow-bookend"><span>Итог</span><strong>Основная модель → проверка ответа → действия</strong></div>
 <Field label="Максимум обращений к модели за запуск (1–12)"><input type="number" min={1} max={12} value={flow.max_calls} onChange={e=>onChange({...flow,max_calls:Number(e.target.value)})}/></Field>
 <details className="agent-source"><summary>Переменные для инструкций</summary><p>Вставьте нужную переменную в задание или текстовый шаг.</p><div className="studio-variable-help"><code>{'{{metrics.task_count}}'}</code>{config.inputs.map(d=><code key={d.key}>{`{{inputs.${d.key}}}`}</code>)}{nodes.flatMap(n=>[<code key={n.id}>{`{{steps.${n.id}.${n.type==='filter'?'count':n.type==='condition'?'matched':'summary'}}}`}</code>,...(n.fields||[]).map(f=><code key={`${n.id}.${f.key}`}>{`{{steps.${n.id}.values.${f.key}}}`}</code>)])}</div><p className="work-muted">В шаге доступны только результаты предшествующих шагов. Пропущенные значения заменяются пустой строкой. Произвольный код не выполняется.</p></details></div>;
}
export function ExtraSources({source,onChange,options,ChoiceList}){
 const task=source.tasks,setTask=p=>onChange({...source,tasks:{...task,...p}}),set=p=>onChange({...source,...p});
 return <><details className="agent-source"><summary>Дополнительные данные и фильтры задач</summary><div className="studio-grid"><Field label="Текст в названии или описании"><input maxLength={200} value={task.query} onChange={e=>setTask({query:e.target.value})}/></Field><Field label="Изменены за последние N дней (0 — любой срок)"><input type="number" min={0} max={365} value={task.updated_days} onChange={e=>setTask({updated_days:Number(e.target.value)})}/></Field></div><Field label="ID исполнителей через запятую"><input defaultValue={task.assignee_ids.join(', ')} onBlur={e=>setTask({assignee_ids:numberIds(e.target.value)})}/></Field><div className="work-checks"><label><input type="checkbox" checked={task.include_comments} onChange={e=>setTask({include_comments:e.target.checked})}/>Последние 10 открытых комментариев</label><label><input type="checkbox" checked={task.include_checklist} onChange={e=>setTask({include_checklist:e.target.checked})}/>До 30 пунктов чек-листа</label></div><h3>Пользовательские атрибуты</h3><div className="agent-inline-checks">{(options.fields||[]).map(f=><label key={f.code}><input type="checkbox" checked={task.custom_fields.includes(f.code)} onChange={e=>setTask({custom_fields:toggle(task.custom_fields,f.code,e.target.checked)})}/>{f.name}</label>)}</div></details>
 <fieldset className="agent-source"><legend><label><input type="checkbox" checked={source.semantic.enabled} onChange={e=>set({semantic:{...source.semantic,enabled:e.target.checked}})}/> Поиск по смыслу в базе знаний</label></legend>{source.semantic.enabled&&<><ChoiceList label="пространства поиска" items={(options.spaces||[]).map(s=>({...s,title:s.name}))} value={source.semantic.space_ids} limit={10} onChange={ids=>set({semantic:{...source.semantic,space_ids:ids}})}/><Field label="Запрос (поддерживает переменные inputs)"><textarea rows={2} maxLength={2000} value={source.semantic.query} onChange={e=>set({semantic:{...source.semantic,query:e.target.value}})}/></Field><div className="studio-grid"><Field label="Максимум найденных фрагментов"><input type="number" min={1} max={10} value={source.semantic.limit} onChange={e=>set({semantic:{...source.semantic,limit:Number(e.target.value)}})}/></Field><Field label="Минимальное сходство (0.1–1)"><input type="number" min={0.1} max={1} step={0.05} value={source.semantic.min_score} onChange={e=>set({semantic:{...source.semantic,min_score:Number(e.target.value)}})}/></Field></div><p className="work-muted">Используется настроенный индекс поиска. Запуск расходует токены embeddings. В предпросмотре источников запрос к модели не выполняется.</p></>}</fieldset>
 <details className="agent-source"><summary>Статьи из пространств базы знаний</summary><ChoiceList label="пространства" items={(options.spaces||[]).map(s=>({...s,title:s.name}))} value={source.knowledge.space_ids} limit={10} onChange={ids=>set({knowledge:{...source.knowledge,space_ids:ids}})}/><Field label="Поиск по названию и содержимому"><input maxLength={200} value={source.knowledge.query} onChange={e=>set({knowledge:{...source.knowledge,query:e.target.value}})}/></Field><Field label="Последних обновлённых опубликованных статей"><input type="number" min={1} max={20} value={source.knowledge.limit} onChange={e=>set({knowledge:{...source.knowledge,limit:Number(e.target.value)}})}/></Field></details>
 {[['chat_channel_ids','Переписка чатов',options.channels],['recording_ids','Расшифровки записей встреч',options.recordings]].map(([key,label,items])=><details className="agent-source" key={key}><summary>{label} · {source[key].length}</summary><ChoiceList label={label.toLowerCase()} items={items||[]} value={source[key]} limit={5} onChange={ids=>set({[key]:ids})}/><p className="work-muted">{key==='recording_ids'?'Сначала расшифруйте запись в карточке встречи. Здесь используются готовые расшифровки.':'До 50 последних сообщений каждого выбранного чата.'}</p></details>)}
 <div className="work-checks"><label><input type="checkbox" checked={source.planning} onChange={e=>set({planning:e.target.checked})}/>Спринты и релизы проекта</label><label><input type="checkbox" checked={source.objectives} onChange={e=>set({objectives:e.target.checked})}/>Цели и ключевые результаты проекта</label></div></>;
}
export function ActionPolicy({config,onChange,rights,options,ChoiceList}){
 const p=config.policy,set=v=>onChange({policy:{...p,...v}});
 return <><div className="work-checks">{AGENT_ACTION_CATALOG.map(a=><label key={a.key}><input type="checkbox" disabled={!!a.permission&&!rights[a.permission]} checked={config.actions.includes(a.key)} onChange={e=>onChange({actions:toggle(config.actions,a.key,e.target.checked)})}/>{a.name}{a.permission&&!rights[a.permission]?' · нет права':''}</label>)}</div>
 {config.actions.includes('update_task')&&<fieldset className="agent-source"><legend>Разрешённые атрибуты для изменения</legend><div className="agent-inline-checks">{['title','description','priority','start_date','due_date','progress','estimate_minutes'].map(k=><label key={k}><input type="checkbox" checked={p.editable_fields.includes(k)} onChange={e=>set({editable_fields:toggle(p.editable_fields,k,e.target.checked)})}/>{AGENT_FIELD_LABELS[k]}</label>)}</div></fieldset>}
 {config.actions.includes('move_task')&&<fieldset className="agent-source"><legend>Разрешённые этапы</legend><div className="agent-inline-checks">{(options.stages||[]).map(s=><label key={s.id}><input type="checkbox" checked={p.allowed_stage_ids.includes(s.id)} onChange={e=>set({allowed_stage_ids:toggle(p.allowed_stage_ids,s.id,e.target.checked)})}/>{s.name}</label>)}</div></fieldset>}
 {config.actions.includes('assign_task')&&<Field label="ID допустимых исполнителей через запятую"><input defaultValue={p.allowed_assignee_ids.join(', ')} onBlur={e=>set({allowed_assignee_ids:numberIds(e.target.value)})}/></Field>}
 {config.actions.includes('create_article')&&<div className="agent-source"><h3>Пространства для черновиков</h3><ChoiceList label="пространства с правом редактирования" items={(options.spaces||[]).filter(s=>s.can_edit).map(s=>({...s,title:s.name}))} value={p.article_space_ids} limit={10} onChange={ids=>set({article_space_ids:ids})}/></div>}
 {config.actions.includes('chat_message')&&<div className="agent-source"><h3>Чаты для отправки</h3><ChoiceList label="чаты" items={options.channels||[]} value={p.chat_channel_ids} limit={5} onChange={ids=>set({chat_channel_ids:ids})}/><p className="work-muted">Проверьте получателей: в сообщении могут оказаться сведения из всех выбранных источников.</p></div>}
 <details className="agent-source" open><summary>Проверка качества ответа</summary><Field label="Минимальная уверенность модели (0–1)"><input type="number" min={0} max={1} step={0.05} value={p.min_confidence} onChange={e=>set({min_confidence:Number(e.target.value)})}/></Field><div className="work-checks"><label><input type="checkbox" checked={p.require_citations} onChange={e=>set({require_citations:e.target.checked})}/>Требовать ссылки на источники</label><label><input type="checkbox" checked={p.require_reasons} onChange={e=>set({require_reasons:e.target.checked})}/>Требовать обоснование каждого действия</label><label><input type="checkbox" checked={p.redact_emails} onChange={e=>set({redact_emails:e.target.checked})}/>Скрывать email в источниках перед передачей модели</label></div><p className="work-muted">Если проверка качества не пройдена, автоматические действия ждут решения человека. Уверенность — самооценка модели, а не гарантия точности. Скрытие email не обезличивает все данные.</p></details></>;
}
export function AgentVersions({agent,notify,onClose,onRestored}){
 const api=useWork(`agents/${agent.id}/versions`),[busy,act]=useAction(notify);
 return <ToolDialog title={`Версии · ${agent.name}`} onClose={onClose}><ErrorLine error={api.error}/><p>Восстановление создаёт новую версию и ставит агента на паузу. Права и доступность источников проверяются заново.</p><div className="studio-versions">{api.value?.map(v=><article key={v.revision}><div><strong>Версия {v.revision} · {v.name}</strong><p className="work-muted">{v.saved_by} · {String(v.created_at).replace('T',' ').slice(0,19)}</p></div><details><summary>Настройки версии</summary><pre className="studio-json">{JSON.stringify(v.config,null,2)}</pre></details><button className="secondary" disabled={busy||v.revision===agent.revision} onClick={()=>act(async()=>{await workApi(`agents/${agent.id}/restore`,{method:'POST',body:JSON.stringify({revision:agent.revision,version:v.revision})});notify('Версия восстановлена. Агент на паузе');await onRestored();onClose();})}>Восстановить</button></article>)}</div>{!api.value?.length&&<Empty>{api.loading?'Загружаем…':'История появится после следующего сохранения агента'}</Empty>}</ToolDialog>;
}
export function AgentAnalytics({projectId}){
 const [days,setDays]=useState(30),api=useWork(`agents/analytics?project_id=${projectId}&days=${days}`),list=api.value?.summary||[],runs=list.reduce((n,s)=>n+Number(s.runs),0),tokens=list.reduce((n,s)=>n+Number(s.tokens),0),count=s=>Number(list.find(r=>r.status===s)?.runs||0);
 return <div className="studio-analytics"><div className="studio-toolbar"><h2>Работа агентов</h2><Field label="Период"><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 дней</option><option value={30}>30 дней</option><option value={90}>90 дней</option></select></Field></div><ErrorLine error={api.error}/><div className="studio-stats">{[[runs,'запусков'],[count('completed'),'завершено'],[count('review'),'ждут решения'],[count('failed'),'ошибок'],[tokens.toLocaleString('ru-RU'),'токенов сообщено']].map(([v,label])=><div key={label}><strong>{api.loading&&!api.value?'…':v}</strong><span>{label}</span></div>)}</div>{api.value?.agents?.some(a=>Number(a.runs)>0)&&<div className="studio-ranking">{api.value.agents.filter(a=>Number(a.runs)>0).slice(0,5).map(a=><div key={a.id}><span>{a.name}</span><meter min={0} max={Math.max(1,runs)} value={Number(a.runs)} aria-label={`Запусков: ${a.runs}`}/><strong>{a.runs}</strong></div>)}</div>}</div>;
}
