"use client";
import {useEffect,useState} from 'react';
import ToolDialog from './ToolDialog.jsx';
import {workApi,useWork,useAction,Field,ErrorLine,Empty} from './WorkUI.jsx';
import {AGENT_ACTION_CATALOG,AGENT_SOURCE_LABELS,AGENT_FIELD_LABELS} from '../lib/agent-catalog.js';
const toggle=(list,key,on)=>on?[...new Set([...list,key])]:list.filter(v=>v!==key);

export function AgentDesigner({projectId,profiles,notify,onClose,onCreated}){
 const [description,setDescription]=useState(''),[profile,setProfile]=useState(profiles[0]?.id||''),[busy,act]=useAction(notify),[requestId,setRequestId]=useState(()=>crypto.randomUUID());
 return <ToolDialog title="Создать агента по описанию" subtitle="Опишите цель, данные и ожидаемый результат." onClose={()=>!busy&&onClose()}><form className="workbench-form" onSubmit={e=>{e.preventDefault();act(async()=>{const generated=await workApi('agents/design',{method:'POST',body:JSON.stringify({request_id:requestId,project_id:projectId,profile_id:profile,description})});onCreated(generated);});}}>
  <Field label="Модель для проектирования"><select required value={profile} onChange={e=>{setProfile(e.target.value);setRequestId(crypto.randomUUID());}} disabled={busy}><option value="">Выберите модель</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {p.model}</option>)}</select></Field>
  <Field label="Какую работу поручить агенту?"><textarea required minLength={20} maxLength={6000} rows={7} disabled={busy} value={description} onChange={e=>{setDescription(e.target.value);setRequestId(crypto.randomUUID());}} placeholder="Каждое утро анализировать просроченные задачи команды, выделять блокеры и готовить сводку со ссылками на задачи."/></Field>
  <p className="integration-notice">Генерация расходует токены выбранной модели. Результат откроется как редактируемый черновик: проверьте источники, расписание и права перед публикацией.</p>
  <div className="studio-toolbar"><button className="primary" disabled={busy||!profile}>{busy?'Проектируем…':'Создать черновик'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setRequestId(crypto.randomUUID())}>Новая попытка</button></div>
 </form></ToolDialog>;
}

export function AgentActionPreview({runId}){
 const api=useWork(`agents/runs/${runId}/preview`);
 return <details className="agent-source" open><summary>Что изменится</summary><ErrorLine error={api.error}/>{api.loading&&!api.value&&<p>Сверяем текущее состояние…</p>}{api.value?.items.map(item=><article className="action-diff" key={item.index}>
  <strong>{item.index+1}. {AGENT_ACTION_CATALOG.find(a=>a.key===item.type)?.name}{item.task_id?` · задача #${item.task_id}`:''}</strong>
  <div className="action-diff-columns"><div><small>Сейчас</small>{item.before?Object.entries(item.before).map(([k,v])=><p key={k}><b>{AGENT_FIELD_LABELS[k]||k}: </b>{v==null?'Не задано':String(v)}</p>):<p>Новая запись</p>}</div><div><small>После применения</small>{Object.entries(item.after).map(([k,v])=><p key={k}><b>{AGENT_FIELD_LABELS[k]||({body:'Текст',space_id:'Пространство',channel_id:'Чат'})[k]||k}: </b>{v==null?'Не задано':String(v)}</p>)}</div></div>
  {item.reason&&<ErrorLine error={item.reason}/>}
 </article>)}<p className="work-muted">Права и версии проверяются повторно при применении. После новых изменений может понадобиться другой запуск.</p><button className="secondary" onClick={api.reload} disabled={api.loading}>Обновить сравнение</button></details>;
}

export function AgentGate({run,rights,notify,onChanged}){
 const [note,setNote]=useState(''),[busy,act]=useAction(notify),gate=run.checkpoint;
 if(run.status!=='review'||gate?.status!=='waiting')return null;
 const decide=decision=>act(async()=>{await workApi(`agents/runs/${run.id}/gate`,{method:'POST',body:JSON.stringify({node_id:gate.node_id,revision:gate.revision,decision,note})});await onChanged();notify(decision==='approve'?'Согласовано. Агент продолжит со следующего шага':'Сценарий отклонён');});
 return <section className="agent-gate"><span className="overline">СОГЛАСОВАНИЕ ШАГА</span><h3>{run.meta.gate_message||'Проверьте промежуточный результат'}</h3><p>Ожидание до {new Date(String(gate.expires_at).replace(' ','T')+'Z').toLocaleString('ru-RU')}. Предыдущие шаги повторно не выполняются.</p>{rights['agent.approve']&&<><Field label="Комментарий к решению"><textarea rows={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></Field><div className="studio-toolbar"><button className="primary" disabled={busy} onClick={()=>decide('approve')}>Согласовать и продолжить</button><button className="secondary" disabled={busy} onClick={()=>decide('reject')}>Отклонить</button></div></>}</section>;
}

const emptyCase=i=>({key:`case_${i}`,name:`Пример ${i}`,task_id:null,inputs:{},expected:{summary_contains:[],summary_excludes:[],required_actions:[],forbidden_actions:[],max_actions:20,min_confidence:0,require_citations:false}});
const lines=v=>v.split('\n').map(s=>s.trim()).filter(Boolean);
export function AgentLaboratory({agent,profiles,notify,onClose,onRun}){
 const base=`agents/${agent.id}/evaluations`,api=useWork(base),versions=useWork(`agents/${agent.id}/versions`),[suite,setSuite]=useState(null),[batch,setBatch]=useState(null),[selected,setSelected]=useState(''),[compare,setCompare]=useState(true),[busy,act]=useAction(notify);
 const [variant,setVariant]=useState([{name:'A · опубликованная',version:'published',profile_id:agent.config.profile_id},{name:'B · черновик',version:agent.draft_revision?'draft':'published',profile_id:agent.config.profile_id}]);
 const editCase=(i,p)=>setSuite(s=>({...s,cases:s.cases.map((c,j)=>i===j?{...c,...p}:c)}));
 return <ToolDialog title={`Лаборатория · ${agent.name}`} onClose={()=>!busy&&onClose()}><div className="workbench-form"><ErrorLine error={api.error||versions.error}/><p className="integration-notice">До 10 примеров × 2 варианта. Все запуски тестовые, действия не применяются. Варианты получают одинаковый снимок источников первого варианта. Используются ваши права и обычные лимиты ИИ; поиск по смыслу также расходует токены.</p>
  {!suite&&<><div className="studio-toolbar"><Field label="Набор проверок"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Выберите набор</option>{api.value?.suites.map(s=><option key={s.id} value={s.id}>{s.name} · {s.cases.length} примеров</option>)}</select></Field><button className="secondary" onClick={()=>setSuite({name:'Проверка агента',cases:[emptyCase(1)]})}>+ Набор</button>{selected&&<button className="secondary" onClick={()=>setSuite(structuredClone(api.value.suites.find(s=>s.id===Number(selected))))}>Изменить</button>}</div>
   <label className="connector-check"><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/>Сравнить два варианта</label><div className="studio-grid">{variant.slice(0,compare?2:1).map((v,i)=><fieldset className="agent-source" key={i}><legend>Вариант {i?'B':'A'}</legend><Field label="Название"><input maxLength={160} value={v.name} onChange={e=>setVariant(variant.map((x,j)=>i===j?{...x,name:e.target.value}:x))}/></Field><Field label="Версия"><select value={v.version} onChange={e=>setVariant(variant.map((x,j)=>i===j?{...x,version:['draft','published'].includes(e.target.value)?e.target.value:Number(e.target.value)}:x))}><option value="published">Опубликованная</option>{Boolean(agent.draft_revision)&&<option value="draft">Сохранённый черновик</option>}{versions.value?.map(v=><option key={v.revision} value={v.revision}>Версия {v.revision}</option>)}</select></Field><Field label="Основная модель"><select value={v.profile_id} onChange={e=>setVariant(variant.map((x,j)=>i===j?{...x,profile_id:e.target.value}:x))}>{profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {p.model}</option>)}</select></Field></fieldset>)}</div>
   <button className="primary" disabled={busy||!selected} onClick={()=>act(async()=>{const s=api.value.suites.find(s=>s.id===Number(selected));const b=await workApi(`${base}/batches`,{method:'POST',body:JSON.stringify({suite_id:s.id,suite_revision:s.revision,variants:variant.slice(0,compare?2:1)})});setBatch(b.id);await api.reload();})}>{busy?'Подготавливаем выборку…':'Запустить пакет проверок'}</button>
  </>}
  {suite&&<form className="workbench-form" onSubmit={e=>{e.preventDefault();act(async()=>{const {id,agent_id,created_by,updated_at,...payload}=suite;const r=await workApi(`${base}/suites${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(payload)});setSelected(String(r.id));setSuite(null);await api.reload();});}}><Field label="Название набора"><input required minLength={2} maxLength={160} value={suite.name} onChange={e=>setSuite({...suite,name:e.target.value})}/></Field>
   {suite.cases.map((c,i)=><fieldset className="agent-source" key={c.key}><legend>{c.name}</legend><div className="studio-grid"><Field label="Название примера"><input required maxLength={160} value={c.name} onChange={e=>editCase(i,{name:e.target.value})}/></Field><Field label="ID задачи (для режима одной задачи)"><input type="number" min={1} value={c.task_id||''} onChange={e=>editCase(i,{task_id:e.target.value?Number(e.target.value):null})}/></Field></div>
    <Field label="Входные параметры в JSON"><textarea rows={2} defaultValue={JSON.stringify(c.inputs)} onBlur={e=>{try{const inputs=JSON.parse(e.target.value);if(!inputs||Array.isArray(inputs)||typeof inputs!=='object')throw new Error();editCase(i,{inputs});e.target.setCustomValidity('');}catch{e.target.setCustomValidity('Укажите JSON-объект');e.target.reportValidity();}}}/></Field>
    <div className="studio-grid"><Field label="Сводка должна содержать (по строке)"><textarea rows={3} defaultValue={c.expected.summary_contains.join('\n')} onBlur={e=>editCase(i,{expected:{...c.expected,summary_contains:lines(e.target.value)}})}/></Field><Field label="Сводка не должна содержать"><textarea rows={3} defaultValue={c.expected.summary_excludes.join('\n')} onBlur={e=>editCase(i,{expected:{...c.expected,summary_excludes:lines(e.target.value)}})}/></Field></div>
    <div className="agent-inline-checks">{AGENT_ACTION_CATALOG.map(a=><label key={a.key}><input type="checkbox" checked={c.expected.required_actions.includes(a.key)} onChange={e=>editCase(i,{expected:{...c.expected,required_actions:toggle(c.expected.required_actions,a.key,e.target.checked)}})}/>Ожидать: {a.name}</label>)}</div>
    <div className="studio-grid"><Field label="Максимум действий"><input type="number" min={0} max={20} value={c.expected.max_actions} onChange={e=>editCase(i,{expected:{...c.expected,max_actions:Number(e.target.value)}})}/></Field><Field label="Минимальная самооценка уверенности"><input type="number" min={0} max={1} step={0.1} value={c.expected.min_confidence} onChange={e=>editCase(i,{expected:{...c.expected,min_confidence:Number(e.target.value)}})}/></Field></div><label className="connector-check"><input type="checkbox" checked={c.expected.require_citations} onChange={e=>editCase(i,{expected:{...c.expected,require_citations:e.target.checked}})}/>Требовать ссылки на источники</label><button type="button" className="text-button" disabled={suite.cases.length===1} onClick={()=>setSuite({...suite,cases:suite.cases.filter((_,j)=>i!==j)})}>Удалить пример</button>
   </fieldset>)}<div className="studio-toolbar"><button type="button" className="secondary" disabled={suite.cases.length>=10} onClick={()=>{let n=1;while(suite.cases.some(c=>c.key===`case_${n}`))n++;setSuite({...suite,cases:[...suite.cases,emptyCase(n)]});}}>+ Пример</button><button className="primary" disabled={busy}>Сохранить набор</button><button type="button" className="secondary" onClick={()=>setSuite(null)}>Отмена</button></div>
  </form>}
  <h3>История сравнений</h3><div className="studio-toolbar">{api.value?.batches.map(b=><button className="secondary" key={b.id} onClick={()=>setBatch(b.id)}>#{b.id} · {b.name}</button>)}</div>{batch&&<EvaluationBatch key={batch} base={base} id={batch} notify={notify} onRun={onRun}/>}
 </div></ToolDialog>;
}
function EvaluationBatch({base,id,notify,onRun}){
 const api=useWork(`${base}/batches/${id}`),[busy,act]=useAction(notify),items=api.value?.items||[];
 useEffect(()=>{if(api.value?.status!=='running')return;const t=setInterval(api.reload,5000);return()=>clearInterval(t);},[api.value?.status,api.reload]);
 const variants=[...new Set(items.map(i=>i.variant))];
 return <section className="workbench-form"><ErrorLine error={api.error}/><div className="studio-toolbar"><h3>Пакет #{id}</h3><button className="secondary" onClick={api.reload}>Обновить</button>{api.value?.status==='running'&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{await workApi(`${base}/batches/${id}/cancel`,{method:'POST',body:'{}'});await api.reload();})}>Остановить пакет</button>}</div>
  <p className="work-muted">Процент отражает только заданные проверки, а не фактическую точность модели. Неизвестный расход токенов показан как «—».</p><div className="evaluation-table"><table><thead><tr><th>Вариант</th><th>Готово</th><th>Проверки</th><th>Время, с</th><th>Токены</th></tr></thead><tbody>{variants.map(v=>{const all=items.filter(i=>i.variant===v),done=all.filter(i=>i.score),passed=done.reduce((s,i)=>s+i.score.passed,0),total=done.reduce((s,i)=>s+i.score.total,0),known=all.every(i=>i.input_tokens!=null&&i.output_tokens!=null);return <tr key={v}><th>{v}</th><td>{done.length}/{all.length}</td><td>{total?`${Math.round(100*passed/total)}%`:'—'}</td><td>{done.length?done.reduce((s,i)=>s+(Date.parse(i.completed_at)-Date.parse(i.started_at))/1000,0).toFixed(1):'—'}</td><td>{known?all.reduce((s,i)=>s+Number(i.input_tokens)+Number(i.output_tokens),0):'—'}</td></tr>;})}</tbody></table></div>
  {items.map(i=><details className="agent-source" key={i.id}><summary>{i.name} · {i.variant} · {i.score?`${i.score.percent}%`:({pending:'В очереди',queueing:'В очереди',running:'Выполняется',failed:'Ошибка',cancelled:'Остановлен'})[i.status]||i.status}</summary><ErrorLine error={i.error}/>{i.score?.checks.map((c,n)=><p key={n}>{c.pass?'✓':'✕'} {c.name}</p>)}{i.result&&<p className="agent-result-text">{i.result.summary}</p>}{i.run_id&&<button className="secondary" onClick={()=>onRun(i.run_id)}>Открыть запуск</button>}</details>)}
 </section>;
}

export function AgentIdentities({data,projectId,options,notify,onClose,onChanged}){
 const api=useWork('agents/identities'),[draft,setDraft]=useState(null),[busy,act]=useAction(notify),[search,setSearch]=useState('');
 const fresh=()=>({name:'Агент команды',owner_id:data.user.id,enabled:true,monthly_tokens:1000000,policy:{projects:[{id:projectId,permissions:['project.browse','agent.view','agent.run']}],workspace_permissions:[],profile_ids:options.profiles[0]?[options.profiles[0].id]:[],actions:[],source_kinds:['task'],spaces:[],chat_ids:[],conference_ids:[]}});
 const policy=draft?.policy,setPolicy=p=>setDraft({...draft,policy:{...policy,...p}});
 const checks=(items,value,onChange)=><div className="agent-inline-checks">{items.map(i=><label key={i.id}><input type="checkbox" checked={value.includes(i.id)} onChange={e=>onChange(toggle(value,i.id,e.target.checked))}/>{i.name}</label>)}</div>;
 return <ToolDialog title="Учётные записи агентов" subtitle="Собственные права, модели, владелец и бюджет. Вход в систему и персональные API-токены отключены." onClose={()=>!busy&&onClose()}><ErrorLine error={api.error}/>
  {!draft?<><button className="primary" onClick={()=>setDraft(fresh())}>+ Учётная запись</button>{api.value?.identities.map(i=><article className="agent-source" key={i.id}><h3>{i.name}</h3><p>{i.owner_name} · {i.enabled?'Активна':'Отключена'} · {Number(i.charged_tokens).toLocaleString('ru-RU')} / {Number(i.monthly_tokens).toLocaleString('ru-RU')} токенов за месяц UTC</p><div className="studio-toolbar"><button className="secondary" onClick={()=>setDraft({id:i.id,name:i.name,owner_id:i.owner_id,enabled:i.enabled,monthly_tokens:Number(i.monthly_tokens),revision:i.revision,policy:structuredClone(i.policy)})}>Изменить права</button>{i.enabled&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{await workApi(`agents/identities/${i.id}`,{method:'PATCH',body:JSON.stringify({enabled:false,revision:i.revision})});await api.reload();await onChanged();notify('Учётная запись отключена; активные запуски отменены');})}>Экстренная остановка</button>}</div></article>)}</>:<form className="workbench-form" onSubmit={e=>{e.preventDefault();act(async()=>{const {id,...d}=draft;await workApi(`agents/identities${id?'/'+id:''}`,{method:id?'PUT':'POST',body:JSON.stringify(d)});setDraft(null);await api.reload();await onChanged();notify('Права учётной записи сохранены');});}}>
   <div className="studio-grid"><Field label="Название"><input required minLength={2} maxLength={150} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Владелец"><select value={draft.owner_id} onChange={e=>setDraft({...draft,owner_id:Number(e.target.value)})}>{data.users.filter(u=>!u.is_service&&!u.email?.endsWith('@agents.invalid')).map(u=><option key={u.id} value={u.id}>{u.display_name}</option>)}</select></Field><Field label="Бюджет токенов в месяц UTC"><input type="number" min={1000} max={1000000000} value={draft.monthly_tokens} onChange={e=>setDraft({...draft,monthly_tokens:Number(e.target.value)})}/></Field><label className="connector-check"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Активна</label></div>
   <fieldset className="agent-source"><legend>Проекты и права</legend>{data.projects.filter(p=>data.permissions.projects[p.id]?.['project.access.manage']).map(p=>{const grant=policy.projects.find(g=>g.id===p.id);return <div className="identity-project" key={p.id}><label className="connector-check"><input type="checkbox" checked={Boolean(grant)} onChange={e=>setPolicy({projects:e.target.checked?[...policy.projects,{id:p.id,permissions:['project.browse','agent.view','agent.run']}]:policy.projects.filter(g=>g.id!==p.id)})}/>{p.name}</label>{grant&&checks((api.value?.project_permissions||[]).map(key=>({id:key,name:key})),grant.permissions,value=>setPolicy({projects:policy.projects.map(g=>g.id===p.id?{...g,permissions:value}:g)}))}</div>;})}</fieldset>
   <fieldset className="agent-source"><legend>Модели</legend>{checks(options.profiles.map(p=>({id:p.id,name:`${p.name} · ${p.model}`})),policy.profile_ids,value=>setPolicy({profile_ids:value}))}</fieldset>
   <fieldset className="agent-source"><legend>Источники и действия</legend>{checks(Object.entries(AGENT_SOURCE_LABELS).map(([id,name])=>({id,name})),policy.source_kinds,value=>setPolicy({source_kinds:value}))}{checks(AGENT_ACTION_CATALOG.map(a=>({id:a.key,name:a.name})),policy.actions,value=>setPolicy({actions:value}))}{checks([{id:'knowledge.view',name:'Чтение базы знаний'},{id:'ai.search',name:'Поиск с ИИ'}],policy.workspace_permissions,value=>setPolicy({workspace_permissions:value}))}</fieldset>
   <fieldset className="agent-source"><legend>Пространства знаний</legend><input type="search" aria-label="Поиск пространства" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Найти пространство"/>{options.spaces.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())).map(s=><Field key={s.id} label={s.name}><select value={policy.spaces.find(v=>v.id===s.id)?.level||''} onChange={e=>setPolicy({spaces:[...policy.spaces.filter(v=>v.id!==s.id),...(e.target.value?[{id:s.id,level:e.target.value}]:[])]})}><option value="">Нет доступа</option><option value="view">Чтение</option><option value="edit">Редактирование</option></select></Field>)}</fieldset>
   <fieldset className="agent-source"><legend>Чаты и встречи</legend>{checks(options.channels.map(c=>({id:c.id,name:c.title})),policy.chat_ids,value=>setPolicy({chat_ids:value}))}{checks(options.conferences.map(c=>({id:c.id,name:c.title})),policy.conference_ids,value=>setPolicy({conference_ids:value}))}<p className="work-muted">Выдача доступа требует управления пространством знаний, владения закрытым чатом или управления встречей.</p></fieldset>
   <div className="studio-toolbar"><button className="primary" disabled={busy}>Сохранить права</button><button className="secondary" type="button" disabled={busy} onClick={()=>setDraft(null)}>Отмена</button></div>
  </form>}
 </ToolDialog>;
}
