"use client";
import {useId,useRef,useState} from 'react';
import {AGENT_NODE_LABELS} from '../lib/agent-catalog.js';
// Отображает сценарий с перемещением блоков, связями и масштабом по фактическим границам схемы.
export default function AgentCanvas({flow,onChange,selected,onSelect,steps=[]}){
 const [zoom,setZoom]=useState(.8),[pan,setPan]=useState({x:25,y:20}),[dragged,setDragged]=useState({}),[connection,setConnection]=useState(null),[hint,setHint]=useState('');
 const pointer=useRef(null),canvas=useRef(null),marker=useId().replace(/:/g,'');
 const nodes=flow.nodes||[],readOnly=!onChange,positions=Object.fromEntries(nodes.map((n,i)=>[n.id,dragged[n.id]||flow.positions?.[n.id]||{x:40+(i%2)*350,y:100+Math.floor(i/2)*185}]));
 const end={x:40,y:100+Math.ceil(nodes.length/2)*185},terminal=[{id:'$start',name:'Источники и параметры',type:'start',point:{x:40,y:0}},{id:'$end',name:'Итоговый ответ',type:'final',point:end}];
 const edges=[];if(nodes.length)edges.push({from:'$start',to:nodes[0].id,key:'next'});else edges.push({from:'$start',to:'$end',key:'next'});
 for(const [i,n] of nodes.entries())for(const key of n.type==='condition'?['on_true','on_false']:n.type==='stop'?[]:['next'])edges.push({from:n.id,to:n[key]||nodes[i+1]?.id||'$end',key});
 const point=id=>positions[id]||terminal.find(t=>t.id===id)?.point||end;
 const width=Math.max(800,...Object.values(positions).map(p=>p.x+330)),height=Math.max(420,end.y+150,...Object.values(positions).map(p=>p.y+180));
 function connect(id){if(!connection)return;const from=nodes.findIndex(n=>n.id===connection.id),to=nodes.findIndex(n=>n.id===id);if(id!=='$end'&&to<=from){setHint('Связь должна вести к следующему шагу: циклы запрещены');setConnection(null);return;}onChange({...flow,nodes:nodes.map(n=>n.id===connection.id?{...n,[connection.key]:id}:n)});setConnection(null);setHint('Связь сохранена');}
 function start(e,id){if(readOnly||e.button!==0)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);pointer.current={id,x:e.clientX,y:e.clientY,origin:positions[id]};onSelect?.(id);}
 function move(e){const p=pointer.current;if(!p)return;if(p.id==='$pan'){setPan({x:p.origin.x+e.clientX-p.x,y:p.origin.y+e.clientY-p.y});return;}setDragged({[p.id]:{x:Math.max(0,Math.min(6000,Math.round(p.origin.x+(e.clientX-p.x)/zoom))),y:Math.max(70,Math.min(6000,Math.round(p.origin.y+(e.clientY-p.y)/zoom)))}});}
 function endDrag(){const p=pointer.current;if(p&&p.id!=='$pan'&&dragged[p.id])onChange({...flow,positions:{...flow.positions,[p.id]:dragged[p.id]}});pointer.current=null;setDragged({});}
 // Вписывает видимые блоки, не уменьшая короткую схему ради пустого пространства холста.
 function fit(){const points=[...Object.values(positions),...terminal.map(node=>node.point)],left=Math.min(...points.map(p=>p.x)),top=Math.min(...points.map(p=>p.y)),right=Math.max(...points.map(p=>p.x+290)),bottom=Math.max(...points.map(p=>p.y+128)),w=canvas.current?.clientWidth||700,h=canvas.current?.clientHeight||460,next=Math.max(.2,Math.min(1,(w-40)/(right-left),(h-40)/(bottom-top)));setZoom(next);setPan({x:20-left*next,y:20-top*next});}
 return <section className="agent-canvas-shell" aria-label="Схема агента">
  <div className="canvas-toolbar"><strong>{readOnly?'Путь выполнения':'Карта сценария'}</strong><div><button type="button" className="secondary" onClick={()=>setZoom(Math.max(.2,zoom-.1))} aria-label="Уменьшить масштаб">−</button><output aria-label="Масштаб">{Math.round(zoom*100)}%</output><button type="button" className="secondary" onClick={()=>setZoom(Math.min(1.5,zoom+.1))} aria-label="Увеличить масштаб">+</button><button type="button" className="secondary" onClick={fit}>Вписать</button></div></div>
  <div className="agent-canvas" ref={canvas} onPointerDown={e=>{if(e.target!==e.currentTarget||e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);pointer.current={id:'$pan',x:e.clientX,y:e.clientY,origin:pan};}} onPointerMove={move} onPointerUp={endDrag} onPointerCancel={endDrag} onKeyDown={e=>{if(e.key==='Escape'){setConnection(null);setHint('');}}}>
   <div className="canvas-world" style={{width,height,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
    <svg className="canvas-edges" width={width} height={height} aria-hidden="true"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="currentColor"/></marker></defs>{edges.map(e=>{const a=point(e.from),b=point(e.to),step=steps.find(s=>s.node_id===e.from),taken=Boolean(step?.status==='completed'&&(step.node_type!=='condition'||(e.key==='on_true')===step.output?.matched));const x=a.x+(e.key==='on_false'?205:85),y=a.y+(e.from==='$start'?60:128),x2=b.x+145,y2=b.y;return <g key={`${e.from}-${e.key}`} className={taken?'taken':''}><path d={`M${x} ${y} C${x} ${y+45},${x2} ${y2-40},${x2} ${y2}`} markerEnd={`url(#${marker})`}/>{e.key!=='next'&&<text x={x+8} y={y+25}>{e.key==='on_true'?'Да':'Нет'}</text>}</g>;})}</svg>
    {terminal.map(n=><button type="button" className={`canvas-terminal ${connection&&n.id==='$end'?'connectable':''}`} key={n.id} style={{left:n.point.x,top:n.point.y}} onPointerUp={()=>n.id==='$end'&&connect(n.id)} onClick={()=>n.id==='$end'&&connect(n.id)}>{n.name}</button>)}
    {nodes.map((n,i)=>{const state=steps.find(s=>s.node_id===n.id)?.status;return <article key={n.id} className={`canvas-node ${selected===n.id?'selected':''} ${state||''} ${connection?'connectable':''}`} style={{left:positions[n.id].x,top:positions[n.id].y}} onPointerUp={()=>connection&&connection.id!==n.id&&connect(n.id)}>
     <button type="button" className="canvas-node-handle" title={readOnly?'Выбрать шаг':'Перетащите блок. Alt + стрелки перемещают с клавиатуры'} aria-label={`${i+1}. ${n.name}`} onPointerDown={e=>start(e,n.id)} onClick={()=>{if(connection)connect(n.id);else onSelect?.(n.id);}} onKeyDown={e=>{if(!readOnly&&e.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const p=positions[n.id];onChange({...flow,positions:{...flow.positions,[n.id]:{x:Math.max(0,Math.min(6000,p.x+(e.key==='ArrowLeft'?-20:e.key==='ArrowRight'?20:0))),y:Math.max(70,Math.min(6000,p.y+(e.key==='ArrowUp'?-20:e.key==='ArrowDown'?20:0)))}}});}}}><span>{String(i+1).padStart(2,'0')} · {AGENT_NODE_LABELS[n.type]}</span><strong>{n.name}</strong><small>{state==='completed'?'✓ Выполнен':state==='failed'?'Ошибка':state==='running'?'Выполняется':n.id}</small></button>
     {!readOnly&&n.type!=='stop'&&<div className="canvas-ports">{(n.type==='condition'?['on_true','on_false']:['next']).map(key=><button type="button" className={connection?.id===n.id&&connection.key===key?'active':''} key={key} title="Нажмите и выберите следующий блок или перетащите к нему" onPointerDown={e=>{e.stopPropagation();setConnection({id:n.id,key});setHint('Выберите блок назначения или «Итоговый ответ»');}} onClick={e=>{e.stopPropagation();setConnection({id:n.id,key});}}>{key==='next'?'Далее ○':key==='on_true'?'Да ○':'Нет ○'}</button>)}</div>}
    </article>;})}
   </div>
  </div>
  <p className="canvas-hint" role="status">{hint|| (readOnly?'Зелёным отмечены выполненные блоки и пройденные связи.':'Перетаскивайте блоки и свободное поле. Для связи выберите выход блока, затем следующий блок. Esc — отмена.')}</p>
 </section>;
}
