"use client";
import {useState} from 'react';
import {useWork,ErrorLine} from './WorkUI.jsx';
const defaults={enabled:false,monthly_user_tokens:1000000,monthly_workspace_tokens:10000000,max_concurrent:10};
const number=value=>Number(value||0).toLocaleString('ru-RU');
export function AiUsage({workspace=false}){
 const [open,setOpen]=useState(false),report=useWork(open?`ai-usage?scope=${workspace?'workspace':'self'}`:null);
 return <details className="ai-usage" open={open} onToggle={e=>setOpen(e.currentTarget.open)}><summary>{workspace?'Расход ИИ по сотрудникам и моделям':'Мой расход ИИ'}</summary><ErrorLine error={report.error}/>{report.value&&<><p>{report.value.month} · {report.value.note}</p><button type="button" className="secondary" onClick={report.reload}>Обновить</button><div className="work-table-scroll"><table className="work-table"><thead><tr><th>Сотрудник</th><th>Обращений</th><th>Учтено токенов</th><th>Нет точного расхода</th></tr></thead><tbody>{report.value.people.map(p=><tr key={p.user_id}><td>{p.display_name}</td><td>{number(p.calls)}</td><td>{number(p.charged_tokens)}</td><td>{number(Number(p.uncertain_calls)+Number(p.reserved_calls))}</td></tr>)}</tbody></table></div>{!report.value.people.length&&<p>В этом месяце обращений ещё нет.</p>}<div className="ai-usage-models">{report.value.purposes.map(p=><p key={`${p.purpose}-${p.model}`}><strong>{p.model}</strong> · {{search:'Поиск',meeting_actions:'Поручения',project_summary:'Анализ проекта',conference_summary:'Сводка чата',recording_summary:'Изложение записи',connection_test:'Проверка подключения',acceptance:'Критерии приёмки',duplicates:'Поиск дубликатов',contradictions:'Проверка противоречий'}[p.purpose]||p.purpose} · {number(p.charged_tokens)} токенов</p>)}</div></>}</details>;
}
export function AiBudgetSettings({value,onChange}){
 const budget={...defaults,...value};return <section className="ai-budget-settings"><h3>Бюджет текстового ИИ</h3><label className="ai-check"><input type="checkbox" checked={budget.enabled} onChange={e=>onChange({...budget,enabled:e.target.checked})}/>Ограничить месячный расход токенов</label><div className="ai-config-grid">{[['monthly_user_tokens','Токенов на сотрудника в месяц',1000,1000000000000],['monthly_workspace_tokens','Токенов на пространство в месяц',1000,1000000000000],['max_concurrent','Одновременных обращений к модели',1,100]].map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} value={budget[key]} onChange={e=>onChange({...budget,[key]:Number(e.target.value)})}/></label>)}</div><p className="ai-help">Перед каждым обращением резервируются входные данные и максимум ответа. После ответа учитывается usage провайдера. Если расход неизвестен, резерв сохраняется. Месяц считается по UTC; это учёт токенов, а не счёт провайдера.</p><AiUsage workspace/></section>;
}
