"use client";
import {useState} from 'react';
import {workApi,useWork,useAction,Field,Select,Empty,ErrorLine,WorkHeader} from './WorkUI.jsx';
import ToolDialog from './ToolDialog.jsx';
const statusLabels={passed:'Пройден',failed:'Ошибка',broken:'Сломан',skipped:'Пропущен',unknown:'Неизвестно'};
export default function AllureView({data,notify,projectId:fixedProject,onRun}){
 const projects=data.projects.filter(p=>['qa.view','qa.manage','qa.execute'].some(key=>data.permissions.projects[p.id]?.[key]));
 const [ownProject,setOwnProject]=useState(projects[0]?.id||null),projectId=fixedProject||ownProject,rights=data.permissions.projects[projectId]||{};
 const api=useWork(projectId?`allure?project_id=${projectId}`:null),[busy,act]=useAction(notify),[draft,setDraft]=useState(null),[upload,setUpload]=useState(null),[details,setDetails]=useState(null);
 if(!projects.length)return <Empty>Нет проектов с доступом к тестированию.</Empty>;
 return <section className="allure-view"><WorkHeader title="Allure" text="Результаты автотестов из CI в прогонах проекта.">{rights['qa.manage']&&<button className="primary" onClick={()=>setDraft({project_id:projectId,name:'Allure',report_base_url:'',key_strategy:'historyId',create_missing:false,enabled:true})}>+ Подключение</button>}</WorkHeader>
 {!fixedProject&&<Field label="Проект"><Select items={projects} value={projectId} onChange={id=>{setOwnProject(id);setDraft(null);setUpload(null);setDetails(null);}}/></Field>}<ErrorLine error={api.error}/>
 <div className="connector-connections">{api.value?.connections.map(c=><article className="connector-connection" key={c.id}><div className="work-header"><div><span className="overline">АВТОТЕСТЫ</span><h3>{c.name}</h3><p>{c.enabled?'Включено':'Пауза'} · ключ: {c.key_strategy} · подключение #{c.id}</p></div><div className="connector-actions">{rights['qa.execute']&&<button className="primary" disabled={!c.enabled} onClick={()=>setUpload(c)}>Загрузить результаты</button>}{rights['qa.manage']&&<button className="secondary" onClick={()=>setDraft(c)}>Настроить</button>}</div></div><details><summary>Подключение к CI</summary><p>Передайте токен пользователя с API scopes quality:write и правом qa.execute в проекте. Создание новых кейсов требует qa.manage.</p><pre className="integration-code">{`KONTUR_URL=${typeof window==='undefined'?'https://kontur.example':window.location.origin}\nKONTUR_ALLURE_CONNECTION_ID=${c.id}\nKONTUR_ALLURE_LAUNCH_ID=<уникальный номер сборки>\nKONTUR_ALLURE_REPORT_URL=<ссылка на отчёт>\n# KONTUR_TOKEN храните в секретах CI\nnode scripts/import-allure.mjs ./allure-results`}</pre><p>Отправляются JSON-результаты. Файлы вложений остаются в отчёте Allure. При повторе того же запуска новый прогон не создаётся.</p></details></article>)}</div>
 {api.loading&&!api.value?<Empty>Загружаем Allure…</Empty>:api.value&&!api.value.connections.length&&<Empty>Создайте подключение и загрузите результаты Allure. Можно настроить автоматическую отправку из CI.</Empty>}
 <h3 className="allure-history-title">История запусков</h3><div className="connector-connections">{api.value?.imports.map(item=><article className="work-card" key={item.id}><div className="work-header"><div><h3>{item.title}</h3><p>{item.connection_name} · {item.external_id}</p></div><span className={`agent-status ${item.summary.failed||item.summary.broken||item.summary.unknown?'failed':'completed'}`}>{item.summary.passed}/{item.summary.total} пройдено</span></div><div className="allure-counters"><span>Ошибок: {item.summary.failed}</span><span>Сломано: {item.summary.broken}</span><span>Нестабильных: {item.summary.flaky}</span><span>Повторов: {item.summary.retries}</span></div><div className="connector-actions"><button className="secondary" onClick={()=>setDetails(item.id)}>Результаты Allure</button>{onRun&&<button className="text-button" onClick={()=>onRun(item.run_id)}>Открыть прогон</button>}{item.report_url&&<a href={item.report_url} target="_blank" rel="noopener noreferrer">Отчёт ↗</a>}</div></article>)}</div>
 {draft&&<ToolDialog title="Подключение Allure" onClose={()=>!busy&&setDraft(null)}><form className="connector-editor" onSubmit={event=>{event.preventDefault();act(async()=>{const payload={project_id:draft.project_id,name:draft.name,report_base_url:draft.report_base_url,key_strategy:draft.key_strategy,create_missing:draft.create_missing,enabled:draft.enabled,...(draft.id?{revision:draft.revision}:{})};await workApi(`allure/connections${draft.id?`/${draft.id}`:''}`,{method:draft.id?'PUT':'POST',body:JSON.stringify(payload)});setDraft(null);await api.reload();notify('Подключение Allure сохранено');});}}><Field label="Название"><input required minLength={2} maxLength={160} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Адрес отчётов (необязательно)"><input type="url" placeholder="https://allure.company.ru/reports/" value={draft.report_base_url} onChange={e=>setDraft({...draft,report_base_url:e.target.value})}/></Field><Field label="Сопоставление с ключом автотеста"><select value={draft.key_strategy} onChange={e=>setDraft({...draft,key_strategy:e.target.value})}><option value="historyId">historyId — тест и набор параметров</option><option value="fullName">fullName — полное имя</option><option value="testCaseId">testCaseId — идентификатор кейса</option></select></Field><p className="work-muted">При выборе fullName или testCaseId к параметризованным тестам добавляется отпечаток параметров. Точные ключи видны в предварительном просмотре.</p><label className="connector-check"><input type="checkbox" checked={draft.create_missing} onChange={e=>setDraft({...draft,create_missing:e.target.checked})}/>Создавать отсутствующие тест-кейсы (импортёру нужно qa.manage)</label><label className="connector-check"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Подключение включено</label><button className="primary" disabled={busy}>Сохранить</button></form></ToolDialog>}
 {upload&&<AllureUpload connection={upload} notify={notify} onClose={()=>setUpload(null)} onImported={async id=>{setUpload(null);await api.reload();setDetails(id);}}/>}
 {details&&<AllureDetails id={details} rights={rights} notify={notify} onClose={()=>setDetails(null)}/>}
 </section>;
}
function AllureUpload({connection,notify,onClose,onImported}){
 const [value,setValue]=useState({external_id:crypto.randomUUID(),title:'Автотесты Allure',report_url:'',results:[]}),[preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,act]=useAction(notify);
 const change=patch=>{setValue({...value,...patch});setPreview(null);};
 async function select(files){setError('');setPreview(null);try{const chosen=[...files];if(!chosen.length||chosen.length>200||chosen.some(f=>!f.name.endsWith('-result.json')))throw new Error('Выберите от 1 до 200 файлов *-result.json');if(chosen.reduce((n,f)=>n+f.size,0)>2_800_000)throw new Error('Размер пакета — до 2,8 МБ');const results=await Promise.all(chosen.map(async f=>JSON.parse(await f.text())));setValue(v=>({...v,results}));}catch(e){setValue(v=>({...v,results:[]}));setError(e.message);}}
 return <ToolDialog title={`Импорт · ${connection.name}`} onClose={()=>!busy&&onClose()}><fieldset disabled={busy} className="connector-editor agent-controls"><Field label="Идентификатор запуска (сохраняйте при повторной отправке)"><input maxLength={160} value={value.external_id} onChange={e=>change({external_id:e.target.value})}/></Field><Field label="Название прогона"><input maxLength={200} value={value.title} onChange={e=>change({title:e.target.value})}/></Field><Field label="Ссылка на отчёт"><input type="url" value={value.report_url} placeholder={connection.report_base_url||'Настройте адрес в подключении'} onChange={e=>change({report_url:e.target.value})}/></Field><Field label="Файлы Allure"><input type="file" multiple accept=".json,application/json" disabled={busy} onChange={e=>select(e.target.files)}/></Field><p>{value.results.length} файлов выбрано</p><ErrorLine error={error}/><button className="secondary" disabled={busy||!value.results.length} onClick={()=>act(async()=>setPreview(await workApi(`allure/connections/${connection.id}/preview`,{method:'POST',body:JSON.stringify(value)})))}>Предварительный просмотр</button>{preview&&<><p>Тестов: {preview.summary.total} · ошибок: {preview.summary.failed} · сломано: {preview.summary.broken} · новых кейсов: {preview.will_create}</p>{!preview.can_import&&<ErrorLine error={`Импорт пока недоступен: отсутствующих ключей ${preview.missing.length}, архивных кейсов ${preview.archived.length}. Проверьте ключи и права создания.`}/>}<div className="allure-preview">{preview.results.map(r=><div key={r.key}><strong>{r.name}</strong><code>{r.key}</code><span>{statusLabels[r.status]} · попыток {r.attempts}</span></div>)}</div><button className="primary" disabled={busy||!preview.can_import} onClick={()=>act(async()=>{const result=await workApi(`allure/connections/${connection.id}/import`,{method:'POST',body:JSON.stringify(value)});notify(result.replayed?'Этот запуск уже импортирован':'Результаты Allure импортированы');await onImported(result.id);})}>Импортировать</button></>}</fieldset></ToolDialog>;
}
function AllureDetails({id,rights,notify,onClose}){
 const api=useWork(`allure/imports/${id}`),[busy,act]=useAction(notify),[onlyFailed,setOnlyFailed]=useState(false);
 return <ToolDialog title="Результаты Allure" onClose={onClose}><ErrorLine error={api.error}/>{api.value&&<><div className="connector-actions"><label className="connector-check"><input type="checkbox" checked={onlyFailed} onChange={e=>setOnlyFailed(e.target.checked)}/>Только проблемы</label>{api.value.report_url&&<a href={api.value.report_url} target="_blank" rel="noopener noreferrer">Полный отчёт ↗</a>}</div>{api.value.results.filter(r=>!onlyFailed||['failed','broken','unknown'].includes(r.status)||r.flaky).map(r=><article className="work-card" key={r.key}><div className="work-header"><div><h3>{r.name}</h3><p>{statusLabels[r.status]}{r.flaky?' · Нестабильный':''} · попыток {r.attempts}{r.duration_ms!=null?` · ${r.duration_ms} мс`:''}</p></div></div>{r.message&&<p>{r.message}</p>}<details><summary>Диагностика и шаги</summary><code>{r.key}</code>{r.trace&&<pre className="allure-trace">{r.trace}</pre>}{r.steps.map((step,i)=><p key={i}>{i+1}. {step.name} · {statusLabels[step.status]}{step.message&&` · ${step.message}`}</p>)}<p>Вложений в Allure: {r.attachment_count}</p></details><div className="connector-actions">{r.defect_task_id?<a href={`/?task=${r.defect_task_id}`}>Открыть дефект #{r.defect_task_id}</a>:rights['qa.execute']&&rights['task.create']&&['failed','broken','unknown'].includes(r.status)&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{const result=await workApi(`allure/imports/${id}/defect`,{method:'POST',body:JSON.stringify({case_id:r.case_id})});notify(`Создан дефект #${result.task_id}`);await api.reload();})}>Создать дефект</button>}</div></article>)}</>}</ToolDialog>;
}
