"use client";
import {useEffect,useRef,useState} from 'react';
import {Track} from 'livekit-client';
import {workApi} from './WorkUI.jsx';
const asBase64=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Не удалось подготовить аудио'));reader.readAsDataURL(blob);});
export default function ConferenceCaptions({conference,roomRef,mic,canPublish,readOnly,breakoutId,notify}){
 const [state,setState]=useState(null),[items,setItems]=useState([]),[consent,setConsent]=useState(false),[open,setOpen]=useState(false),[error,setError]=useState(''),[capturing,setCapturing]=useState(false),[saving,setSaving]=useState(false),cursor=useRef(null),listRef=useRef(null),noticeRef=useRef(notify);
 noticeRef.current=notify;
 const base=`conference-captions/${conference.id}`,query=new URLSearchParams({join_code:conference.join_code||''}).toString();
 useEffect(()=>{
  let active=true,busy=false;const controller=new AbortController();cursor.current=null;setItems([]);setState(null);setConsent(false);
  async function poll(){if(busy||!active)return;busy=true;try{const result=await workApi(`${base}?${query}${cursor.current===null?'':`&after=${cursor.current}`}`,{signal:controller.signal});if(!active)return;setState(result);setError('');if(result.items.length){cursor.current=Math.max(cursor.current||0,...result.items.map(i=>Number(i.sequence_number)));setItems(old=>[...new Map([...old,...result.items].map(i=>[i.id,i])).values()].slice(-300));}if(!result.enabled||!result.service_enabled||!result.can_caption)setConsent(false);}catch(e){if(!active)return;setError(e.message);setConsent(false);}finally{busy=false;}}
  poll();const timer=setInterval(poll,5000);return()=>{active=false;clearInterval(timer);controller.abort();};
 },[base,query]);
 useEffect(()=>{if(!mic||!canPublish||readOnly||breakoutId)setConsent(false);},[mic,canPublish,readOnly,breakoutId]);
 useEffect(()=>{
  if(!consent||!mic||!canPublish||readOnly||breakoutId||!state?.enabled||!state?.service_enabled)return;
  const source=roomRef.current?.localParticipant.getTrackPublication(Track.Source.Microphone)?.track?.mediaStreamTrack;
  if(!source||source.readyState!=='live'||!source.enabled){setConsent(false);noticeRef.current('Сначала включите микрофон встречи','error');return;}
  if(!window.MediaRecorder){setConsent(false);noticeRef.current('Браузер не поддерживает запись микрофона','error');return;}
  const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(m=>MediaRecorder.isTypeSupported(m));
  if(!mime){setConsent(false);noticeRef.current('Браузер не поддерживает подходящий формат аудио','error');return;}
  const clone=source.clone(),stream=new MediaStream([clone]),controller=new AbortController();let active=true,recorder,timer,pending=false;const queue=[];
  const stop=()=>{active=false;clearTimeout(timer);if(recorder?.state==='recording')recorder.stop();clone.stop();queue.length=0;controller.abort();};
  const fail=message=>{if(!active)return;stop();setConsent(false);setCapturing(false);noticeRef.current(message,'error');};
  async function send(){if(pending||!active)return;pending=true;try{while(active&&queue.length){const blob=queue.shift(),audio_base64=await asBase64(blob);if(!active)return;await workApi(`${base}/chunks?${query}`,{method:'POST',signal:controller.signal,body:JSON.stringify({client_id:crypto.randomUUID(),mime_type:blob.type,audio_base64})});}}catch(e){if(active)fail(e.message);}finally{pending=false;}}
  function record(){if(!active)return;try{const parts=[];recorder=new MediaRecorder(stream,{mimeType:mime,audioBitsPerSecond:48000});recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};recorder.onerror=()=>fail('Запись субтитров прервана браузером');recorder.onstop=()=>{if(!active)return;if(!source.enabled||source.readyState!=='live'){fail('Микрофон выключен. Субтитры остановлены');return;}const blob=new Blob(parts,{type:mime});if(blob.size>1000000){fail('Слишком большой фрагмент. Возобновите субтитры');return;}if(queue.length>=2){fail('Распознавание не успевает за речью. Субтитры остановлены; попробуйте позже');return;}if(blob.size){queue.push(blob);send();}record();};recorder.start();timer=setTimeout(()=>{if(active&&recorder.state==='recording')recorder.stop();},8000);}catch{fail('Не удалось запустить субтитры микрофона');}}
  const hidden=()=>{if(document.hidden)fail('Субтитры остановлены при скрытии приложения. Включите их после возвращения');};const ended=()=>fail('Микрофон отключён. Субтитры остановлены');document.addEventListener('visibilitychange',hidden);source.addEventListener('ended',ended);
  setCapturing(true);record();return()=>{stop();setCapturing(false);document.removeEventListener('visibilitychange',hidden);source.removeEventListener('ended',ended);};
 },[consent,mic,canPublish,readOnly,breakoutId,state?.enabled,state?.service_enabled,roomRef,base,query]);
 useEffect(()=>{if(listRef.current)listRef.current.scrollTop=listRef.current.scrollHeight;},[items,open]);
 async function changeEnabled(value){setSaving(true);try{await workApi(`${base}?${query}`,{method:'PATCH',body:JSON.stringify({enabled:value})});setState(old=>({...old,enabled:value}));if(!value)setConsent(false);}catch(e){noticeRef.current(e.message,'error');}finally{setSaving(false);}}
 return <section className={`conference-captions ${capturing?'is-capturing':''}`} aria-label="Субтитры встречи"><div className="caption-heading"><button aria-expanded={open} className="caption-toggle" onClick={()=>setOpen(!open)}>CC · Субтитры {capturing?'· мой микрофон распознаётся':''}<span>{open?'⌃':'⌄'}</span></button>{state?.can_moderate&&!readOnly&&<label><input type="checkbox" checked={state.enabled} disabled={saving||!state.service_enabled} onChange={e=>changeEnabled(e.target.checked)}/>Разрешить во встрече</label>}</div>{open&&<div className="caption-content">{error&&<p role="alert">{error}</p>}{!state?.service_enabled&&<p>Администратор должен включить сервис субтитров в настройках ИИ.</p>}{state?.service_enabled&&!state.enabled&&<p>Организатор ещё не разрешил субтитры.</p>}{breakoutId?<p>Субтитры работают только в основной комнате. Для распознавания после возвращения включите их снова.</p>:state?.enabled&&state.service_enabled&&!readOnly&&<><label className="caption-consent"><input type="checkbox" checked={consent} disabled={!state.can_caption||!mic||!canPublish} onChange={e=>setConsent(e.target.checked)}/>Распознавать мой микрофон и сохранять текст для участников</label><p>Ваше аудио фрагментами передаётся настроенному сервису распознавания. Аудиофайлы субтитров приложение не сохраняет. Текст виден участникам; задержка зависит от сервиса. {!state.can_caption?'Нужно право «Субтитры собственного микрофона».':!mic?'Сначала включите микрофон.':''}</p></>}<div className="caption-lines" ref={listRef} role="log" aria-live="polite" aria-relevant="additions">{items.length?items.map(i=><p key={i.id}><strong>{i.display_name}</strong><time>{new Date(String(i.created_at).replace(' ','T').replace(/Z?$/,'Z')).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</time><span>{i.text}</span></p>):<p>Сохранённых субтитров пока нет.</p>}</div><small>Показаны последние {items.length} фрагментов. Автоматическое распознавание может ошибаться.</small></div>}</section>;
}
