"use client";
import {useEffect,useState} from 'react';
import ToolDialog from './ToolDialog.jsx';
import {workApi,useWork,useAction,Field,ErrorLine,Empty} from './WorkUI.jsx';
const route=(conference,suffix)=>`conference-tools/${conference.id}/${suffix}?${new URLSearchParams({join_code:conference.join_code||''})}`;
function useLive(path){const result=useWork(path);useEffect(()=>{let busy=false,active=true;const timer=setInterval(async()=>{if(!active||busy||document.hidden)return;busy=true;try{await result.reload();}finally{busy=false;}},10000);return()=>{active=false;clearInterval(timer);};},[result.reload]);return result;}
function Polls({conference,notify,readOnly}){
 const report=useLive(route(conference,'polls')),[draft,setDraft]=useState(null),[busy,act]=useAction(notify);
 return <><ErrorLine error={report.error}/>{report.value?.can_moderate&&!readOnly&&<button className="primary" onClick={()=>setDraft({question:'',options:['Да','Нет'],results_visible:true})}>+ Опрос</button>}{report.value?.polls.map(p=><article className="conference-poll" key={p.id}><h3>{p.question}</h3><small>{p.closed?'Опрос закрыт':'Можно изменить свой ответ'}</small><div>{p.options.map((option,i)=>{const count=p.counts?.find(c=>c.option_index===i)?.count||0,total=p.counts?.reduce((s,c)=>s+c.count,0)||0;return <button key={i} className={p.my_vote===i?'selected':''} disabled={busy||readOnly||Boolean(p.closed)} onClick={()=>act(async()=>{await workApi(route(conference,`polls/${p.id}/vote`),{method:'POST',body:JSON.stringify({option_index:i})});await report.reload();})}><span>{p.my_vote===i?'✓ ':''}{option}</span>{p.counts&&<b>{count} · {total?Math.round(count/total*100):0}%</b>}</button>;})}</div>{p.counts===null&&<p>Результаты появятся после закрытия опроса.</p>}{report.value.can_moderate&&!readOnly&&<button className="text-button" disabled={busy} onClick={()=>act(async()=>{await workApi(route(conference,`polls/${p.id}`),{method:'PATCH',body:JSON.stringify({closed:!p.closed,revision:p.revision})});await report.reload();})}>{p.closed?'Открыть снова':'Завершить опрос'}</button>}</article>)}{report.value?.polls.length===0&&<Empty>Опросов пока нет.</Empty>}{draft&&<ToolDialog title="Новый опрос" onClose={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();act(async()=>{await workApi(route(conference,'polls'),{method:'POST',body:JSON.stringify(draft)});setDraft(null);await report.reload();});}}><Field label="Вопрос"><input required minLength={2} maxLength={500} value={draft.question} onChange={e=>setDraft({...draft,question:e.target.value})}/></Field>{draft.options.map((option,i)=><Field key={i} label={`Вариант ${i+1}`}><div className="work-actions"><input required maxLength={180} value={option} onChange={e=>setDraft({...draft,options:draft.options.map((v,j)=>j===i?e.target.value:v)})}/><button className="secondary" type="button" disabled={draft.options.length<=2} onClick={()=>setDraft({...draft,options:draft.options.filter((_,j)=>i!==j)})}>×</button></div></Field>)}<button type="button" className="secondary" disabled={draft.options.length>=10} onClick={()=>setDraft({...draft,options:[...draft.options,'']})}>+ Вариант</button><label className="work-checkbox"><input type="checkbox" checked={draft.results_visible} onChange={e=>setDraft({...draft,results_visible:e.target.checked})}/>Показывать результаты до закрытия</label><button className="primary" disabled={busy}>Опубликовать опрос</button></form></ToolDialog>}</>;
}
function Lobby({conference,notify,readOnly}){
 const report=useLive(route(conference,'lobby')),[busy,act]=useAction(notify);
 return <><ErrorLine error={report.error}/>{report.value&&<><label className="work-checkbox"><input type="checkbox" checked={report.value.waiting_room} disabled={busy||readOnly} onChange={e=>act(async()=>{await workApi(route(conference,'settings'),{method:'PATCH',body:JSON.stringify({waiting_room:e.target.checked})});await report.reload();})}/>Зал ожидания для новых подключений</label><p>Организаторы входят сразу. Уже выданные медиатокены продолжают действовать.</p>{report.value.people.map(p=><div className="conference-admission" key={p.user_id}><strong>{p.display_name}</strong><div className="work-actions">{[['admitted','Впустить'],['denied','Отклонить']].map(([status,label])=><button key={status} className="secondary" disabled={busy||readOnly} onClick={()=>act(async()=>{await workApi(route(conference,'lobby'),{method:'PATCH',body:JSON.stringify({user_id:p.user_id,status})});await report.reload();})}>{label}</button>)}</div></div>)}{!report.value.people.length&&<Empty>Никто не ожидает допуска.</Empty>}</>}</>;
}
function Breakouts({conference,notify,readOnly,activeRoom,onSwitch}){
 const report=useLive(route(conference,'breakouts')),[draft,setDraft]=useState(null),[query,setQuery]=useState(''),[busy,act]=useAction(notify),candidates=useWork(draft?route(conference,'candidates'):null);
 return <><ErrorLine error={report.error}/>{activeRoom&&<button className="primary" onClick={()=>onSwitch(null)}>Вернуться в общую комнату</button>}{report.value?.can_moderate&&!readOnly&&<button className="secondary" onClick={()=>{setQuery('');setDraft({name:'',member_ids:[]});}}>+ Комната обсуждения</button>}<p>Аудио, видео и демонстрация экрана отделены по комнатам. Чат, вопросы и опросы остаются общими. Запись основной встречи не включает комнаты.</p>{report.value?.rooms.map(room=><div className="conference-breakout" key={room.id}><h3>{room.name}</h3><small>{room.members} назначенных участников · {room.closed?'закрыта':activeRoom===room.id?'вы здесь':'открыта'}</small><div className="work-actions">{!room.closed&&!readOnly&&<button className="secondary" disabled={busy||activeRoom===room.id} onClick={()=>onSwitch(room.id)}>Перейти</button>}{report.value.can_moderate&&!readOnly&&<button className="text-button" disabled={busy} onClick={()=>act(async()=>{const result=await workApi(route(conference,`breakouts/${room.id}`),{method:'PATCH',body:JSON.stringify({closed:true})});if(activeRoom===room.id)onSwitch(null);await report.reload();notify(result.media_disconnected?'Комната закрыта':'Новый вход закрыт, но медиасервер не подтвердил отключение участников',result.media_disconnected?'success':'error');})}>{room.closed?'Повторить отключение':'Закрыть комнату'}</button>}</div></div>)}{report.value?.rooms.length===0&&<Empty>Вам пока не назначена комната обсуждения.</Empty>}{draft&&<ToolDialog title="Комната обсуждения" onClose={()=>setDraft(null)}><form onSubmit={e=>{e.preventDefault();act(async()=>{await workApi(route(conference,'breakouts'),{method:'POST',body:JSON.stringify(draft)});setDraft(null);await report.reload();});}}><Field label="Название"><input required minLength={2} maxLength={180} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Поиск участников"><input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></Field><ErrorLine error={candidates.error}/><p>Выбрано {draft.member_ids.length} участников. Организатор может входить в любую комнату.</p><div className="breakout-candidates">{candidates.value?.filter(p=>p.display_name.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))).slice(0,100).map(p=><label key={p.id}><input type="checkbox" checked={draft.member_ids.includes(p.id)} onChange={e=>setDraft({...draft,member_ids:e.target.checked?[...draft.member_ids,p.id]:draft.member_ids.filter(id=>id!==p.id)})}/>{p.display_name}</label>)}</div><small>Первые 100 совпадений. Уточните поиск, чтобы выбрать остальных.</small><button className="primary" disabled={busy||!draft.member_ids.length}>Создать комнату</button></form></ToolDialog>}</>;
}
function Attendance({conference}){const report=useWork(route(conference,'attendance'));return <><ErrorLine error={report.error}/><button className="secondary" onClick={report.reload}>Обновить журнал</button>{report.value&&<><p>{report.value.note}</p>{report.value.people.map(p=><div className="conference-admission" key={p.user_id}><strong>{p.display_name}</strong><span>{p.minutes} мин · {p.sessions} подключений{p.open_sessions?" · есть незавершённые интервалы":""}</span></div>)}{!report.value.people.length&&<Empty>Событий медиасервера пока нет.</Empty>}</>}</>;}
export default function ConferenceTools({conference,canModerate,notify,readOnly,activeRoom,onSwitch}){
 const [tab,setTab]=useState('polls');return <div className="conference-tools-panel"><nav className="conference-tool-tabs" aria-label="Инструменты встречи">{[['polls','Опросы'],['rooms','Комнаты'],...(canModerate?[['lobby','Зал ожидания'],['attendance','Посещаемость']]:[])].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>{tab==='polls'&&<Polls conference={conference} notify={notify} readOnly={readOnly}/>} {tab==='rooms'&&<Breakouts conference={conference} notify={notify} readOnly={readOnly} activeRoom={activeRoom} onSwitch={onSwitch}/>} {tab==='lobby'&&canModerate&&<Lobby conference={conference} notify={notify} readOnly={readOnly}/>} {tab==='attendance'&&canModerate&&<Attendance conference={conference}/>}</div>;
}
