"use client";
import {useEffect,useState} from 'react';
import {workApi,useWork,useAction,Field,Select,ErrorLine,Empty,WorkHeader} from './WorkUI.jsx';
import {TaskFilters} from './TaskTable.jsx';
import ToolDialog from './ToolDialog.jsx';
import {filterTasks} from '../lib/view-filters.js';
import {METRICS} from '../lib/analytics-math.js';
export function DashboardFilters({data,value={},onChange}){
 return <div className="dashboard-global-filters"><details><summary>Фильтры дашборда <small>{Object.values(value).filter(Boolean).length?'· настроены':'· все задачи'}</small></summary><TaskFilters data={data} value={value} onChange={onChange}/><div className="dashboard-period-fields"><Field label="Период с"><input type="date" value={value.from||''} onChange={e=>onChange({...value,from:e.target.value||undefined})}/></Field><Field label="По"><input type="date" value={value.to||''} onChange={e=>onChange({...value,to:e.target.value||undefined})}/></Field><Field label="Часовой пояс"><input list="dashboard-zones" value={value.timezone||''} placeholder={Intl.DateTimeFormat().resolvedOptions().timeZone} onChange={e=>onChange({...value,timezone:e.target.value||undefined})}/><datalist id="dashboard-zones">{['UTC','Europe/Moscow','Asia/Yekaterinburg','Asia/Novosibirsk','Asia/Vladivostok'].map(v=><option key={v} value={v}/>)}</datalist></Field><button className="secondary" onClick={()=>onChange({})}>Сбросить</button></div><p>Период применяется к созданным и завершённым задачам. По умолчанию — последние 30 дней; остальные виджеты показывают текущее состояние.</p></details></div>;
}
export const filteredDashboardData=(data,filter)=>({...data,tasks:filterTasks(data.tasks,filter),projects:filter.projectId?data.projects.filter(p=>p.id===filter.projectId):data.projects});
export function AnalyticsWidget({widget,filter={}}){
 const [value,setValue]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),query=JSON.stringify({filter,expression:widget.config?.expression||'total',widget_project_id:widget.config?.projectId||null});
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');setValue(null);const timer=setTimeout(()=>{workApi('analytics/metrics',{method:'POST',body:query,signal:controller.signal}).then(v=>{if(!controller.signal.aborted)setValue(v);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},300);return()=>{clearTimeout(timer);controller.abort();};},[query]);
 return <section className="surface dashboard-widget analytics-widget"><div className="surface-head"><div><span className="overline">{widget.widget_type==='formula'?'ФОРМУЛА':'ДИНАМИКА'}</span><h2>{widget.title}</h2></div></div><ErrorLine error={error}/>{loading&&<p className="muted" role="status">Рассчитываем…</p>}{value&&(widget.widget_type==='formula'?<><strong className="formula-value">{value.value==null?'—':value.value.toLocaleString('ru-RU',{maximumFractionDigits:2})}<small>{String(widget.config?.unit||'').slice(0,30)}</small></strong><code>{widget.config?.expression||'total'}</code>{value.value==null&&<p>Значение не определено: проверьте деление на ноль.</p>}</>:<><div className="period-metrics">{['created','completed'].map(key=>{const delta=value.metrics[key]-value.previous[key];return <div key={key}><span>{METRICS[key]}</span><strong>{value.metrics[key]}</strong><small>{delta>0?'+':''}{delta} к прошлому периоду</small></div>;})}</div><p>{value.period.from} — {value.period.to} · {value.period.timezone}</p></>)}{value&&<small className="analytics-note">{value.note}</small>}</section>;
}
export function FormulaEditor({config,onChange}){return <div className="formula-editor"><label>Формула<input maxLength={512} value={config.expression||''} placeholder="done / total * 100" onChange={e=>onChange({...config,expression:e.target.value})}/></label><label>Единица измерения<input maxLength={30} value={config.unit||''} placeholder="%" onChange={e=>onChange({...config,unit:e.target.value})}/></label><details><summary>Доступные показатели</summary>{Object.entries(METRICS).map(([key,label])=><div key={key}><code>{key}</code> — {label}</div>)}<p>Операции + − * / и скобки. Деление на ноль показывает «—».</p></details></div>;}
export function DashboardSharing({draft,setDraft,canShare}){
 const groups=useWork(canShare?'analytics/groups':null);
 if(!canShare)return null;
 return <div className="dashboard-sharing"><Field label="Доступ"><select value={draft.is_shared?(draft.share_group_id||'workspace'):'private'} onChange={e=>setDraft({...draft,is_shared:e.target.value!=='private',share_group_id:!['private','workspace'].includes(e.target.value)?Number(e.target.value):null})}><option value="private">Только я</option><option value="workspace">Всё пространство</option>{(groups.value||[]).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><label><input type="checkbox" checked={Boolean(draft.is_template)} onChange={e=>setDraft({...draft,is_template:e.target.checked})}/>Предлагать как шаблон</label><ErrorLine error={groups.error}/></div>;
}
export function DashboardSubscription({dashboard,notify}){
 const [open,setOpen]=useState(false);
 return <><button className="secondary" onClick={()=>setOpen(true)}>Почтовый отчёт</button>{open&&<ToolDialog title={`Отчёт: ${dashboard.name}`} subtitle="Доставка на адрес из вашего профиля. Права проверяются перед каждой отправкой." onClose={()=>setOpen(false)}><SubscriptionForm dashboard={dashboard} notify={notify} close={()=>setOpen(false)}/></ToolDialog>}</>;
}
function SubscriptionForm({dashboard,notify,close}){
 const report=useWork(`analytics/subscriptions/${dashboard.id}`),[draft,setDraft]=useState(null),[busy,act]=useAction(notify);
 useEffect(()=>{if(report.value)setDraft({...report.value,enabled:Boolean(report.value.enabled),timezone:report.value.revision?report.value.timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});},[report.value]);
 return <><ErrorLine error={report.error}/>{draft?<form className="work-form" onSubmit={e=>{e.preventDefault();act(async()=>{await workApi(`analytics/subscriptions/${dashboard.id}`,{method:'PUT',body:JSON.stringify(draft)});notify('Расписание отчёта сохранено');close();});}}><label><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Получать отчёт</label><Field label="Частота"><select value={draft.frequency} onChange={e=>setDraft({...draft,frequency:e.target.value})}><option value="daily">Каждый день</option><option value="weekly">Раз в неделю</option></select></Field>{draft.frequency==='weekly'&&<Field label="День недели"><select value={draft.weekday} onChange={e=>setDraft({...draft,weekday:Number(e.target.value)})}>{['Воскресенье','Понедельник','Вторник','Среда','Четверг','Пятница','Суббота'].map((d,i)=><option key={i} value={i}>{d}</option>)}</select></Field>}<Field label="Час доставки"><input type="number" required min={0} max={23} value={draft.delivery_hour} onChange={e=>setDraft({...draft,delivery_hour:Number(e.target.value)})}/></Field><Field label="Часовой пояс"><input required value={draft.timezone} onChange={e=>setDraft({...draft,timezone:e.target.value})}/></Field>{draft.last_sent_at&&<p>Последняя отправка: {draft.last_sent_at} UTC</p>}<ErrorLine error={draft.last_error}/><p>Нужны настроенная почта и запущенный worker. Отчёт содержит основные показатели и формулы сохранённого дашборда.</p><button className="primary" disabled={busy}>Сохранить расписание</button></form>:!report.error&&<p>Загружаем…</p>}</>;
}
export function ForecastView({data}){
 const projects=data.projects.filter(p=>data.permissions.projects[String(p.id)]?.['report.view']),[projectId,setProjectId]=useState(projects[0]?.id||null),report=useWork(projectId?`analytics/forecast?project_id=${projectId}`:null);
 return <div className="surface forecast-panel"><WorkHeader title="Прогноз завершения" text="Оценка сроков по фактической истории выполнения"><Select items={projects} value={projectId} onChange={setProjectId} placeholder="Выберите проект"/></WorkHeader><ErrorLine error={report.error}/>{report.loading&&<p>Считаем прогноз…</p>}{report.value&&<>{report.value.status==='insufficient'?<Empty>{report.value.reason}</Empty>:report.value.status==='complete'?<Empty>Все задачи проекта завершены.</Empty>:<><div className="forecast-dates">{[['p50','50% сценариев'],['p85','85% сценариев'],['p95','95% сценариев']].map(([key,label])=><div key={key}><small>{label}</small><strong>{report.value.dates[key]?new Date(`${report.value.dates[key]}T12:00:00`).toLocaleDateString('ru-RU'):'За горизонтом'}</strong></div>)}</div><p>Осталось {report.value.remaining} задач. В выборке — {report.value.completed} завершений за {report.value.samples} дней.</p></>}<p className="analytics-note">{report.value.assumptions}</p></>}{!projectId&&<Empty>Выберите проект с правом просмотра отчётов.</Empty>}</div>;
}
