"use client";
import {useState,useEffect} from 'react';
import {workApi,useWork,useAction,Field,Select,Empty,ErrorLine,WorkHeader} from './WorkUI.jsx';
import ToolDialog from './ToolDialog.jsx';
const labels={title:'Название',description:'Описание',start:'Начало',end:'Завершение',status:'Состояние',response:'Ответ на приглашение',stage_id:'Этап',assignee_id:'Исполнитель',due_date:'Срок'};
const errors={UNMAPPED_USER:'Сопоставьте исполнителя с пользователем Контур',UNMAPPED_STAGE:'Сопоставьте рабочий и завершённый этапы',REMOTE_MISSING:'Внешний объект удалён. Локальные данные сохранены',REMOTE_CHANGED:'Внешний объект изменился во время синхронизации',LOCAL_CHANGED:'Объект в Контуре изменился во время синхронизации',ETAG_REQUIRED:'CalDAV-сервер не вернул ETag',ORGANIZER_REQUIRED:'Только организатор или управляющий встречей может менять её параметры',MEETING_NOT_SCHEDULED:'Параметры встречи можно менять из календаря только до её начала',ACCESS_REVOKED:'Доступ отозван',SYNC_FAILED:'Не удалось синхронизировать. Проверьте реквизиты, сеть и формат события',CHANGED_DURING_SYNC:'Данные изменились во время обмена; требуется повторная проверка',ADDRESS_BLOCKED:'Адрес запрещён сетевой политикой',TIMEOUT:'Сервис не ответил вовремя'};
export default function ExternalSyncView({data,notify}){
 const api=useWork('sync'),[busy,act]=useAction(notify),[draft,setDraft]=useState(null),[selected,setSelected]=useState(null);
 const features=data.permissions.features,projects=data.projects.filter(p=>data.permissions.projects[p.id]?.['project.admin']);
 function create(kind){setDraft({kind,name:'',enabled:false,revision:0,project_id:kind==='gitlab'?projects[0]?.id||null:null,config:{users:{}},credentials:{url:'',username:'',password:'',token:''},replace:true});}
 return <section className="work-module"><WorkHeader title="Календари и обмен задачами" text="Личные подключения, сопоставления и контроль изменений на обеих сторонах."><button className="secondary" onClick={api.reload}>Обновить</button>{features['calendar.connect']&&<button className="primary" onClick={()=>create('caldav')}>+ Календарь CalDAV</button>}{features['integration.manage']&&<button className="secondary" onClick={()=>create('gitlab')} disabled={!projects.length}>+ Задачи GitLab</button>}</WorkHeader><ErrorLine error={api.error}/><p className="integration-notice">Добавляйте только те встречи и задачи, которые нужно синхронизировать. Начальная привязка различающихся задач требует выбора версии. Внешние объекты при удалении подключения сохраняются.</p>
 {!api.value?.length?<Empty>Подключите свой CalDAV-календарь или проект GitLab.</Empty>:api.value.map(c=><article className="connector-connection" key={c.id}><div className="connector-connection-head"><span className="connector-mark">{c.kind==='caldav'?'CAL':'GL'}</span><div><h3>{c.name}</h3><p>{c.kind==='caldav'?'Календарь встреч':'Двусторонний обмен задачами'} · {c.enabled?'Включено':'Пауза'}</p></div></div>{c.error_code&&<ErrorLine error={errors[c.error_code]||c.error_code}/>}<div className="connector-actions"><button className="primary" onClick={()=>setSelected(c)}>Связи и конфликты</button><button className="secondary" onClick={()=>setDraft({...c,credentials:{},replace:false})}>Настроить</button><button className="secondary" disabled={busy||!c.enabled} onClick={()=>act(async()=>{await workApi(`sync/${c.id}/run`,{method:'POST',body:JSON.stringify({revision:c.revision})});notify('Синхронизация поставлена в очередь');})}>Синхронизировать</button><button className="text-button danger-text" disabled={busy} onClick={()=>{if(confirm(`Удалить подключение «${c.name}»? Объекты с обеих сторон сохранятся.`))act(async()=>{await workApi(`sync/${c.id}`,{method:'DELETE',body:JSON.stringify({revision:c.revision})});await api.reload();});}}>Удалить</button></div></article>)}
 {draft&&<ToolDialog title={draft.kind==='caldav'?'Календарь CalDAV':'Обмен задачами GitLab'} onClose={()=>!busy&&setDraft(null)}><form className="connector-editor" onSubmit={e=>{e.preventDefault();act(async()=>{const body={kind:draft.kind,name:draft.name,enabled:draft.enabled,revision:draft.revision,project_id:draft.project_id,config:draft.config,...(draft.replace?{credentials:draft.kind==='caldav'?{url:draft.credentials.url,username:draft.credentials.username,password:draft.credentials.password}:{url:draft.credentials.url,token:draft.credentials.token}}:{})};await workApi(draft.id?`sync/${draft.id}`:'sync',{method:draft.id?'PUT':'POST',body:JSON.stringify(body)});setDraft(null);await api.reload();notify('Подключение сохранено');});}}><Field label="Название"><input required minLength={2} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field>{draft.kind==='gitlab'&&<><Field label="Проект Контур"><Select disabled={!!draft.id} required items={projects} value={draft.project_id} onChange={id=>setDraft({...draft,project_id:id,config:{...draft.config,open_stage_id:undefined,closed_stage_id:undefined}})}/></Field><Field label="Числовой ID проекта GitLab"><input type="number" min={1} required value={draft.config.remote_project_id||''} onChange={e=>setDraft({...draft,config:{...draft.config,remote_project_id:Number(e.target.value)}})}/></Field>{[['open_stage_id','Открытая задача',false],['closed_stage_id','Закрытая задача',true]].map(([key,label,done])=><Field label={label} key={key}><Select required items={data.workflows.filter(w=>w.id===projects.find(p=>p.id===draft.project_id)?.workflow_id).flatMap(w=>w.stages).filter(s=>Boolean(s.is_done)===done)} value={draft.config[key]} onChange={id=>setDraft({...draft,config:{...draft.config,[key]:id}})}/></Field>)}<UserMap value={draft.config.users||{}} users={data.users} onChange={users=>setDraft({...draft,config:{...draft.config,users}})}/></>}
 {draft.id&&<label className="connector-check"><input type="checkbox" checked={draft.replace} onChange={e=>setDraft({...draft,replace:e.target.checked,credentials:{}})}/>Заменить реквизиты</label>}{draft.replace&&<><Field label={draft.kind==='caldav'?'HTTPS URL коллекции календаря':'HTTPS URL сервера GitLab'}><input required type="url" value={draft.credentials.url||''} onChange={e=>setDraft({...draft,credentials:{...draft.credentials,url:e.target.value}})} placeholder={draft.kind==='caldav'?'https://calendar.example.ru/dav/calendars/user/work/':'https://gitlab.example.ru'}/></Field>{(draft.kind==='caldav'?[['username','Логин','text'],['password','Пароль приложения','password']]:[['token','Токен GitLab с доступом к API проекта','password']]).map(([key,label,type])=><Field label={label} key={key}><input type={type} required autoComplete="new-password" value={draft.credentials[key]||''} onChange={e=>setDraft({...draft,credentials:{...draft.credentials,[key]:e.target.value}})}/></Field>)}</>}
 <label className="connector-check"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Включить фоновую синхронизацию</label><p className="work-muted">Реквизиты зашифрованы и скрыты после сохранения. Используется текущая модель доступа. Из календаря меняются название, описание, время и отмена запланированных встреч; свой ответ участника синхронизируется отдельно.</p><button className="primary" disabled={busy}>Сохранить</button></form></ToolDialog>}
 {selected&&<Bindings data={data} connection={selected} notify={notify} onClose={()=>setSelected(null)}/>}
 </section>;
}
function UserMap({value,onChange,users}){const [remote,setRemote]=useState(''),[local,setLocal]=useState(null);return <fieldset className="connector-event-picker"><legend>Сопоставление исполнителей</legend>{Object.entries(value).map(([id,userId])=><div className="connector-actions" key={id}><span>GitLab #{id} → {users.find(u=>u.id===userId)?.display_name||userId}</span><button type="button" className="secondary" onClick={()=>{const next={...value};delete next[id];onChange(next);}}>Удалить</button></div>)}<div className="work-form-grid"><Field label="ID пользователя GitLab"><input type="number" min={1} value={remote} onChange={e=>setRemote(e.target.value)}/></Field><Field label="Пользователь Контур"><Select items={users} value={local} onChange={setLocal}/></Field></div><button type="button" className="secondary" disabled={!remote||!local} onClick={()=>{onChange({...value,[remote]:local});setRemote('');setLocal(null);}}>Добавить соответствие</button></fieldset>;}
function Bindings({data,connection,notify,onClose}){
 const api=useWork(`sync/${connection.id}/bindings`),meetings=useWork(connection.kind==='caldav'?'sync-meetings':null),[entity,setEntity]=useState(null),[external,setExternal]=useState(''),[conflict,setConflict]=useState(null),[busy,act]=useAction(notify);
 const items=connection.kind==='caldav'?meetings.value||[]:data.tasks.filter(t=>t.project_id===connection.project_id);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')api.reload();},10000);return()=>clearInterval(timer);},[api.reload]);
 return <ToolDialog title={`Синхронизация · ${connection.name}`} onClose={onClose}><ErrorLine error={api.error||meetings.error}/><div className="work-form-grid"><Field label={connection.kind==='caldav'?'Встреча':'Задача Контур'}><Select items={items} value={entity} onChange={setEntity}/></Field>{connection.kind==='gitlab'&&<Field label="Номер задачи GitLab (IID)"><input type="number" min={1} value={external} onChange={e=>setExternal(e.target.value)}/></Field>}</div><button className="primary" disabled={busy||!entity||(connection.kind==='gitlab'&&!external)} onClick={()=>act(async()=>{await workApi(`sync/${connection.id}/bindings`,{method:'POST',body:JSON.stringify({entity_id:entity,...(connection.kind==='gitlab'?{external_key:external}:{})})});await api.reload();setEntity(null);setExternal('');})}>Добавить связь</button><p className="work-muted">Автоматически проверяются до 10 связей за проход. Конфликтующие изменения не перезаписываются.</p>{api.value?.map(b=><article className="work-card" key={b.id}><strong>{b.title}</strong><p>{{pending:'Ожидает первого обмена',synced:'Синхронизировано',conflict:'Изменения требуют выбора',failed:'Ошибка синхронизации'}[b.status]}</p>{b.error_code&&<ErrorLine error={errors[b.error_code]||b.error_code}/>}<div className="connector-actions">{b.conflict&&<button className="primary" onClick={()=>setConflict(b)}>Разобрать конфликт</button>}<button className="text-button danger-text" disabled={busy} onClick={()=>act(async()=>{await workApi(`sync/${connection.id}/bindings/${b.id}`,{method:'DELETE'});await api.reload();})}>Отключить связь</button></div></article>)}{conflict&&<div className="work-card"><h3>Выберите версию: {conflict.title}</h3><div className="work-table-scroll"><table className="work-table"><thead><tr><th>Поле</th><th>Контур</th><th>Внешняя система</th></tr></thead><tbody>{Object.keys(conflict.conflict.local).map(key=><tr key={key}><td>{labels[key]||key}</td><td>{String(conflict.conflict.local[key]??'—')}</td><td>{String(conflict.conflict.remote?.[key]??'—')}</td></tr>)}</tbody></table></div><div className="connector-actions">{[['local','Оставить Контур'],['remote','Принять внешние изменения']].map(([choice,label])=><button className="secondary" key={choice} disabled={busy||(choice==='remote'&&!conflict.conflict.remote)} onClick={()=>act(async()=>{await workApi(`sync/${connection.id}/bindings/${conflict.id}/resolve`,{method:'POST',body:JSON.stringify({revision:conflict.revision,choice,conflict_hash:conflict.conflict_hash})});setConflict(null);await api.reload();notify('Выбор сохранён; изменения применятся после повторной проверки');})}>{label}</button>)}<button className="text-button" onClick={()=>setConflict(null)}>Закрыть сравнение</button></div></div>}</ToolDialog>;
}
