"use client";
import AllureView from './AllureView.jsx';
import ExternalSyncView from "./ExternalSyncView.jsx";
import {useEffect,useState} from 'react';
import {workApi,useWork,useAction,Field,Empty,ErrorLine,Select} from './WorkUI.jsx';
import ToolDialog from './ToolDialog.jsx';
import {DevelopmentTools} from './WorkDataTools.jsx';
import {IntegrationsAdmin} from './AdvancedViews';
import {INTEGRATION_PROVIDERS,INTEGRATION_EVENTS,DELIVERY_STATES,DELIVERY_ERRORS} from '../lib/integration-catalog.js';
const providerFor=key=>INTEGRATION_PROVIDERS.find(p=>p.key===key);
const stamp=value=>value?new Date(String(value).replace(' ','T')+'Z').toLocaleString('ru-RU'):'—';
export default function IntegrationsHub({data,reload,notify}){
 const features=data.permissions.features||{},canView=features['integration.view']||features['integration.manage'];
 const api=useWork(canView?'integrations':null),[busy,act]=useAction(notify);
 const [tab,setTab]=useState('catalog'),[search,setSearch]=useState(''),[projectId,setProjectId]=useState(null),[draft,setDraft]=useState(null),[journal,setJournal]=useState(null),[test,setTest]=useState(null),[gitProvider,setGitProvider]=useState('github');
 const projects=data.projects.filter(p=>p.status==='active'),managed=projects.filter(p=>data.permissions.projects[p.id]?.['project.admin']);
 const canAllure=data.projects.some(p=>['qa.view','qa.manage','qa.execute'].some(k=>data.permissions.projects[p.id]?.[k]));
 const canManage=Boolean(features['integration.manage']),connections=api.value?.connections||[];
 const allowed=item=>canManage&&data.permissions.projects[item.project_id]?.['project.admin'];
 const filtered=connections.filter(c=>(!projectId||Number(c.project_id)===projectId)&&`${c.name} ${providerFor(c.provider)?.name}`.toLowerCase().includes(search.toLowerCase()));
 function create(provider){setDraft({provider,project_id:managed.find(p=>p.id===projectId)?.id||managed[0]?.id||null,name:'',enabled:false,event_types:['task.created','task.updated'],config:{},credentials:{},replace_credentials:true});}
 async function mutate(item,method,patch={}){await workApi(`integrations/${item.id}`,{method,body:JSON.stringify({version_number:item.version_number,...patch})});await api.reload();}
 if(!canView&&canAllure)return <><h1>Интеграции · Allure</h1><AllureView data={data} notify={notify}/>{features['calendar.connect']&&<ExternalSyncView data={data} notify={notify}/>}</>;
 if(!canView&&features['calendar.connect'])return <ExternalSyncView data={data} notify={notify}/>;
 if(!canView)return <Empty>Для открытия раздела требуется право «Просмотр подключений».</Empty>;
 return <section className="integrations-hub"><div className="page-head"><div><span className="overline">КОНТУР / СВЯЗИ МЕЖДУ СЕРВИСАМИ</span><h1>Интеграции</h1><p>События проектов там, где работает ваша команда.</p></div><button className="secondary" disabled={api.loading} onClick={api.reload}>Обновить</button></div>
 <div className="integrations-summary"><div><strong>{connections.length}</strong><span>подключений уведомлений</span></div><div><strong>{connections.filter(c=>c.enabled).length}</strong><span>включено</span></div><div><strong>{new Set(connections.map(c=>c.project_id)).size}</strong><span>проектов подключено</span></div></div>
 <nav className="work-tabs" aria-label="Разделы интеграций">{[['catalog','Каталог'],['connections','Мои подключения'],['git','GitHub / GitLab'],...(canAllure?[['allure','Allure']]:[]),...((features['calendar.connect']||canManage)?[['sync','Календари и синхронизация']]:[]),...(canManage?[['legacy','Ранее созданные webhooks и API']]:[])].map(([key,label])=><button key={key} className={tab===key?'active':''} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}{key==='connections'&&` · ${connections.length}`}</button>)}</nav><ErrorLine error={api.error}/>
 {tab==='catalog'&&<><div className="integration-intro"><h2>Подключите инструменты команды</h2><p>Выберите сервис, проект и события. Доступы назначаются через роли пользователей и групп.</p></div><div className="connector-catalog">{canAllure&&<article className="connector-card"><span className="connector-mark allure" aria-hidden="true">A</span><span className="connector-type">Тестирование</span><h3>Allure Report</h3><p>Результаты автотестов из CI: ошибки, повторы и связанные дефекты.</p><button className="secondary" onClick={()=>setTab('allure')}>Открыть подключения ↗</button></article>}{INTEGRATION_PROVIDERS.map(p=><article className="connector-card" key={p.key}><span className={`connector-mark ${p.key}`} aria-hidden="true">{p.mark}</span><span className="connector-type">Уведомления</span><h3>{p.name}</h3><p>{p.description}</p><button className="secondary" disabled={!canManage||!managed.length} onClick={()=>create(p.key)}>{canManage?'Подключить':'Нет права настройки'} <span aria-hidden="true">↗</span></button></article>)}{[['github','GitHub','GH'],['gitlab','GitLab','GL']].map(([key,name,mark])=><article className="connector-card" key={key}><span className="connector-mark git" aria-hidden="true">{mark}</span><span className="connector-type">Разработка</span><h3>{name}</h3><p>Коммиты, ветки, запросы слияния и сборки в карточках задач.</p><button className="secondary" onClick={()=>{setGitProvider(key);setTab('git');}}>Открыть подключения <span aria-hidden="true">↗</span></button></article>)}</div>{canManage&&!managed.length&&<p className="work-muted">Для создания подключения нужен активный проект с правом «Администрирование проекта».</p>}</>}
 {tab==='allure'&&<AllureView data={data} notify={notify}/>}
 {tab==='connections'&&<><div className="integration-filters"><Field label="Поиск подключения"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Название или сервис"/></Field><Field label="Проект"><Select items={projects} value={projectId} onChange={setProjectId} placeholder="Все доступные проекты"/></Field></div>{api.loading&&!api.value?<Empty>Загружаем подключения…</Empty>:!filtered.length?<Empty>Подключений пока нет. Выберите сервис в каталоге.</Empty>:<div className="connector-connections">{filtered.map(item=><article className="connector-connection" key={item.id}><div className="connector-connection-head"><span className={`connector-mark ${item.provider}`} aria-hidden="true">{providerFor(item.provider)?.mark}</span><div><h3>{item.name}</h3><p>{providerFor(item.provider)?.name} · {projects.find(p=>p.id===item.project_id)?.name}</p></div><span className={`connector-status ${item.enabled?'enabled':''}`}>{item.enabled?'Включено':'Пауза'}</span></div><p className="connector-destination">{item.destination_label}</p><div className="connector-events">{item.event_types.map(key=><span key={key}>{INTEGRATION_EVENTS.find(e=>e.key===key)?.name}</span>)}</div><div className="connector-actions">{allowed(item)&&<button className="secondary" disabled={busy} onClick={()=>setDraft({...item,credentials:{},replace_credentials:false})}>Настроить</button>}{features['integration.test']&&<button className="secondary" disabled={busy||!item.enabled} onClick={()=>setTest(item)}>Тестовая отправка</button>}{features['integration.logs']&&<button className="secondary" onClick={()=>setJournal(item)}>Журнал</button>}{allowed(item)&&<><button className="text-button" disabled={busy} onClick={()=>act(()=>mutate(item,'PATCH',{enabled:!item.enabled}))}>{item.enabled?'Приостановить':'Включить'}</button><button className="text-button danger-text" disabled={busy} onClick={()=>{if(confirm(`Удалить «${item.name}» и журнал доставки?`))act(()=>mutate(item,'DELETE'));}}>Удалить</button></>}</div></article>)}</div>}</>}
 {tab==='sync'&&<ExternalSyncView data={data} notify={notify}/>}
 {tab==='git'&&<DevelopmentTools key={gitProvider} data={data} notify={notify} initialProvider={gitProvider}/>}
 {tab==='legacy'&&canManage&&<><p className="integration-notice">Здесь сохранены настройки прежних webhooks. Для новых подключений с журналом и повторной доставкой используйте каталог выше. Личные токены также доступны в разделе «Мой API».</p>{Boolean(data.administration?.integrations?.length)&&<section className="work-card"><h2>Сохранённые подключения прежней версии</h2><p>Настройки сохранены. Для отправки уведомлений создайте подключение в каталоге, выберите проект и события.</p><div className="connector-connections">{data.administration.integrations.map(item=><article className="connector-connection" key={item.id}><h3>{item.name}</h3><p>{item.provider} · сохранённая конфигурация</p></article>)}</div></section>}<IntegrationsAdmin data={data} reload={reload} notify={notify}/></>}
 {draft&&<ConnectionEditor draft={draft} setDraft={setDraft} projects={managed} busy={busy} onSave={e=>{e.preventDefault();act(async()=>{const {id,replace_credentials,config,credentials,...rest}=draft;const input={name:rest.name,provider:rest.provider,project_id:rest.project_id,enabled:rest.enabled,event_types:rest.event_types,config,...(id?{version_number:rest.version_number}:{}),...(replace_credentials?{credentials}:{})};await workApi(id?`integrations/${id}`:'integrations',{method:id?'PUT':'POST',body:JSON.stringify(input)});setDraft(null);setTab('connections');await api.reload();notify('Подключение сохранено');});}}/>}
 {test&&<ToolDialog title="Отправить тестовое сообщение" onClose={()=>!busy&&setTest(null)}><p>Получатель: <strong>{test.name}</strong> · {test.destination_label}</p><blockquote className="integration-notice">Проверка подключения Контур. Уведомления доставляются.</blockquote><p>Сообщение будет отправлено в настроенный канал. Данные задач в проверку не входят.</p><button className="primary" disabled={busy} onClick={()=>act(async()=>{await workApi(`integrations/${test.id}/test`,{method:'POST',body:JSON.stringify({version_number:test.version_number})});const item=test;setTest(null);if(features['integration.logs'])setJournal(item);notify('Тестовое сообщение поставлено в очередь');})}>{busy?'Ставим в очередь…':'Отправить сообщение'}</button></ToolDialog>}
 {journal&&<DeliveryJournal item={journal} canRetry={Boolean(features['integration.test']&&data.permissions.projects[journal.project_id]?.['project.admin'])} notify={notify} onClose={()=>setJournal(null)}/>}
 </section>;
}
function ConnectionEditor({draft,setDraft,projects,busy,onSave}){
 const provider=providerFor(draft.provider),change=patch=>setDraft({...draft,...patch}),credentials=patch=>change({credentials:{...draft.credentials,...patch}}),config=patch=>change({config:{...draft.config,...patch}});
 return <ToolDialog title={`${draft.id?'Настроить':'Подключить'} ${provider.name}`} onClose={()=>!busy&&setDraft(null)}><form className="connector-editor" onSubmit={onSave}><Field label="Название подключения"><input required minLength={2} maxLength={160} value={draft.name} onChange={e=>change({name:e.target.value})} placeholder="Например, уведомления команды разработки"/></Field><Field label="Проект"><Select required disabled={Boolean(draft.id)} items={projects} value={draft.project_id} onChange={id=>change({project_id:id})}/></Field>
 {draft.provider==='telegram'&&<div className="work-form-grid"><Field label="Chat ID или @имя канала"><input required value={draft.config.chat_id||''} onChange={e=>config({chat_id:e.target.value})} placeholder="-1001234567890"/></Field><Field label="ID темы (необязательно)"><input type="number" min={1} value={draft.config.message_thread_id||''} onChange={e=>config({message_thread_id:e.target.value})}/></Field></div>}
 {draft.id&&<label className="connector-check"><input type="checkbox" checked={draft.replace_credentials} onChange={e=>change({replace_credentials:e.target.checked,credentials:{}})}/>Заменить сохранённые реквизиты</label>}
 {draft.replace_credentials&&<><Field label={provider.credential}><input type="password" autoComplete="new-password" required value={draft.provider==='telegram'?draft.credentials.token||'':draft.credentials.url||''} onChange={e=>credentials({[draft.provider==='telegram'?'token':'url']:e.target.value})} placeholder={draft.provider==='telegram'?'Токен от BotFather':'https://…'}/></Field>{draft.provider==='webhook'&&<Field label="Секрет HMAC-SHA256 (не менее 16 символов)"><input type="password" autoComplete="new-password" minLength={16} maxLength={256} required value={draft.credentials.secret||''} onChange={e=>credentials({secret:e.target.value})}/></Field>}<p className="work-muted">Реквизиты будут зашифрованы. После сохранения система их не показывает.</p></>}
 <fieldset className="connector-event-picker"><legend>Какие события отправлять</legend>{INTEGRATION_EVENTS.map(event=><label className="connector-check" key={event.key}><input type="checkbox" checked={draft.event_types.includes(event.key)} onChange={e=>change({event_types:e.target.checked?[...draft.event_types,event.key]:draft.event_types.filter(k=>k!==event.key)})}/>{event.name}</label>)}</fieldset>
 <p className="integration-notice">Получатель увидит ключ и название задачи выбранного проекта. Текст комментариев и вложения не передаются. Подключение работает от имени последнего редактора.</p><label className="connector-check"><input type="checkbox" checked={draft.enabled} onChange={e=>change({enabled:e.target.checked})}/>Включить доставку событий</label>{draft.id&&<small className="work-muted">Сохранение отменит ещё не отправленные сообщения этой конфигурации.</small>}<div className="connector-actions"><button type="button" className="secondary" disabled={busy} onClick={()=>setDraft(null)}>Отмена</button><button className="primary" disabled={busy||!draft.project_id||!draft.event_types.length}>{busy?'Сохраняем…':'Сохранить'}</button></div></form></ToolDialog>;
}
function DeliveryJournal({item,canRetry,notify,onClose}){
 const [status,setStatus]=useState(''),[offset,setOffset]=useState(0),[busy,act]=useAction(notify);
 const health=useWork(`integrations/${item.id}/health`),history=useWork(`integrations/${item.id}/history`);
 const api=useWork(`integrations/${item.id}/deliveries?offset=${offset}${status?`&status=${status}`:''}`);
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible')api.reload();},5000);return()=>clearInterval(timer);},[api.reload]);
 return <ToolDialog title={`Журнал · ${item.name}`} onClose={onClose}><div className="integration-filters"><Field label="Состояние"><select value={status} onChange={e=>{setStatus(e.target.value);setOffset(0);}}><option value="">Все</option>{Object.entries(DELIVERY_STATES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><button className="secondary" disabled={api.loading} onClick={api.reload}>Обновить</button></div><ErrorLine error={api.error}/>{health.value&&<div className="integration-notice"><strong>{health.value.health?.degraded?'Есть ошибки доставки':health.value.health?.last_success_at?'Последняя доставка успешна':'Ожидаем первую доставку'}</strong><p>За 24 часа: {health.value.last_24_hours.map(s=>`${DELIVERY_STATES[s.status]} — ${s.count}`).join(' · ')||'нет событий'}</p></div>}<details className="work-card"><summary>История настроек подключения</summary>{history.value?.map((h,i)=><p key={i}>{stamp(h.created_at)} · {h.actor||'Система'} · {h.action}</p>)}</details><p className="work-muted">Обновление каждые 5 секунд. До 5 автоматических попыток при временной ошибке.</p>{!api.value?.items.length?<Empty>{api.loading?'Загружаем журнал…':'Записей пока нет. Проверьте подключение или дождитесь события.'}</Empty>:<div className="connector-deliveries">{api.value.items.map(d=><article key={d.id}><div><strong>{d.event_type==='integration.test'?'Тестовое сообщение':INTEGRATION_EVENTS.find(e=>e.key===d.event_type)?.name||d.event_type}</strong><span className={`delivery-status ${d.status}`}>{DELIVERY_STATES[d.status]}</span></div><small>{stamp(d.created_at)} · попыток: {d.attempts}{d.http_status?` · HTTP ${d.http_status}`:''}</small>{d.error_code&&<p>{DELIVERY_ERRORS[d.error_code]||'Ошибка доставки'}</p>}{d.status==='pending'&&d.attempts>0&&<small>Повтор после {stamp(d.available_at)}</small>}<details><summary>Идентификатор события</summary><code>{d.event_uuid}</code></details>{canRetry&&d.status==='failed'&&item.enabled&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{await workApi(`integrations/${item.id}/deliveries/${d.id}/retry`,{method:'POST',body:'{}'});await api.reload();notify('Повторная отправка поставлена в очередь');})}>Повторить отправку</button>}</article>)}</div>}<div className="connector-actions"><button className="secondary" disabled={api.loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>← Новее</button><span>Страница {offset/50+1}</span><button className="secondary" disabled={api.loading||!api.value?.has_more} onClick={()=>setOffset(offset+50)}>Старее →</button></div></ToolDialog>;
}
