"use client";
import {useEffect,useRef,useState} from 'react';
import * as Y from 'yjs';
import {replaceText,lineDiff} from '../lib/knowledge-crdt.js';
import {workApi,useWork,ErrorLine,Empty} from './WorkUI.jsx';
const LOCAL='local-input';
const encode=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};
const decode=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
export default function KnowledgeCrdtEditor({articleId,canEdit,disabled,notify,onDirty,onEnabled,renderPreview}){
 const [enabled,setEnabled]=useState(null),[text,setText]=useState(''),[error,setError]=useState(''),[dirty,setDirty]=useState(false),[frozen,setFrozen]=useState(false),[people,setPeople]=useState([]),[version,setVersion]=useState(null),[preview,setPreview]=useState(false),[copied,setCopied]=useState(false),[scroll,setScroll]=useState({top:0,left:0});
 const live=useRef(null),editor=useRef(null),mounted=useRef(false),initialize=useRef(null),syncNow=useRef(null),callbacks=useRef({onDirty,onEnabled,canEdit});callbacks.current={onDirty,onEnabled,canEdit};
 function unsaved(value){setDirty(value);callbacks.current.onDirty(value);}
 useEffect(()=>{mounted.current=true;let active=true;
  function setup(result){
   if(!active)return;live.current?.undo.destroy();live.current?.doc.destroy();live.current=null;setError('');setFrozen(false);setCopied(false);setEnabled(result.enabled);callbacks.current.onEnabled(result.enabled);setVersion(result.version_number);unsaved(false);
   if(!result.enabled)return;
   const doc=new Y.Doc(),body=doc.getText('body');Y.applyUpdate(doc,decode(result.update),'remote');
   const undo=new Y.UndoManager(body,{trackedOrigins:new Set([LOCAL]),captureTimeout:500});
   const state={doc,text:body,undo,epoch:result.epoch,serverVector:Y.encodeStateVector(doc),edits:0,ack:0,inFlight:false,frozen:false,composing:false,clientId:crypto.randomUUID()};live.current=state;
   doc.on('update',(_update,origin)=>{if(origin===LOCAL||origin===undo){state.edits++;unsaved(true);setCopied(false);}if(active)setText(body.toString());});setText(body.toString());
  }
  async function load(){try{setup(await workApi(`knowledge/${articleId}/collaboration`));}catch(e){if(active)setError(e.message);}}
  initialize.current=async()=>{try{setup(await workApi(`knowledge/${articleId}/collaboration${callbacks.current.canEdit?'/initialize':''}`,callbacks.current.canEdit?{method:'POST',body:'{}'}:{}));}catch(e){if(active)setError(e.message);}};
  async function sync(){
   const state=live.current;if(!state||state.frozen||state.inFlight||state.composing||!active||document.hidden)return;
   state.inFlight=true;const sent=state.edits,selection=editor.current,anchor=selection?Y.createRelativePositionFromTypeIndex(state.text,selection.selectionStart):null,focus=selection?Y.createRelativePositionFromTypeIndex(state.text,selection.selectionEnd):null;
   try{const result=await workApi(`knowledge/${articleId}/collaboration/sync`,{method:'POST',body:JSON.stringify({epoch:state.epoch,client_id:state.clientId,vector:encode(Y.encodeStateVector(state.doc)),...(sent!==state.ack?{update:encode(Y.encodeStateAsUpdate(state.doc,state.serverVector))}:{}),anchor,focus})});
    if(!active||state!==live.current||state.composing)return;
    const field=editor.current,focused=document.activeElement===field,start=field?Y.createRelativePositionFromTypeIndex(state.text,field.selectionStart):null,end=field?Y.createRelativePositionFromTypeIndex(state.text,field.selectionEnd):null;
    Y.applyUpdate(state.doc,decode(result.update),'remote');state.serverVector=decode(result.vector);state.ack=sent;unsaved(state.edits!==state.ack);setVersion(result.version_number);setPeople(result.people||[]);setError('');
    if(focused)requestAnimationFrame(()=>{const a=Y.createAbsolutePositionFromRelativePosition(start,state.doc),b=Y.createAbsolutePositionFromRelativePosition(end,state.doc);if(a&&b&&editor.current===field)field.setSelectionRange(a.index,b.index);});
   }catch(e){if(active){setError(e.message);if([403,404,409,413,422].includes(e.status)){state.frozen=true;setFrozen(true);}}}finally{state.inFlight=false;}
  }
  syncNow.current=sync;load();const timer=setInterval(sync,1200),exit=e=>{if(live.current&&live.current.edits!==live.current.ack){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',exit);
  return()=>{active=false;mounted.current=false;clearInterval(timer);window.removeEventListener('beforeunload',exit);live.current?.undo.destroy();live.current?.doc.destroy();live.current=null;callbacks.current.onDirty(false);};
 },[articleId]);
 function change(value){const state=live.current;if(!state||frozen||disabled||!canEdit)return;replaceText(state.text,state.text.toString(),value,LOCAL);}
 function format(prefix,suffix=''){const field=editor.current;if(!field)return;const start=field.selectionStart,end=field.selectionEnd;change(text.slice(0,start)+prefix+text.slice(start,end)+suffix+text.slice(end));requestAnimationFrame(()=>{field.focus();field.setSelectionRange(start+prefix.length,end+prefix.length);});}
 const peers=people.filter(p=>p.client_id!==live.current?.clientId).map(p=>{try{const a=p.anchor&&Y.createAbsolutePositionFromRelativePosition(p.anchor,live.current.doc),b=p.focus&&Y.createAbsolutePositionFromRelativePosition(p.focus,live.current.doc);return a&&b?{...p,start:Math.min(a.index,b.index),end:Math.max(a.index,b.index),color:/^#[0-9a-f]{6}$/i.test(p.avatar_color)?p.avatar_color:'#675ee7'}:null;}catch{return null;}}).filter(Boolean);
 const offsets=[...new Set([0,text.length,...peers.flatMap(p=>[p.start,p.end])])].sort((a,b)=>a-b);
 return <section className="crdt-editor"><div className="work-header"><div><h3>Общий текст статьи</h3><p>{enabled?'Правки объединяются автоматически, в том числе в одном абзаце.':'Включите общий текст, чтобы работать одновременно в одном абзаце.'}</p></div>{version&&<span className="work-muted">v{version}</span>}</div><ErrorLine error={error}/>{enabled===null&&!error&&<p>Открываем документ…</p>}{enabled===false&&(canEdit?<button className="primary" disabled={disabled} onClick={()=>initialize.current?.()}>Включить одновременное редактирование</button>:<Empty>Редактор ещё не включён автором.</Empty>)}{enabled&&<><div className="crdt-toolbar"><span role="status">{frozen?'Синхронизация остановлена':dirty?'Есть несохранённые правки':'Все правки сохранены'}</span><button className="secondary" onClick={()=>setPreview(v=>!v)}>{preview?'Показать исходник':'Предпросмотр'}</button>{canEdit&&<><button className="secondary" disabled={disabled||frozen||preview} onClick={()=>format('**','**')} aria-label="Жирный текст"><b>Ж</b></button><button className="secondary" disabled={disabled||frozen||preview} onClick={()=>format('## ')}>Заголовок</button><button className="secondary" disabled={disabled||frozen||preview} onClick={()=>format('- ')}>Список</button><button className="secondary" disabled={disabled||frozen} onClick={()=>live.current?.undo.undo()}>Отменить</button><button className="secondary" disabled={disabled||frozen} onClick={()=>live.current?.undo.redo()}>Повторить</button></>}</div>
  <div className="work-presence" aria-label="Курсоры коллег">{peers.map(p=><span key={`${p.user_id}-${p.client_id}`} style={{borderColor:p.color}}>{p.display_name} · строка {text.slice(0,p.start).split('\n').length}{p.end>p.start?' · выделение':''}</span>)}</div>
  {preview?renderPreview?.(text):<div className="crdt-text-wrap"><pre className="crdt-cursor-layer" aria-hidden="true" style={{transform:`translate(${-scroll.left}px,${-scroll.top}px)`}}>{offsets.map((at,i)=><span key={at}>{peers.filter(p=>p.end===at).map(p=><span className="crdt-caret" key={`${p.user_id}-${p.client_id}`} style={{color:p.color}}><i/><small>{p.display_name}</small></span>)}<span style={{background:peers.find(p=>p.start<offsets[i+1]&&p.end>at)?`${peers.find(p=>p.start<offsets[i+1]&&p.end>at).color}25`:undefined}}>{text.slice(at,offsets[i+1]??at)}</span></span>)}</pre><textarea ref={editor} aria-label="Совместный текст статьи в Markdown" rows={18} maxLength={1000000} value={text} readOnly={!canEdit||disabled||frozen} onChange={e=>change(e.target.value)} onScroll={e=>setScroll({top:e.target.scrollTop,left:e.target.scrollLeft})} onCompositionStart={()=>{if(live.current)live.current.composing=true;}} onCompositionEnd={()=>{if(live.current)live.current.composing=false;syncNow.current?.();}} onKeyDown={e=>{if(canEdit&&!disabled&&!frozen&&(e.ctrlKey||e.metaKey)&&['z','y'].includes(e.key.toLowerCase())){e.preventDefault();e.stopPropagation();if(e.shiftKey||e.key.toLowerCase()==='y')live.current?.undo.redo();else live.current?.undo.undo();}}}/></div>}
  {frozen&&<div className="work-card"><p>Ваш текст остаётся в редакторе. Скопируйте его, прежде чем открыть актуальную версию.</p><div className="work-actions"><button className="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(text);setCopied(true);notify('Текст скопирован');}catch{notify('Выделите и скопируйте текст вручную','error');}}}>Скопировать мой текст</button><button className="secondary" disabled={dirty&&!copied} onClick={()=>initialize.current?.()}>Открыть актуальную версию</button></div></div>}</>}
 </section>;
}
export function ArticleVersionDiff({before,after}){const lines=lineDiff(before,after);return <div className="article-version-diff"><p><span className="diff-legend removed">− Удаляется</span> <span className="diff-legend added">+ Восстанавливается</span></p><pre>{lines.map((line,i)=><span className={`diff-line ${line.kind}`} key={i}>{line.kind==='added'?'+ ':line.kind==='removed'?'− ':'  '}{line.text||' '}\n</span>)}</pre></div>;}
export function StaleArticleList({onOpen}){const [open,setOpen]=useState(false),articles=useWork(open?'knowledge/stale':null);return <div className="stale-articles"><button className="secondary" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>Требуют актуализации {articles.value?`· ${articles.value.length}`:''}</button>{open&&<div className="work-card"><ErrorLine error={articles.error}/>{articles.value?.map(a=><button className="stale-article" key={a.id} onClick={()=>onOpen(a.id)}><strong>{a.title}</strong><span>{a.space_name} · до {a.review_due_date} · {a.steward_name||'Нет ответственного'}</span></button>)}{articles.value?.length===0&&<Empty>Просроченных проверок нет.</Empty>}</div>}</div>;}
