"use client";
import {useState} from 'react';
import {useWork,useAction,workApi,ErrorLine,Empty} from './WorkUI.jsx';
function Suggestions({start,end,notify,onApplied}){
 const report=useWork(`leveling?start=${start}&end=${end}`),[busy,act]=useAction(notify),[undo,setUndo]=useState(null);
 const name=id=>report.value?.people.find(p=>p.id===id)?.display_name||'Сотрудник';
 return <div className="work-card"><ErrorLine error={report.error}/>{report.loading&&<p>Проверяем доступность и нагрузку…</p>}{report.value&&<><p className="work-muted">{report.value.note}</p><p>Без оценки: {report.value.unestimated_tasks} задач. Предложений: {report.value.proposals.length}.</p>{report.value.proposals.map(p=><div className="leveling-proposal" key={p.task_id}><div><strong>{p.task_key} · {p.title}</strong><p>{name(p.from_user_id)} → {name(p.to_user_id)} · {p.hours} ч</p><small>Снижение перегрузки на {p.reduced_overload_hours} ч</small></div><button className="secondary" disabled={busy} onClick={()=>act(async()=>{const result=await workApi('task-changes',{method:'POST',body:JSON.stringify({task_id:p.task_id,version_number:p.version_number,patch:{assignee_id:p.to_user_id}})});setUndo(result.undo_id);await report.reload();await onApplied();notify('Исполнитель изменён');})}>Назначить</button></div>)}{!report.value.proposals.length&&<Empty>Подходящих переносов нет. Проверьте оценки, доступы участников и резерв времени.</Empty>}{undo&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{await workApi(`undo/${undo}`,{method:'POST',body:'{}'});setUndo(null);await report.reload();await onApplied();notify('Назначение отменено');})}>Отменить последнее назначение</button>}</>}</div>;
}
export default function LevelingSuggestions(props){const [open,setOpen]=useState(false);return <div className="leveling-panel"><button className="secondary" onClick={()=>setOpen(v=>!v)} aria-expanded={open}>{open?'Скрыть предложения':'Предложить перераспределение задач'}</button>{open&&<Suggestions {...props}/>}</div>;}
