"use client";
import {useState} from 'react';
import ToolDialog from './ToolDialog.jsx';
import {useWork,useAction,workApi,Field,ErrorLine,Empty} from './WorkUI.jsx';
const kinds={project:'Проект',board:'Доска',plan:'План',article:'Статья'},icons={project:'▤',board:'▥',plan:'◇',article:'▧'};
// Показывает одинаковое личное избранное на компьютере и телефоне, сохраняя порядок на сервере.
export default function PersonalFavorites({open,onOpen,onClose,notify}){
 const saved=useWork('favorites'),[kind,setKind]=useState('project'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[dragged,setDragged]=useState(null),choices=useWork(open?`favorites/choices?kind=${kind}&q=${encodeURIComponent(search)}`:null),[busy,act]=useAction(notify),items=saved.value?.items||[];
 // Сохраняет состав с версией, чтобы другая вкладка не могла незаметно перезаписать список.
 function save(next){act(async()=>{try{const value=await workApi('favorites',{method:'PUT',body:JSON.stringify({revision:saved.value.revision,items:next.map(({kind,id})=>({kind,id}))})});saved.setValue(value);}catch(e){if(e.status===409)await saved.reload();throw e;}});}
 // Перемещает ссылку по кнопкам или после перетаскивания, включая управление с телефона.
 function move(from,to){if(from==null||to<0||to>=items.length||from===to||busy)return;const next=[...items],[item]=next.splice(from,1);next.splice(to,0,item);save(next);setDragged(null);}
 return <><details className="sidebar-projects personal-favorites" open><summary className="sidebar-section-label">Избранное <span>{items.length}</span></summary>{items.slice(0,5).map(item=><a className="favorite-link" key={`${item.kind}:${item.id}`} href={item.href}><span>{icons[item.kind]}</span><span><strong>{item.title}</strong><small>{kinds[item.kind]}</small></span></a>)}<button type="button" onClick={onOpen}>{items.length>5?`Все ссылки (${items.length})`:'Настроить избранное'} <span>☆</span></button><ErrorLine error={saved.error}/></details>
 {open&&<ToolDialog title="Личное избранное" subtitle="Проекты, доски, планы и статьи в вашем порядке" onClose={onClose}><ErrorLine error={saved.error||choices.error}/><div className="favorite-list">{items.map((item,index)=><div className="favorite-row" key={`${item.kind}:${item.id}`} draggable={!busy} onDragStart={()=>setDragged(index)} onDragEnd={()=>setDragged(null)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();move(dragged,index);}}><span className="favorite-grip" aria-hidden="true">⠿</span><a href={item.href}><strong>{item.title}</strong><small>{kinds[item.kind]}</small></a><button type="button" className="secondary" disabled={busy||!index} aria-label={`Выше: ${item.title}`} onClick={()=>move(index,index-1)}>↑</button><button type="button" className="secondary" disabled={busy||index===items.length-1} aria-label={`Ниже: ${item.title}`} onClick={()=>move(index,index+1)}>↓</button><button type="button" className="secondary" disabled={busy} aria-label={`Убрать: ${item.title}`} onClick={()=>save(items.filter((_,i)=>i!==index))}>×</button></div>)}</div>{!items.length&&<Empty>Добавьте ссылки, которые часто открываете.</Empty>}
 <form className="favorite-search" onSubmit={event=>{event.preventDefault();setSearch(query);}}><Field label="Тип ссылки"><select value={kind} onChange={event=>setKind(event.target.value)}>{Object.entries(kinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Найти ссылку"><input maxLength={180} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Название…"/></Field><button type="submit" className="secondary">Найти</button></form>
 <div className="favorite-choices">{choices.value?.items.map(item=>{const exists=items.some(i=>i.kind===item.kind&&i.id===item.id);return <button type="button" key={`${item.kind}:${item.id}`} disabled={busy||exists||items.length>=30||!saved.value} onClick={()=>save([...items,item])}><span>{icons[item.kind]} {item.title}</span><span>{exists?'✓':'+ Добавить'}</span></button>;})}</div>{choices.loading&&<p className="work-muted">Ищем доступные ссылки…</p>}{choices.value?.items.length===0&&<Empty>Доступных ссылок по этому запросу нет.</Empty>}<p className="work-muted">До 30 ссылок. Порядок можно менять перетаскиванием или стрелками. После отзыва доступа ссылка исчезнет.</p></ToolDialog>}</>;
}
