"use client";
import {useEffect,useState} from 'react';
import ToolDialog from './ToolDialog.jsx';
import {workApi,useWork,useAction,Field,Select,Empty,ErrorLine,shortDate} from './WorkUI.jsx';
const priorities={critical:'Критический',high:'Высокий',medium:'Обычный',low:'Низкий'};
const states={planning:'Планируется',active:'В работе',cancelled:'Отменено'};
// Извлекает редактируемые поля плана без служебных значений ответа.
function planDraft(plan){return {title:plan.title||'',description:plan.description||'',start_date:plan.start_date||null,due_date:plan.due_date||null,objective_id:plan.objective_id||null,archived:Boolean(plan.archived),...(plan.id?{id:plan.id,revision:plan.revision}:{project_id:plan.project_id||null,request_id:crypto.randomUUID()})};}
// Подготавливает поля запланированной задачи либо нового эпика.
function itemDraft(item={}){return {kind:item.kind||'task',parent_id:item.parent_id||null,title:item.title||'',description:item.description||'',priority:item.priority||'medium',assignee_id:item.assignee_id||null,start_date:item.start_date||null,due_date:item.due_date||null,estimate_minutes:item.estimate_minutes??null,story_points:item.story_points==null?null:Number(item.story_points),objective_id:item.objective_id||null,state:item.state||'planning',...(item.id?{id:item.id,revision:item.revision}:{request_id:crypto.randomUUID()})};}
// Показывает проекты-черновики и инициативы работающих проектов с эпиками и целями.
export default function PlansView({data,notify,reload,onTask}){
 const list=useWork('plans'),goals=useWork('plans/goals'),[selected,setSelected]=useState(null),detail=useWork(selected?`plans/${selected}`:null),[draft,setDraft]=useState(null),[item,setItem]=useState(null),[start,setStart]=useState(null),[members,setMembers]=useState(null),[search,setSearch]=useState(''),[showArchive,setShowArchive]=useState(false),[busy,act]=useAction(notify);
 const projects=data.projects.filter(p=>data.permissions.projects[p.id]?.['planning.manage']&&data.permissions.projects[p.id]?.['planning.view']),canCreate=Boolean(data.permissions.features['planning.create']),plan=detail.value,items=plan?.items||[],goalOptions=goals.value||[];
 useEffect(()=>{const id=Number(new URLSearchParams(window.location.search).get('plan'));if(id)setSelected(id);},[]);
 useEffect(()=>{if(!selected&&list.value?.plans.length)setSelected(list.value.plans[0].id);},[list.value,selected]);
 // Обновляет план и список после завершённого изменения.
 async function refresh(){await Promise.all([list.reload(),detail.reload()]);}
 // Сохраняет поля инициативы с проверкой версии на сервере.
 function savePlan(event){event.preventDefault();act(async()=>{const {id,...payload}=draft,result=await workApi(id?`plans/${id}`:'plans',{method:id?'PUT':'POST',body:JSON.stringify(payload)});setDraft(null);if(!id)setSelected(result.id);await refresh();notify('План сохранён');});}
 // Сохраняет эпик или задачу, не изменяя текущие рабочие задачи проекта.
 function saveItem(event){event.preventDefault();act(async()=>{const {id,...payload}=item;await workApi(`plans/${plan.id}/items${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(payload)});setItem(null);await refresh();notify('Запланированная задача сохранена');});}
 // Начинает выполнение одной задачи, повторный запрос возвращает ту же рабочую карточку.
 function beginItem(value){act(async()=>{await workApi(`plans/${plan.id}/items/${value.id}/start`,{method:'POST',body:JSON.stringify({revision:value.revision})});await refresh();await reload();notify('Задача перешла в рабочий процесс проекта');});}
 // Создаёт рабочий проект или связывает черновик с уже существующим.
 function beginProject(event){event.preventDefault();act(async()=>{const payload=start.project_id?{revision:plan.revision,project_id:start.project_id}:{revision:plan.revision,key_code:start.key_code,workflow_id:start.workflow_id};await workApi(`plans/${plan.id}/start-project`,{method:'POST',body:JSON.stringify(payload)});setStart(null);await reload();await refresh();notify('План связан с рабочим проектом');});}
 // Отображает строку эпика или вложенной задачи вместе с доступными действиями.
 function itemRow(value,nested=false){return <article className={`plan-item ${nested?'nested':''}`} key={value.id}><div className={`plan-kind ${value.kind}`}>{value.kind==='epic'?'◇':'□'}</div><div className="plan-item-copy"><button type="button" onClick={()=>value.state==='active'&&value.task_id?onTask(value.task_id):setItem(itemDraft(value))}><strong>{value.title}</strong></button><div><span className={`plan-state ${value.state}`}>{states[value.state]}</span><span>{value.kind==='epic'?'Эпик':'Задача'}</span>{value.objective_title&&<span title={value.objective_title}>◎ {value.objective_title}</span>}{value.due_date&&<span>до {shortDate(value.due_date)}</span>}{value.story_points!=null&&<span>{value.story_points} баллов</span>}{value.assignee_id&&<span>{data.users.find(u=>u.id===value.assignee_id)?.display_name||'Участник'}</span>}</div></div><div className="plan-item-actions">{plan.can_edit&&value.kind==='epic'&&value.state!=='cancelled'&&<button type="button" className="secondary" aria-label={`Добавить задачу в эпик ${value.title}`} onClick={()=>setItem(itemDraft({parent_id:value.id,objective_id:value.objective_id}))}>+ Задача</button>}{plan.can_edit&&plan.project_id&&value.state==='planning'&&data.permissions.projects[plan.project_id]?.['task.create']&&<button type="button" className="secondary" disabled={busy} onClick={()=>beginItem(value)}>Начать работу</button>}</div></article>;}
 return <section className="plans-view">
  <div className="plans-heading"><div><span className="overline">ОТ ИДЕИ К РЕЗУЛЬТАТУ</span><h2>Планы и идеи</h2><p>Проекты, эпики и задачи, которые вы готовите к работе.</p></div>{(canCreate||projects.length>0)&&<button type="button" className="primary" onClick={()=>setDraft(planDraft({project_id:canCreate?null:projects[0].id}))}>+ Новый план</button>}</div>
  <ErrorLine error={list.error||detail.error}/>
  <div className="planning-layout"><aside className="plans-list"><input aria-label="Найти план" type="search" placeholder="Найти план…" value={search} onChange={e=>setSearch(e.target.value)}/><label className="plan-archive"><input type="checkbox" checked={showArchive} onChange={e=>setShowArchive(e.target.checked)}/>Показать архив</label>{list.value?.plans.filter(p=>(showArchive||!p.archived)&&p.title.toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru'))).map(p=><button type="button" className={Number(selected)===Number(p.id)?'active':''} key={p.id} onClick={()=>setSelected(p.id)}><span className="plan-list-icon">{p.project_id?'▤':'◇'}</span><span><strong>{p.title}</strong><small>{p.archived?'Архив':p.project_id?'Рабочий проект':'Проект-черновик'} · {p.planned_count} в плане</small></span></button>)}{list.value?.has_more&&<p className="work-muted">Показаны последние 500 планов.</p>}{list.value?.plans.length===0&&<Empty>Сохраните идею первого проекта или эпика.</Empty>}</aside>
  <div className="plan-detail">{detail.loading&&!plan?<Empty>Загружаем план…</Empty>:plan?<><header className="plan-detail-head"><div><span className="plan-state planning">{plan.archived?'Архив':plan.project_id?'Инициатива проекта':'Проект-черновик'}</span><h3>{plan.title}</h3><p>{plan.description||'Добавьте контекст: зачем нужен этот план и какой результат ожидается.'}</p><div className="plan-meta">{plan.project_id&&<span>▤ {data.projects.find(p=>p.id===plan.project_id)?.name||'Проект'}</span>}{plan.objective_title&&<span>◎ {plan.objective_title}</span>}{plan.due_date&&<span>До {shortDate(plan.due_date)}</span>}</div></div><div className="plan-head-actions">{plan.can_restore&&<button type="button" className="secondary" disabled={busy} onClick={()=>act(async()=>{await workApi(`plans/${plan.id}/restore`,{method:'POST',body:JSON.stringify({revision:plan.revision})});await refresh();notify('План возвращён из архива');})}>Вернуть из архива</button>}{plan.can_edit&&<button type="button" className="secondary" onClick={()=>setDraft(planDraft(plan))}>Изменить план</button>}{plan.can_share&&<button type="button" className="secondary" onClick={()=>setMembers(plan.members.map(m=>({user_id:m.user_id,can_edit:Boolean(m.can_edit)})))}>Участники</button>}{plan.can_edit&&!plan.project_id&&<button type="button" className="primary" onClick={()=>setStart({project_id:null,key_code:'',workflow_id:data.workflows[0]?.id})}>Создать рабочий проект</button>}</div></header>
   <div className="plan-stats"><div><strong>{items.filter(i=>i.state==='planning').length}</strong><span>Планируется</span></div><div><strong>{items.filter(i=>i.kind==='epic'&&i.state!=='cancelled').length}</strong><span>Эпиков</span></div><div><strong>{items.filter(i=>i.state==='active').length}</strong><span>Передано в работу</span></div></div>
   <div className="plan-items-head"><h4>Состав плана</h4>{plan.can_edit&&<div><button type="button" className="secondary" onClick={()=>setItem(itemDraft({kind:'epic',objective_id:plan.objective_id}))}>+ Эпик</button><button type="button" className="primary" onClick={()=>setItem(itemDraft({objective_id:plan.objective_id}))}>+ Задача в план</button></div>}</div>
   <div className="plan-tree">{items.filter(i=>!i.parent_id).map(value=><div className="plan-group" key={value.id}>{itemRow(value)}{items.filter(i=>Number(i.parent_id)===Number(value.id)).map(child=>itemRow(child,true))}</div>)}{items.length===0&&<div className="plan-empty"><span>◇</span><h3>Начните с крупной идеи</h3><p>Добавьте эпик, разбейте его на задачи и свяжите с целью.</p></div>}</div>
   <p className="work-muted">{plan.project_id?'Запланированные карточки уже видны участникам с правом планирования в колонке «Планируется» на доске проекта.':'После создания рабочего проекта карточки появятся на его доске в колонке «Планируется». Права будут определяться настройками рабочего проекта.'}</p>
  </>:<Empty>Выберите план слева или создайте новый.</Empty>}</div></div>
  {draft&&<ToolDialog title={draft.id?'Изменить план':'Новый план'} onClose={()=>!busy&&setDraft(null)}><form onSubmit={savePlan}>{!draft.id&&<Field label="Где планируем"><select value={draft.project_id||''} onChange={e=>setDraft({...draft,project_id:Number(e.target.value)||null})}>{canCreate&&<option value="">Новый проект-черновик</option>}{projects.map(p=><option key={p.id} value={p.id}>В проекте «{p.name}»</option>)}</select></Field>}<Field label="Название плана"><input required minLength={2} maxLength={180} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></Field><Field label="Замысел и ожидаемый результат"><textarea rows={4} maxLength={10000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></Field><PlanDates value={draft} onChange={setDraft}/><Field label="Цель плана"><Select items={goalOptions} value={draft.objective_id} onChange={objective_id=>setDraft({...draft,objective_id})} placeholder="Без привязки к цели"/></Field><ErrorLine error={goals.error}/>{draft.id&&<label className="connector-check"><input type="checkbox" checked={draft.archived} onChange={e=>setDraft({...draft,archived:e.target.checked})}/>Переместить в архив</label>}<button className="primary" disabled={busy}>Сохранить план</button></form></ToolDialog>}
  {item&&plan&&<ToolDialog title={item.id?'Запланированная задача':'Добавить в план'} onClose={()=>!busy&&setItem(null)}><form onSubmit={saveItem}><fieldset disabled={busy||!plan.can_edit}><div className="work-form-grid"><Field label="Тип элемента"><select value={item.kind} onChange={e=>setItem({...item,kind:e.target.value,parent_id:null})}><option value="epic">Эпик</option><option value="task">Задача</option></select></Field>{item.kind==='task'&&<Field label="Родительский эпик"><Select items={items.filter(i=>i.kind==='epic'&&i.state!=='cancelled')} value={item.parent_id} onChange={parent_id=>setItem({...item,parent_id})} placeholder="Без эпика"/></Field>}</div><Field label="Название в плане"><input required minLength={2} maxLength={300} value={item.title} onChange={e=>setItem({...item,title:e.target.value})}/></Field><Field label="Описание и критерии готовности"><textarea rows={4} maxLength={10000} value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/></Field><div className="work-form-grid"><Field label="Приоритет"><select value={item.priority} onChange={e=>setItem({...item,priority:e.target.value})}>{Object.entries(priorities).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="Ответственный"><Select items={data.users} value={item.assignee_id} onChange={assignee_id=>setItem({...item,assignee_id})}/></Field></div><PlanDates value={item} onChange={setItem}/><div className="work-form-grid"><Field label="Оценка, часов"><input type="number" min={0} max={166666} step={.25} value={item.estimate_minutes==null?'':item.estimate_minutes/60} onChange={e=>setItem({...item,estimate_minutes:e.target.value===''?null:Math.round(Number(e.target.value)*60)})}/></Field><Field label="Оценка, баллов"><input type="number" min={0} max={1000000} step={.5} value={item.story_points??''} onChange={e=>setItem({...item,story_points:e.target.value===''?null:Number(e.target.value)})}/></Field></div><Field label="Связанная цель"><Select items={goalOptions} value={item.objective_id} onChange={objective_id=>setItem({...item,objective_id})} placeholder="Без привязки к цели"/></Field>{item.id&&<Field label="Состояние"><select value={item.state} onChange={e=>setItem({...item,state:e.target.value})}><option value="planning">Планируется</option><option value="cancelled">Отменено</option></select></Field>}{plan.can_edit&&<button className="primary">Сохранить в плане</button>}</fieldset></form></ToolDialog>}
  {start&&<ToolDialog title="Рабочий проект для плана" onClose={()=>!busy&&setStart(null)}><form onSubmit={beginProject}><Field label="Проект"><Select items={projects} value={start.project_id} onChange={project_id=>setStart({...start,project_id})} placeholder="Создать новый проект"/></Field>{!start.project_id&&<><Field label="Ключ проекта"><input required pattern="[A-Z][A-Z0-9]{1,11}" maxLength={12} placeholder="NOVA" value={start.key_code} onChange={e=>setStart({...start,key_code:e.target.value.toUpperCase()})}/></Field><Field label="Рабочий процесс"><Select required items={data.workflows} value={start.workflow_id} onChange={workflow_id=>setStart({...start,workflow_id})}/></Field></>}<p className="work-muted">Эпики и задачи останутся в статусе «Планируется». Начать работу над ними можно отдельно.</p><button className="primary" disabled={busy||(!start.project_id&&!data.permissions.features['project.create'])}>Подтвердить проект</button></form></ToolDialog>}
  {members&&<ToolDialog title="Участники проекта-черновика" onClose={()=>!busy&&setMembers(null)}><p>Участники видят план. Изменение разрешается отдельно; автор сохраняет доступ.</p><div className="plan-member-list">{data.users.map(person=>{const member=members.find(m=>m.user_id===person.id),author=person.id===plan.created_by;return <div key={person.id}><label><input type="checkbox" checked={Boolean(member)||author} disabled={author} onChange={e=>setMembers(e.target.checked?[...members,{user_id:person.id,can_edit:false}]:members.filter(m=>m.user_id!==person.id))}/>{person.display_name}</label>{member&&<label><input type="checkbox" checked={member.can_edit||author} disabled={author} onChange={e=>setMembers(members.map(m=>m.user_id===person.id?{...m,can_edit:e.target.checked}:m))}/>Может изменять</label>}</div>;})}</div><button className="primary" disabled={busy} onClick={()=>act(async()=>{await workApi(`plans/${plan.id}/members`,{method:'PUT',body:JSON.stringify({revision:plan.revision,members})});setMembers(null);await refresh();notify('Участники обновлены');})}>Сохранить участников</button></ToolDialog>}
 </section>;
}
// Показывает пару календарей с ограничением срока относительно начала.
function PlanDates({value,onChange}){return <div className="work-form-grid"><Field label="Плановое начало"><input type="date" value={value.start_date||''} onChange={e=>onChange({...value,start_date:e.target.value||null})}/></Field><Field label="Плановый срок"><input type="date" min={value.start_date||undefined} value={value.due_date||''} onChange={e=>onChange({...value,due_date:e.target.value||null})}/></Field></div>;}

// Добавляет на рабочую доску карточки планирования, доступные по отдельному разрешению.
export function BoardPlans({project,data,filters={},query=''}){
 const api=useWork(`plans/board?project_id=${project.id}`),items=api.value?.items||[];
 const visible=items.filter(item=>(!filters.priority||filters.priority===item.priority)&&(!filters.assignee||Number(filters.assignee)===Number(item.assignee_id))&&(!filters.overdue||(item.due_date&&item.due_date<new Date().toLocaleDateString('sv-SE')))&&(!filters.issueType||data.issueTypes.find(t=>Number(t.id)===Number(filters.issueType))?.code===item.kind)&&(!query||`${item.title} ${item.description}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru'))));
 return <section className="board-column planning-column"><div className="column-head"><div><span className="stage-dot" style={{background:'#a095c9'}}/><strong>Планируется</strong><span>{visible.length}</span></div><a href="/?view=work&tab=plans" aria-label="Открыть планирование">↗</a></div><ErrorLine error={api.error}/><div className="task-list">{visible.map(item=><a className="planned-card" key={item.id} href={`/?view=work&tab=plans&plan=${item.plan_id}`}><div><span className={`priority ${item.priority}`}>{priorities[item.priority]}</span><span>{item.kind==='epic'?'◇ Эпик':'□ Задача'}</span></div><h3>{item.title}</h3><p>{item.plan_title}</p>{item.objective_title&&<small>◎ {item.objective_title}</small>}<footer><span>Планируется</span><span>{item.due_date?shortDate(item.due_date):'Без срока'}</span></footer></a>)}{!visible.length&&<div className="drop-zone">{api.loading?'Загрузка плана…':'Здесь появятся запланированные эпики и задачи'}</div>}{api.value?.has_more&&<a href="/?view=work&tab=plans">Открыть все планы →</a>}</div></section>;
}
