"use client";
import {useState} from 'react';
import {useWork,useAction,workApi,Field,Select,ErrorLine,shortDate} from './WorkUI.jsx';
import ToolDialog from './ToolDialog.jsx';
const reviewLabels={pending:'Ожидает решения',approved:'Согласовано',rejected:'Отклонено',outdated:'Состав изменён — требуется новое согласование'};
// Объединяет обоснование приоритета, связи и решения по конкретному составу плана.
export default function PlanStrategy({plan,data,notify}){
 const api=useWork(`plans/${plan.id}/strategy`),[edit,setEdit]=useState(null),[review,setReview]=useState(null),[decision,setDecision]=useState(null),[link,setLink]=useState(null),[busy,act]=useAction(notify),value=api.value;
 // Сохраняет отдельную оценку или решение и обновляет их действительность.
 function send(path,method,payload,close){act(async()=>{await workApi(`plans/${plan.id}/${path}`,{method,body:JSON.stringify(payload)});close?.();await api.reload();notify('План обновлён');});}
 return <section className="plan-strategy"><ErrorLine error={api.error}/>{value&&<><div className="plan-strategy-heading"><div><h4>Почему этот план важен</h4><p>{value.strategy.outcome||'Опишите ожидаемое изменение для команды или клиентов.'}</p></div>{plan.can_edit&&<button type="button" className="secondary" onClick={()=>setEdit({...value.strategy,effort:Number(value.strategy.effort)})}>Оценить приоритет</button>}</div><div className="plan-score"><span>Эффект <b>{value.strategy.impact}/10</b></span><span>Усилия <b>{Number(value.strategy.effort)} чел.-дн.</b></span><span>Польза / усилия <b>{Number(value.strategy.effort)>0?(value.strategy.impact/Number(value.strategy.effort)).toFixed(2):'—'}</b></span></div>{value.strategy.rationale&&<p className="work-muted">{value.strategy.rationale}</p>}
 <details className="plan-decision-panel"><summary>Зависимости и согласование <span>{value.reviews[0]?reviewLabels[value.reviews[0].status]:'Решение ещё не запрошено'}</span></summary><h4>Что должно быть готово раньше</h4>{value.dependencies.map(d=><div className="plan-dependency" key={d.id}><span>{plan.items.find(i=>i.id===d.item_id)?.title} ← {d.task_title||plan.items.find(i=>i.id===d.depends_on_item_id)?.title||'Элемент плана'}</span>{plan.can_edit&&plan.items.find(i=>i.id===d.item_id)?.state==='planning'&&<button type="button" className="text-button" disabled={busy} onClick={()=>send('dependencies','DELETE',{revision:value.strategy.revision,item_id:d.item_id,depends_on_item_id:d.depends_on_item_id,depends_on_task_id:d.depends_on_task_id})}>Убрать связь</button>}</div>)}{plan.can_edit&&<div className="work-actions"><button type="button" className="secondary" onClick={()=>setLink({item_id:null,target:'plan',depends_on_item_id:null,depends_on_task_id:null})}>Добавить зависимость</button><button type="button" className="primary" onClick={()=>setReview({reviewer_ids:[],reason:'',request_id:crypto.randomUUID()})}>Запросить согласование</button></div>}
 {value.reviews.map(r=><article className={`plan-review ${r.status}`} key={r.id}><header><strong>{reviewLabels[r.status]}</strong><small>{shortDate(r.created_at)}</small></header><p>{r.reason}</p>{r.people.map(p=><p key={p.user_id}>{p.display_name}: {p.unavailable?'доступ отозван':reviewLabels[p.decision]}{p.comment&&` · ${p.comment}`}</p>)}{r.status==='pending'&&r.people.some(p=>p.user_id===data.user.id&&p.decision==='pending')&&<button type="button" className="secondary" onClick={()=>setDecision({id:r.id,decision:'approved',comment:''})}>Принять решение</button>}</article>)}<p className="work-muted">Решение относится к текущим полям, задачам и связям. Изменения требуют нового согласования.</p></details>
 </>}{edit&&<ToolDialog title="Приоритет плана" onClose={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();const {revision,outcome,impact,effort,rationale}=edit;send('strategy','PUT',{revision,outcome,impact,effort,rationale},()=>setEdit(null));}}><Field label="Ожидаемый результат"><textarea rows={3} maxLength={6000} value={edit.outcome} onChange={e=>setEdit({...edit,outcome:e.target.value})}/></Field><div className="work-form-grid"><Field label="Эффект, от 0 до 10"><input type="number" required min={0} max={10} value={edit.impact} onChange={e=>setEdit({...edit,impact:Number(e.target.value)})}/></Field><Field label="Усилия, человеко-дней"><input type="number" required min={0} max={1000000} step={.25} value={edit.effort} onChange={e=>setEdit({...edit,effort:Number(e.target.value)})}/></Field></div><Field label="Обоснование приоритета"><textarea rows={3} maxLength={6000} value={edit.rationale} onChange={e=>setEdit({...edit,rationale:e.target.value})}/></Field><button className="primary" disabled={busy}>Сохранить оценку</button></form></ToolDialog>}
 {review&&<ToolDialog title="Согласование состава плана" onClose={()=>setReview(null)}><form onSubmit={e=>{e.preventDefault();send('reviews','POST',{...review,content_hash:value.content_hash},()=>setReview(null));}}><Field label="Что нужно согласовать"><textarea required minLength={2} maxLength={4000} value={review.reason} onChange={e=>setReview({...review,reason:e.target.value})}/></Field><p>Все выбранные участники должны иметь доступ к плану. Автор запроса не согласует его сам.</p><div className="plan-reviewer-choices">{data.users.filter(p=>p.id!==data.user.id&&(!plan.project_id?plan.members.some(m=>m.user_id===p.id):true)).map(p=><label key={p.id}><input type="checkbox" checked={review.reviewer_ids.includes(p.id)} onChange={e=>setReview({...review,reviewer_ids:e.target.checked?[...review.reviewer_ids,p.id]:review.reviewer_ids.filter(id=>id!==p.id)})}/>{p.display_name}</label>)}</div><button className="primary" disabled={busy||!review.reviewer_ids.length}>Отправить состав на согласование</button></form></ToolDialog>}
 {decision&&<ToolDialog title="Решение по плану" onClose={()=>setDecision(null)}><form onSubmit={e=>{e.preventDefault();send(`reviews/${decision.id}/decision`,'POST',{decision:decision.decision,comment:decision.comment},()=>setDecision(null));}}><Field label="Решение"><select value={decision.decision} onChange={e=>setDecision({...decision,decision:e.target.value})}><option value="approved">Согласовать</option><option value="rejected">Отклонить</option></select></Field><Field label="Комментарий к плану"><textarea required minLength={2} maxLength={4000} value={decision.comment} onChange={e=>setDecision({...decision,comment:e.target.value})}/></Field><button className="primary" disabled={busy}>Сохранить решение</button></form></ToolDialog>}
 {link&&<ToolDialog title="Зависимость плана" onClose={()=>setLink(null)}><form onSubmit={e=>{e.preventDefault();send('dependencies','POST',{revision:value.strategy.revision,item_id:link.item_id,depends_on_item_id:link.target==='plan'?link.depends_on_item_id:null,depends_on_task_id:link.target==='task'?link.depends_on_task_id:null},()=>setLink(null));}}><Field label="Элемент, который ожидает"><Select required items={plan.items.filter(i=>i.state==='planning')} value={link.item_id} onChange={item_id=>setLink({...link,item_id})}/></Field><Field label="Предшественник"><select value={link.target} onChange={e=>setLink({...link,target:e.target.value})}><option value="plan">Элемент этого плана</option><option value="task">Рабочая задача</option></select></Field><Field label="Что должно быть готово"><Select required items={link.target==='plan'?plan.items.filter(i=>i.id!==link.item_id&&i.state!=='cancelled'):data.tasks} value={link.target==='plan'?link.depends_on_item_id:link.depends_on_task_id} onChange={id=>setLink({...link,[link.target==='plan'?'depends_on_item_id':'depends_on_task_id']:id})}/></Field><button className="primary" disabled={busy}>Сохранить зависимость</button></form></ToolDialog>}</section>;
}
