"use client";
import {useEffect,useState} from 'react';
import ToolDialog,{toolApi} from './ToolDialog.jsx';
import {Field,ErrorLine,Empty} from './WorkUI.jsx';

const names={manager:'Руководитель',member:'Участник',viewer:'Наблюдатель'};
const descriptions={manager:'Настройки проекта, участники и все рабочие действия',member:'Задачи, комментарии и совместная работа',viewer:'Просмотр проекта, отчёты и общение'};

// Управляет личными и групповыми назначениями и явно показывает владельца проекта.
export default function ProjectAccessPanel({project,data,onChanged}){
 const [access,setAccess]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[kind,setKind]=useState('user'),[search,setSearch]=useState(''),[principal,setPrincipal]=useState(''),[role,setRole]=useState('member'),[transfer,setTransfer]=useState(null),[remove,setRemove]=useState(null),[group,setGroup]=useState(null),[effective,setEffective]=useState(null),[mode,setMode]=useState(null);
 const base=`/api/projects/${project.id}`;
 useEffect(()=>{const controller=new AbortController();toolApi(`${base}/access`,{signal:controller.signal}).then(setAccess).catch(failure=>{if(!controller.signal.aborted)setError(failure.message);});return()=>controller.abort();},[base]);
 // Обновляет доступ из ответа сервера после каждой операции и сбрасывает старую проверку прав.
 async function refresh(){setAccess(await toolApi(`${base}/access`));setEffective(null);await onChanged?.();}
 // Отправляет версию списка назначений, чтобы два руководителя не перезаписали решения друг друга.
 async function change(path,method,values,done){if(busy)return;setBusy(true);setError('');setNotice('');try{await toolApi(`${base}/access${path}${method==='DELETE'?`?revision=${access.revision}`:''}`,{method,...(values?{body:JSON.stringify({...values,revision:access.revision})}:{})});done?.();await refresh();setNotice('Доступ обновлён');}catch(failure){setError(failure.message);}finally{setBusy(false);}}
 // Показывает разрешения сотрудника с учётом остальных назначений, групп и запретов.
 async function check(userId){setEffective(null);if(!userId)return;try{setEffective(await toolApi(`${base}/access/effective?user_id=${userId}`));}catch(failure){setError(failure.message);}}
 if(!access)return <><ErrorLine error={error}/>{!error&&<Empty>Загружаем участников…</Empty>}</>;
 const available=kind==='user'?access.users:access.available_groups;
 const filtered=available.filter(item=>item.name.toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru'))||String(item.id)===principal);
 const ownerId=Number(access.owner?.id);
 return <div className="project-people"><ErrorLine error={error}/>{notice&&<p className="ai-notice" role="status">{notice}</p>}
  <section className="project-owner"><div><span className="overline">ВЛАДЕЛЕЦ ПРОЕКТА</span><h3>{access.owner?.name||'Не назначен'}</h3><p>Создатель становится владельцем автоматически.{access.owner?.status&&access.owner.status!=='active'?' Учётная запись владельца отключена.':''}</p></div>{access.can_transfer_owner&&<button className="secondary" disabled={busy} onClick={()=>setTransfer('')}>{ownerId?'Передать владение':'Назначить владельца'}</button>}</section>
  <div className="project-visibility"><span className="tribe-badge">{access.access_mode==='members'?'Доступ по назначению':'Схема компании'}</span><p>{access.access_mode==='members'?'Проект доступен владельцу, назначенным сотрудникам и группам, руководителям этого трайба и администраторам компании.':'Для этого существующего проекта сохранена прежняя схема компании.'}</p>{access.can_transfer_owner&&access.access_mode!=='members'&&<button className="text-button" disabled={busy} onClick={()=>setMode('members')}>Закрыть проект</button>}</div>
  <form className="project-grant-form" onSubmit={event=>{event.preventDefault();change('','POST',{principal_type:kind,principal_id:Number(principal),project_role:role},()=>setPrincipal(''));}}><fieldset disabled={busy} className="ai-fieldset"><h3>Добавить доступ</h3><div className="tribe-tabs">{[['user','Сотруднику'],['group','Группе']].map(([value,label])=><button type="button" className={kind===value?'active':''} key={value} onClick={()=>{setKind(value);setPrincipal('');setSearch('');}}>{label}</button>)}</div><div className="ai-config-grid"><Field label="Поиск"><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder={kind==='user'?'Имя сотрудника':'Название группы'}/></Field><Field label={kind==='user'?'Сотрудник':'Группа сотрудников'}><select required value={principal} onChange={event=>setPrincipal(event.target.value)}><option value="">Выберите…</option>{filtered.filter(item=>kind!=='user'||item.id!==ownerId).map(item=><option key={item.id} value={item.id}>{item.name}{kind==='group'?` · ${item.member_count} сотрудников`:''}</option>)}</select></Field><Field label="Роль в проекте"><select value={role} onChange={event=>setRole(event.target.value)}>{access.grantable_roles.map(item=><option key={item.key} value={item.key}>{item.name}</option>)}</select></Field><p className="tribe-muted">{descriptions[role]}</p></div><div className="work-actions"><button className="primary" disabled={!principal||!access.grantable_roles.some(item=>item.key===role)}>Добавить доступ</button>{kind==='group'&&access.can_manage_groups&&<button type="button" className="secondary" onClick={()=>setGroup({name:'',description:'',members:[],code:`group-${crypto.randomUUID().slice(0,8)}`})}>Создать группу</button>}</div></fieldset></form>
  {access.tribe_id&&<p className="tribe-muted">Личные назначения доступны сотрудникам трайба. Групповое назначение действует для её участников, входящих в этот трайб.</p>}
  {[["user",access.members.filter(item=>item.principal_id!==ownerId),'Сотрудники'],['group',access.groups,'Группы сотрудников']].map(([type,entries,label])=><section key={type}><div className="tribe-list-head"><h3>{label}</h3><span className="tribe-muted">{entries.length}</span></div>{!entries.length&&<p className="tribe-muted">Пока нет назначений.</p>}{entries.map(item=><article className="project-access-row" key={item.principal_id}><span><strong>{item.name}</strong><small>{names[item.project_role]}{item.active===0?' · группа выключена':''}{item.status&&item.status!=='active'?' · сотрудник отключён':''}</small></span><select aria-label={`Роль: ${item.name}`} value={item.project_role} disabled={busy||!access.grantable_roles.length} onChange={event=>change('','POST',{principal_type:type,principal_id:item.principal_id,project_role:event.target.value})}>{!access.grantable_roles.some(role=>role.key===item.project_role)&&<option value={item.project_role}>{names[item.project_role]}</option>}{access.grantable_roles.map(role=><option key={role.key} value={role.key}>{role.name}</option>)}</select>{type==='group'&&access.can_manage_groups&&data.administration?.accessGroups.some(entry=>entry.id===item.principal_id)&&<button className="secondary" disabled={busy} onClick={()=>{const saved=data.administration.accessGroups.find(entry=>entry.id===item.principal_id);setGroup({...saved,members:saved.members.filter(member=>member.membership_source==='direct').map(member=>member.user_id)});}}>Состав</button>}<button className="text-button" disabled={busy} onClick={()=>setRemove({...item,type})}>Убрать</button></article>)}</section>)}
  <p className="tribe-muted">Удаление назначения убирает этот источник прав. Другие личные, групповые или служебные назначения продолжают действовать.</p>
  <details className="project-effective"><summary>Проверить фактические права сотрудника</summary><Field label="Сотрудник для проверки"><select defaultValue="" onChange={event=>check(event.target.value)}><option value="">Выберите…</option>{access.users.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>{effective&&<div className="effective-permissions">{effective.permissions.map(item=><div className={item.allowed?'allowed':'denied'} key={item.key}><span>{item.allowed?'✓':'—'}</span><span>{item.name}<small>{item.category}</small></span></div>)}</div>}</details>
  {transfer!==null&&<ToolDialog title="Передать владение проектом" onClose={()=>setTransfer(null)}><form className="tribe-form" onSubmit={event=>{event.preventDefault();change('/owner','POST',{user_id:Number(transfer)},()=>setTransfer(null));}}><Field label="Новый владелец"><select required value={transfer} onChange={event=>setTransfer(event.target.value)}><option value="">Выберите сотрудника</option>{access.users.filter(item=>item.id!==ownerId).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><p>Новый владелец сможет управлять доступом и передавать проект. Прежние личные назначения сохранятся.</p><button className="primary" disabled={busy}>Передать владение</button></form></ToolDialog>}
  {remove&&<ToolDialog title="Убрать доступ" onClose={()=>setRemove(null)}><p>Убрать назначение «{remove.name}» из проекта? Другие источники прав сохранятся.</p><button className="primary" disabled={busy} onClick={()=>change(`/${remove.type}/${remove.principal_id}`,'DELETE',null,()=>setRemove(null))}>Убрать назначение</button></ToolDialog>}
  {mode&&<ToolDialog title="Изменить видимость проекта" onClose={()=>setMode(null)}><p>{mode==='members'?'Проект станет доступен только по назначениям. Общая схема компании больше не будет открывать его другим сотрудникам.':'Будет применяться настроенная схема компании. Она может открывать проект всем сотрудникам трайба.'}</p><button className="primary" disabled={busy} onClick={()=>change('/mode','PATCH',{access_mode:mode},()=>setMode(null))}>Подтвердить изменение</button></ToolDialog>}
  {group&&<EmployeeGroupForm group={group} data={data} onClose={()=>setGroup(null)} onSaved={async id=>{setGroup(null);await refresh();setKind('group');setPrincipal(String(id));setNotice('Группа сохранена. Назначьте ей роль в проекте.');}}/>}
 </div>;
}

// Меняет только прямой состав группы; участники из корпоративного каталога сохраняются сервером.
function EmployeeGroupForm({group,data,onClose,onSaved}){
 const [draft,setDraft]=useState({name:group.name,description:group.description||'',members:group.members}),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const original=data.administration?.accessGroups.find(item=>item.id===group.id),external=original?.members.filter(item=>item.membership_source!=='direct')||[];
 // Использует общий API групп, который повторно проверяет отдельное право управления группами.
 async function save(event){event.preventDefault();if(busy)return;setBusy(true);setError('');try{const result=await toolApi(`/api/admin/access-groups${group.id?`/${group.id}`:''}`,{method:group.id?'PATCH':'POST',body:JSON.stringify({...draft,...(!group.id?{code:group.code}:{})})});await onSaved(group.id||result.id);}catch(failure){setError(failure.message);}finally{setBusy(false);}}
 return <ToolDialog title={group.id?'Группа сотрудников':'Новая группа сотрудников'} onClose={onClose}><form className="tribe-form" onSubmit={save}><ErrorLine error={error}/><Field label="Название группы"><input required minLength={2} maxLength={160} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></Field><Field label="Описание"><textarea maxLength={500} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></Field><Field label="Поиск сотрудника"><input type="search" value={search} onChange={event=>setSearch(event.target.value)}/></Field><div className="employee-group-list">{data.users.filter(user=>!user.is_service&&(user.status==='active'||draft.members.includes(user.id))&&user.display_name.toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru'))).map(user=><label key={user.id}><input type="checkbox" disabled={external.some(member=>member.user_id===user.id)} checked={draft.members.includes(user.id)||external.some(member=>member.user_id===user.id)} onChange={event=>setDraft({...draft,members:event.target.checked?[...draft.members,user.id]:draft.members.filter(id=>id!==user.id)})}/><span>{user.display_name}{external.some(member=>member.user_id===user.id)&&<small>Из корпоративного каталога</small>}</span></label>)}</div><p className="tribe-muted">Состав группы влияет на все проекты, где ей назначен доступ. Для проекта в трайбе дополнительно требуется членство в этом трайбе.</p><button className="primary" disabled={busy}>Сохранить группу</button></form></ToolDialog>;
}
