"use client";
import {useState} from 'react';
import RoadmapDates from './RoadmapDates.jsx';
import {useWork,useAction,workApi,Field,ErrorLine,shortDate,Empty} from './WorkUI.jsx';
// Показывает совместную шкалу планов и текущей работы, пересчитывая сценарий без записи сроков.
export default function RoadmapView({notify,onTask}){
 const api=useWork('roadmap'),[confirm,setConfirm]=useState(null),[shifts,setShifts]=useState({}),[group,setGroup]=useState(''),[busy,act]=useAction(notify),value=api.value,byId=new Map(value?.items.map(i=>[i.id,i])||[]),schedule=value?.schedule.tasks||[],dates=schedule.flatMap(i=>[i.start_date,i.due_date]).filter(Boolean).sort(),first=dates[0],last=dates.at(-1),days=first?Math.max(1,(Date.parse(last)-Date.parse(first))/86400000+1):1;
 return <section className="roadmap-view"><header className="work-header"><div><h2>Общая карта работы</h2><p>Планы, текущие задачи и зависимости на одной шкале.</p></div><div className="work-actions"><button type="button" className="secondary" disabled={busy||!value||value.schedule.cycle} onClick={()=>setConfirm(value)}>Проверить и сохранить сроки</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setShifts({});api.reload();}}>Исходные сроки</button><button type="button" className="primary" disabled={busy} onClick={()=>act(async()=>api.setValue(await workApi('roadmap/scenario',{method:'POST',body:JSON.stringify({shifts})})))}>Посмотреть сценарий</button></div></header><ErrorLine error={api.error}/>{value&&<><div className="roadmap-controls"><Field label="Проект или план"><select value={group} onChange={e=>setGroup(e.target.value)}><option value="">Все доступные</option>{value.groups.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></Field>{group&&<Field label="Сдвиг начала, дней"><input type="number" min={-365} max={365} value={shifts[group]||0} onChange={e=>setShifts({...shifts,[group]:Number(e.target.value)})}/></Field>}</div><p className="work-muted">Пунктир — планирование, сплошной цвет — работа. Сценарий учитывает зависимости в календарных днях; сроки сохраняются только после проверки и подтверждения выбранных карточек.</p>{value.schedule.cycle&&<ErrorLine error="Есть цикл связей. Исправьте зависимости перед использованием сценария."/>}
 <div className="roadmap-scroll"><div className="roadmap-scale"><span>Проект / карточка</span><div><span>{shortDate(first)}</span><span>{shortDate(last)}</span></div></div>{value.groups.filter(g=>!group||g.id===group).map(g=><section className="roadmap-group" key={g.id}><h3>{g.title}</h3>{schedule.filter(s=>s.project_id===g.id).map(s=>{const item=byId.get(s.id),offset=s.start_date?(Date.parse(s.start_date)-Date.parse(first))/86400000/days*100:0,width=s.start_date?Math.max(.8,((Date.parse(s.due_date)-Date.parse(s.start_date))/86400000+1)/days*100):0,parents=value.dependencies.filter(d=>d.task_id===s.id);return <div className="roadmap-row" key={s.id}><div><a href={item.href} onClick={e=>{if(item.kind==='task'){e.preventDefault();onTask(item.id);}}}>{item.title}</a><small>{item.kind==='task'?'В работе':item.kind==='planned'?'Планируется':'Инициатива'}{s.critical?' · Определяет срок':''}</small>{parents.length>0&&<small>После: {parents.map(p=>byId.get(p.depends_on_task_id)?.title).join(', ')}</small>}</div><div className="roadmap-track">{s.start_date?<div className={`roadmap-bar ${item.kind} ${s.critical?'critical':''}`} style={{left:`${offset}%`,width:`${width}%`}} title={`${item.title}: ${shortDate(s.start_date)} — ${shortDate(s.due_date)}`}><span>{shortDate(s.start_date)} — {shortDate(s.due_date)}</span></div>:<small>Укажите начало и срок</small>}</div></div>;})}</section>)}</div>{!schedule.length&&<Empty>Добавьте задачи или план с датами.</Empty>}
 {value.capacity&&<details className="roadmap-capacity"><summary>Прогноз загрузки на две недели</summary><p className="work-muted">Текущие резервы + оценки доступных планов, распределённые по рабочим дням. Праздники и отсутствия взяты из календарей команды. Бронирование времени не меняется.</p><div className="work-table-scroll"><table className="work-capacity"><thead><tr><th>Участник</th>{value.capacity.dates.map(d=><th key={d}>{shortDate(d)}</th>)}</tr></thead><tbody>{value.capacity.people.map(p=><tr key={p.id}><th>{p.display_name}</th>{p.days.map(d=><td key={d.date} className={d.overload?'overloaded':''} title={`Резерв ${d.planned} ч + план ${d.proposed} ч; доступно ${d.available} ч`}><strong>{d.total}</strong><small>/ {d.available} ч</small></td>)}</tr>)}</tbody></table></div></details>}</>}{confirm&&<RoadmapDates value={confirm} notify={notify} onSaved={api.reload} onClose={()=>setConfirm(null)}/>}</section>;
}
