"use client";
import {useState} from 'react';
import ToolDialog from './ToolDialog.jsx';
import {useAction,workApi,shortDate,Empty} from './WorkUI.jsx';
// Показывает точный список сдвигов и записывает только явно подтверждённые строки сценария.
export default function RoadmapDates({value,notify,onSaved,onClose}){
 const items=new Map(value.items.map(i=>[i.id,i])),changes=value.schedule.tasks.map(s=>({before:items.get(s.id),after:s})).filter(({before,after})=>after.start_date&&after.due_date&&(after.start_date!==before.start_date||after.due_date!==before.due_date)),[selected,setSelected]=useState(()=>changes.filter(c=>c.before.can_edit).map(c=>c.before.id)),[requestId]=useState(()=>crypto.randomUUID()),[busy,act]=useAction(notify);
 // Отправляет версии всех выбранных карточек; конфликт откатывает весь сценарий.
 function save(){act(async()=>{const payload=changes.filter(c=>selected.includes(c.before.id)).map(({before,after})=>({kind:before.kind,id:before.kind==='task'?before.id:before.kind==='planned'?before.item_id:before.plan_id,revision:before.version_number||before.revision,start_date:after.start_date,due_date:after.due_date}));await workApi('roadmap/apply',{method:'POST',body:JSON.stringify({request_id:requestId,changes:payload})});await onSaved();onClose();notify(`Новые сроки сохранены: ${payload.length}`);});}
 return <ToolDialog title="Подтвердить новые сроки" onClose={()=>!busy&&onClose()}><p>Выберите карточки для изменения. Если хотя бы одну уже изменил другой сотрудник, весь запрос будет отменён.</p><div className="roadmap-date-changes">{changes.map(({before,after})=><label key={before.id}><input type="checkbox" disabled={busy||!before.can_edit} checked={selected.includes(before.id)} onChange={e=>setSelected(e.target.checked?[...selected,before.id]:selected.filter(id=>id!==before.id))}/><span><strong>{before.title}</strong><small>Было: {shortDate(before.start_date)} — {shortDate(before.due_date)}</small><small>Станет: {shortDate(after.start_date)} — {shortDate(after.due_date)}</small>{!before.can_edit&&<small>Нет права менять эту карточку</small>}</span></label>)}</div>{!changes.length&&<Empty>Рассчитанные сроки совпадают с карточками.</Empty>}<p className="work-muted">Остальные карточки и резервы времени не изменятся. Для изменённых планов потребуется новое согласование состава.</p><button type="button" className="primary" disabled={busy||!selected.length||selected.length>500} onClick={save}>Сохранить выбранные сроки ({selected.length})</button></ToolDialog>;
}
