"use client";
import {useEffect,useState} from 'react';
import {workApi,useWork,useAction,Field,ErrorLine,Empty,WorkHeader} from './WorkUI.jsx';
const labels={task:'Задачи',knowledge:'База знаний',recording:'Расшифровки встреч'};
export function SemanticSettings(){
 const api=useWork('semantic/settings'),[draft,setDraft]=useState(null),[notice,setNotice]=useState(''),[busy,act]=useAction(setNotice);
 useEffect(()=>{if(api.value)setDraft(api.value);},[api.value]);
 return <section className="work-card"><WorkHeader title="Семантический поиск" text="Отдельная модель embeddings для поиска по смыслу. Подключение и ключ берутся из профиля ИИ."/><ErrorLine error={api.error}/>{draft&&<form onSubmit={e=>{e.preventDefault();act(async()=>{await workApi('semantic/settings',{method:'PUT',body:JSON.stringify({revision:draft.revision,enabled:Boolean(draft.enabled),profile_id:draft.profile_id,model:draft.model})});await api.reload();setNotice('Настройки сохранены. Запустите обновление индекса в разделе поиска.');});}}><label className="connector-check"><input type="checkbox" checked={Boolean(draft.enabled)} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Включить поиск по смыслу</label><div className="work-form-grid"><Field label="Подключение ИИ"><select value={draft.profile_id||''} onChange={e=>setDraft({...draft,profile_id:e.target.value||null})}><option value="">Выберите профиль</option>{draft.profiles.map(p=><option key={p.id} value={p.id} disabled={!p.enabled}>{p.name}</option>)}</select></Field><Field label="Модель embeddings"><input required={Boolean(draft.enabled)} maxLength={200} value={draft.model} onChange={e=>setDraft({...draft,model:e.target.value})} placeholder="Название модели у вашего провайдера"/></Field></div><p className="work-muted">Профиль должен поддерживать HTTPS /embeddings. Фрагменты доступных материалов отправляются выбранному провайдеру и учитываются в бюджете ИИ. После смены модели нужен новый индекс.</p><button className="primary" disabled={busy}>Сохранить поиск</button></form>}{notice&&<p role="status">{notice}</p>}</section>;
}
export default function SemanticSearch({data,notify}){
 const [query,setQuery]=useState(''),[kinds,setKinds]=useState(Object.keys(labels)),[result,setResult]=useState(null),[busy,act]=useAction(notify),canIndex=data.permissions.features['semantic.index'];
 const jobs=useWork(canIndex?'semantic/jobs':null);
 useEffect(()=>{if(!canIndex||!jobs.value?.some(j=>['queued','running'].includes(j.status)))return;const timer=setInterval(jobs.reload,5000);return()=>clearInterval(timer);},[canIndex,jobs.value,jobs.reload]);
 return <section className="work-module"><WorkHeader title="Поиск по смыслу" text="Задавайте вопрос своими словами. Поиск покажет фрагменты доступных вам материалов."/><form onSubmit={e=>{e.preventDefault();act(async()=>setResult(await workApi('semantic/search',{method:'POST',body:JSON.stringify({query,kinds})})));}}><Field label="Что нужно найти?"><input type="search" minLength={2} maxLength={2000} required value={query} onChange={e=>setQuery(e.target.value)} placeholder="Например: что решили об авторизации в мобильном приложении"/></Field><div className="work-actions">{Object.entries(labels).map(([key,label])=><label className="connector-check" key={key}><input type="checkbox" checked={kinds.includes(key)} onChange={e=>setKinds(e.target.checked?[...kinds,key]:kinds.filter(k=>k!==key))}/>{label}</label>)}<button className="primary" disabled={busy||!kinds.length}>{busy?'Ищем…':'Найти'}</button></div></form>{result&&<><p className="work-muted">{result.note}</p>{result.results.length?result.results.map(r=><article className="work-card" key={`${r.kind}:${r.id}`}><span className="overline">{labels[r.kind]}</span><h3><a href={r.url}>{r.title}</a></h3><p className="semantic-snippet">{r.snippet}</p></article>):<Empty>Совпадений в доступном индексе нет. Попробуйте другой запрос или обновите индекс.</Empty>}</>}{canIndex&&<details className="work-card"><summary>Управление индексом</summary><p>Обрабатываются доступные вам задачи, статьи и расшифровки. Повторный запуск пропускает неизменённые документы. До 128 000 символов на материал; поиск приближённый.</p><ErrorLine error={jobs.error}/><button className="secondary" disabled={busy||jobs.value?.some(j=>['queued','running'].includes(j.status))} onClick={()=>act(async()=>{await workApi('semantic/jobs',{method:'POST',body:'{}'});await jobs.reload();})}>Обновить индекс</button>{jobs.value?.map(j=><div className="work-card" key={j.id}><strong>Индексация #{j.id} · {{queued:'В очереди',running:'Выполняется',completed:'Завершена',failed:'Приостановлена из-за ошибки',cancelled:'Остановлена'}[j.status]}</strong><p>Проверено: {j.indexed_count} · пропущено: {j.skipped_count}{j.error_code?` · ${j.error_code}`:''}</p>{['failed','cancelled','running','queued'].includes(j.status)&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{await workApi(`semantic/jobs/${j.id}`,{method:'POST',body:JSON.stringify({action:['failed','cancelled'].includes(j.status)?'resume':'cancel'})});await jobs.reload();})}>{['failed','cancelled'].includes(j.status)?'Продолжить':'Остановить'}</button>}</div>)}</details>}</section>;
}
