"use client";
import {useState} from 'react';
import {workApi,useWork,useAction,Field,ErrorLine,Select} from './WorkUI.jsx';
import ToolDialog from './ToolDialog.jsx';
const days=['Вс','Пн','Вт','Ср','Чт','Пт','Сб'],clock=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`,minute=s=>s.split(':').reduce((a,v,i)=>a+Number(v)*(i?1:60),0);
export function SlaConfig({draft,setDraft,data,calendars}){
 const config=draft.config||{},stages=data.workflows.filter(w=>!draft.project_id||data.projects.find(p=>Number(p.id)===Number(draft.project_id))?.workflow_id===w.id).flatMap(w=>w.stages.map(s=>({...s,name:`${w.name}: ${s.name}`})));
 return <div className="work-grid"><Field label="Ключ таймера"><input pattern="[a-z][a-z0-9_]{0,79}" value={draft.counter_key||'completion'} onChange={e=>setDraft({...draft,counter_key:e.target.value})}/></Field><Field label="Рабочий календарь"><Select items={calendars} placeholder="Круглосуточно, 24/7" value={draft.calendar_id} onChange={calendar_id=>setDraft({...draft,calendar_id})}/></Field><Field label="После повторного открытия"><select value={config.reopen||'resume'} onChange={e=>setDraft({...draft,config:{...config,reopen:e.target.value}})}><option value="resume">Продолжить накопленное время</option><option value="restart">Новый цикл с нуля</option><option value="keep">Оставить завершённым</option></select></Field>{[['start_stage_ids','Запуск: пусто — с создания'],['pause_stage_ids','Пауза на этапах'],['stop_stage_ids','Завершение: пусто — готовые этапы']].map(([key,label])=><Field label={label} key={key}><div className="work-checks">{stages.map(s=><label key={s.id}><input type="checkbox" checked={(config[key]||[]).includes(s.id)} onChange={e=>setDraft({...draft,config:{...config,[key]:e.target.checked?[...(config[key]||[]),s.id]:(config[key]||[]).filter(id=>id!==s.id)}})}/>{s.name}</label>)}</div></Field>)}</div>;
}
export default function SlaCalendars({notify,onChange}){
 const list=useWork('sla/calendars'),[draft,setDraft]=useState(null),[busy,act]=useAction(notify);
 async function save(e){e.preventDefault();await act(async()=>{await workApi(`sla/calendars${draft.id?`/${draft.id}`:''}`,{method:draft.id?'PATCH':'POST',body:JSON.stringify({...draft,holidays:draft.holidays.map(s=>s.trim()).filter(Boolean)})});setDraft(null);await list.reload();onChange?.();notify('Рабочий календарь сохранён');});}
 return <section className="surface work-section"><div className="work-header"><div><h3>Рабочие календари</h3><p>Праздники и нерабочие интервалы исключаются из расчёта.</p></div><button className="secondary" onClick={()=>setDraft({name:'',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,weekly:{1:[[540,1080]],2:[[540,1080]],3:[[540,1080]],4:[[540,1080]],5:[[540,1080]]},holidays:[]})}>+ Календарь</button></div><ErrorLine error={list.error}/><div className="work-actions">{(list.value||[]).map(c=><button className="secondary" key={c.id} onClick={()=>setDraft(c)}>{c.name} · {c.timezone}</button>)}</div>{draft&&<ToolDialog title={draft.id?'Изменить календарь':'Новый календарь'} onClose={()=>setDraft(null)}><form onSubmit={save} className="work-form"><Field label="Название"><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="Часовой пояс IANA"><input required value={draft.timezone} onChange={e=>setDraft({...draft,timezone:e.target.value})}/></Field><p>Добавляйте отдельные интервалы до и после обеда. Окончание в 00:00 означает конец суток.</p>{days.map((day,i)=><div className="calendar-day" key={day}><strong>{day}</strong><div>{(draft.weekly[i]||[]).map(([start,end],j)=><div className="work-actions" key={j}><input aria-label={`${day}: начало`} type="time" required value={clock(start)} onChange={e=>setDraft({...draft,weekly:{...draft.weekly,[i]:draft.weekly[i].map((r,k)=>k===j?[minute(e.target.value),r[1]]:r)}})}/><span>—</span><input aria-label={`${day}: конец`} type="time" required value={clock(end)} onChange={e=>setDraft({...draft,weekly:{...draft.weekly,[i]:draft.weekly[i].map((r,k)=>k===j?[r[0],minute(e.target.value)||1440]:r)}})}/><button type="button" aria-label="Удалить интервал" onClick={()=>setDraft({...draft,weekly:{...draft.weekly,[i]:draft.weekly[i].filter((_,k)=>k!==j)}})}>×</button></div>)}</div><button type="button" onClick={()=>setDraft({...draft,weekly:{...draft.weekly,[i]:[...(draft.weekly[i]||[]),[540,1080]]}})}>+</button></div>)}<Field label="Праздники: даты YYYY-MM-DD, по одной в строке"><textarea value={draft.holidays.join('\n')} onChange={e=>setDraft({...draft,holidays:e.target.value.split('\n')})}/></Field><div className="work-actions">{draft.id&&<button className="danger-text" type="button" disabled={busy} onClick={()=>act(async()=>{await workApi(`sla/calendars/${draft.id}`,{method:'DELETE'});setDraft(null);await list.reload();onChange?.();})}>Удалить</button>}<button className="primary" disabled={busy}>Сохранить</button></div></form></ToolDialog>}</section>;
}
export function SlaHistory({taskId}){
 const [open,setOpen]=useState(false),history=useWork(taskId&&open?`sla/tasks/${taskId}`:null),phase={running:'Рабочее время',paused:'Пауза',completed:'Завершено',not_started:'До запуска'},date=s=>new Date(s).toLocaleString('ru-RU');
 return <details className="work-sla-history" onToggle={e=>setOpen(e.currentTarget.open)}><summary>Как рассчитан SLA</summary><ErrorLine error={history.error}/>{history.loading&&<p>Загружаем историю…</p>}{history.value?.length===0&&<p>Для этой задачи нет доступных правил SLA.</p>}{(history.value||[]).map(p=><section key={p.policy_id}><h4>{p.policy_name} · {p.elapsed_minutes} / {p.goal_minutes} мин</h4><p>{phase[p.phase]} · цикл {p.cycle} · версия правила {p.policy_revision}{p.calendar_revision?` · календаря ${p.calendar_revision}`:''}</p>{!p.history_complete&&<p className="muted">Часть переходов произошла до включения журнала. Исторический расчёт приблизительный.</p>}<div className="work-table-wrap"><table><thead><tr><th>От</th><th>До</th><th>Состояние</th><th>Минуты</th></tr></thead><tbody>{p.segments.map((s,i)=><tr key={i}><td>{date(s.from)}</td><td>{date(s.to)}</td><td>{phase[s.phase]}</td><td>{s.minutes}</td></tr>)}</tbody></table></div></section>)}</details>;
}

export function SlaNotifications({policyId,data,notify}){
 const {value,error,reload}=useWork(`sla/notifications/${policyId}`),[draft,setDraft]=useState(null),[busy,act]=useAction(notify);
 const current=draft||value;
 return <div className="work-card"><h3>Уведомления и эскалации SLA</h3><ErrorLine error={error}/>{current&&<form className="connector-editor" onSubmit={e=>{e.preventDefault();act(async()=>{const input=Object.fromEntries(['revision','enabled','notify_assignee','warning','breached','escalation_minutes','escalation_user_ids'].map(k=>[k,current[k]]));await workApi(`sla/notifications/${policyId}`,{method:'PUT',body:JSON.stringify(input)});setDraft(null);await reload();notify('Уведомления SLA сохранены');});}}>{[['enabled','Включить уведомления'],['notify_assignee','Уведомлять исполнителя задачи'],['warning','Предупреждать при приближении порога SLA'],['breached','Уведомлять о нарушении SLA']].map(([key,label])=><label className="connector-check" key={key}><input type="checkbox" checked={Boolean(current[key])} onChange={e=>setDraft({...current,[key]:e.target.checked})}/>{label}</label>)}<Field label="Эскалация через рабочие минуты после нарушения (пусто — выключена)"><input type="number" min={1} max={525600} value={current.escalation_minutes||''} onChange={e=>setDraft({...current,escalation_minutes:e.target.value?Number(e.target.value):null})}/></Field><Field label="Получатели эскалации"><div className="work-checks">{data.users.map(u=><label key={u.id}><input type="checkbox" checked={current.escalation_user_ids.includes(u.id)} onChange={e=>setDraft({...current,escalation_user_ids:e.target.checked?[...current.escalation_user_ids,u.id]:current.escalation_user_ids.filter(id=>id!==u.id)})}/>{u.display_name}</label>)}</div></Field><p className="work-muted">Используются календарь и паузы таймера. События можно направить во внешние сервисы через раздел «Интеграции». Получатель должен иметь доступ к проекту.</p><button className="primary" disabled={busy}>Сохранить уведомления</button></form>}</div>;
}
