"use client";
import {useState} from 'react';
import {workApi,useWork,useAction,Field,Empty,ErrorLine} from './WorkUI.jsx';
import ToolDialog from './ToolDialog.jsx';

const rights=[['can_manage_space','Настраивать пространство','Название, описание и цвет трайба'],['can_manage_members','Управлять сотрудниками','Состав трайба и делегирование своих прав'],['can_create_projects','Создавать проекты','Владение созданными проектами'],['can_manage_projects','Управлять всеми проектами трайба','Настройки, участники и работа с проектами этого трайба']];

// Показывает пространства компании и позволяет лидеру создать свой трайб.
export default function TribesView({data,selectedId,onSelect,reload,notify,onProject,onNewProject}){
 const [draft,setDraft]=useState(null),[busy,act]=useAction(notify),tribes=data.tribes||[];
 const admin=['owner','admin'].includes(data.user.global_role),canCreate=data.permissions.features['tribe.create'];
 // Создаёт пространство и открывает его после обновления серверного списка прав.
 async function create(event){event.preventDefault();await act(async()=>{const created=await workApi('tribes',{method:'POST',body:JSON.stringify({...draft,...(draft.leader_id?{leader_id:Number(draft.leader_id)}:{leader_id:undefined})})});await reload();onSelect(created.id);setDraft(null);notify('Пространство трайба создано');});}
 return <section className="view-page tribe-page"><header className="tribe-page-head"><div><span className="overline">{data.workspace.name} · КОМПАНИЯ</span><h1>Трайбы</h1><p>Своё пространство, сотрудники и проекты для каждого подразделения.</p></div>{canCreate&&<button className="primary" onClick={()=>setDraft({name:'',description:'',color:'#e30611',leader_id:admin?'':data.user.id})}>Создать трайб</button>}</header>
  <div className="tribe-cards">{tribes.map(tribe=><button className={`tribe-card tribe-choice ${Number(selectedId)===Number(tribe.id)?'selected':''}`} key={tribe.id} onClick={()=>onSelect(tribe.id)}><span className="tribe-mark" style={{background:tribe.color}}>{tribe.name.slice(0,2).toLocaleUpperCase('ru')}</span><h2>{tribe.name}</h2><p>{tribe.description||'Пространство команды'}</p><span className="tribe-muted">Лидер: {tribe.leader_name}</span>{tribe.is_leader&&<span className="tribe-badge">Вы — трайб-лидер</span>}</button>)}</div>
  {!tribes.length&&<Empty>{canCreate?'Создайте трайб, задайте название и добавьте сотрудников.':'Пока вы не состоите в трайбах. Лидер или администратор компании может добавить вас.'}</Empty>}
  {selectedId&&tribes.some(tribe=>Number(tribe.id)===Number(selectedId))&&<TribeDetails key={selectedId} id={selectedId} data={data} reload={reload} notify={notify} onProject={onProject} onNewProject={onNewProject}/>}
  {draft&&<ToolDialog title="Новое пространство трайба" onClose={()=>setDraft(null)}><form className="tribe-form" onSubmit={create}><Field label="Название трайба"><input autoFocus required minLength={2} maxLength={160} value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></Field><Field label="Описание"><textarea rows={3} maxLength={2000} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})}/></Field><Field label="Цвет"><input type="color" value={draft.color} onChange={event=>setDraft({...draft,color:event.target.value})}/></Field>{admin&&<Field label="Трайб-лидер"><select required value={draft.leader_id} onChange={event=>setDraft({...draft,leader_id:event.target.value})}><option value="">Выберите сотрудника</option>{data.users.filter(user=>user.status==='active'&&!user.is_service).map(user=><option key={user.id} value={user.id}>{user.display_name}</option>)}</select></Field>}<p className="tribe-muted">Лидер сможет настроить пространство и назначить дополнительные права своим сотрудникам.</p><button className="primary" disabled={busy}>Создать пространство</button></form></ToolDialog>}
 </section>;
}

// Управляет составом, настройками и проектами одного трайба с проверкой версии каждой формы.
function TribeDetails({id,data,reload,notify,onProject,onNewProject}){
 const api=useWork(`tribes/${id}`),[tab,setTab]=useState('projects'),[space,setSpace]=useState(null),[member,setMember]=useState(null),[newLeader,setNewLeader]=useState(null),[remove,setRemove]=useState(null),[move,setMove]=useState(null),[search,setSearch]=useState(''),[busy,act]=useAction(notify);
 const tribe=api.value?.tribe,members=api.value?.members||[],projects=data.projects.filter(project=>Number(project.tribe_id)===Number(id)),admin=['owner','admin'].includes(data.user.global_role);
 // Обновляет состав и общую навигацию после подтверждённого изменения сервера.
 async function change(path,method,values,close){await act(async()=>{await workApi(`tribes/${id}${path}`,{method,body:JSON.stringify({...values,revision:tribe.revision})});close?.();await api.reload();await reload();notify('Изменения сохранены');});}
 // Готовит форму только с прямыми делегированными правами сотрудника.
 function editMember(person){setMember({user_id:person?.user_id||'',...Object.fromEntries(rights.map(([key])=>[key,Boolean(person?.[key])]))});setSearch('');}
 if(!tribe)return <><ErrorLine error={api.error}/>{api.loading&&<Empty>Загружаем пространство…</Empty>}</>;
 const candidates=(api.value?.people||[]).filter(person=>person.id!==tribe.leader_id&&person.display_name.toLocaleLowerCase('ru').includes(search.toLocaleLowerCase('ru')));
 return <div className="tribe-detail surface"><header className="tribe-page-head"><div><span className="overline">ПРОСТРАНСТВО ТРАЙБА</span><h2>{tribe.name}</h2><p>{members.length} сотрудников · {projects.length} доступных проектов</p></div><div className="work-actions">{tribe.can_create_projects&&<button className="primary" onClick={()=>onNewProject(id)}>Создать проект</button>}{admin&&<button className="secondary" onClick={()=>setMove('')}>Добавить существующий проект</button>}</div></header>
  <div className="tribe-tabs">{[['projects','Проекты'],['people','Сотрудники'],...(tribe.can_manage_space||tribe.can_assign_leader?[['settings','Настройки']]:[])].map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{label}</button>)}</div><ErrorLine error={api.error}/>
  {tab==='projects'&&<div className="tribe-projects">{projects.map(project=><button key={project.id} onClick={()=>onProject(project.id)}><span className="tribe-badge">{project.key_code}</span><strong>{project.name}</strong><span>Открыть →</span></button>)}{!projects.length&&<Empty>Доступных проектов пока нет. Участие в трайбе само по себе не открывает закрытые проекты.</Empty>}</div>}
  {tab==='people'&&<><div className="tribe-list-head"><h3>Сотрудники трайба</h3>{tribe.can_manage_members&&<button className="secondary" onClick={()=>editMember(null)}>Добавить сотрудника</button>}</div><p className="tribe-muted">Лидер управляет этим пространством. Остальные сотрудники видят проекты по личным назначениям и группам.</p><div className="tribe-people">{members.map(person=><article key={person.user_id}><div><strong>{person.display_name}</strong><small>{person.user_id===tribe.leader_id?'Трайб-лидер':rights.filter(([key])=>person[key]).map(([,label])=>label).join(' · ')||'Участник'}{person.status!=='active'?' · учётная запись отключена':''}</small></div>{tribe.can_manage_members&&person.user_id!==tribe.leader_id&&<div className="work-actions"><button className="secondary" onClick={()=>editMember(person)}>Права</button><button className="text-button" onClick={()=>setRemove(person)}>Убрать</button></div>}</article>)}</div></>}
  {tab==='settings'&&<div className="tribe-settings"><div><h3>Название и оформление</h3><p>{tribe.description||'Описание ещё не добавлено'}</p>{tribe.can_manage_space&&<button className="secondary" onClick={()=>setSpace({name:tribe.name,description:tribe.description,color:tribe.color})}>Настроить пространство</button>}</div>{tribe.can_assign_leader&&<div><h3>Руководство трайбом</h3><p>Передать управление другому сотруднику компании. Прежний лидер останется участником.</p><button className="secondary" onClick={()=>setNewLeader('')}>Сменить трайб-лидера</button></div>}</div>}
  {space&&<ToolDialog title="Настройки пространства" onClose={()=>setSpace(null)}><form className="tribe-form" onSubmit={event=>{event.preventDefault();change('','PATCH',space,()=>setSpace(null));}}><Field label="Название трайба"><input required minLength={2} maxLength={160} value={space.name} onChange={event=>setSpace({...space,name:event.target.value})}/></Field><Field label="Описание"><textarea maxLength={2000} value={space.description} onChange={event=>setSpace({...space,description:event.target.value})}/></Field><Field label="Цвет"><input type="color" value={space.color} onChange={event=>setSpace({...space,color:event.target.value})}/></Field><button className="primary" disabled={busy}>Сохранить настройки</button></form></ToolDialog>}
  {member&&<ToolDialog title="Сотрудник и его права" onClose={()=>setMember(null)}><form className="tribe-form" onSubmit={event=>{event.preventDefault();change('/members','PUT',{...member,user_id:Number(member.user_id)},()=>setMember(null));}}><Field label="Поиск сотрудника"><input type="search" value={search} onChange={event=>setSearch(event.target.value)}/></Field><Field label="Сотрудник"><select required value={member.user_id} onChange={event=>setMember({...member,user_id:event.target.value})}><option value="">Выберите сотрудника</option>{(api.value.people||[]).filter(person=>person.id!==tribe.leader_id&&(candidates.includes(person)||Number(member.user_id)===person.id)).map(person=><option key={person.id} value={person.id}>{person.display_name}</option>)}</select></Field><div className="tribe-rights">{rights.map(([key,label,description])=><label key={key}><input type="checkbox" disabled={!tribe[key]} checked={member[key]} onChange={event=>setMember({...member,[key]:event.target.checked})}/><span><strong>{label}</strong><small>{description}</small></span></label>)}</div><button className="primary" disabled={busy}>Сохранить сотрудника</button></form></ToolDialog>}
  {remove&&<ToolDialog title="Убрать сотрудника из трайба" onClose={()=>setRemove(null)}><p>{remove.display_name} потеряет доступ к пространству и его проектам. Если сотрудник владеет проектом, сначала передайте владение.</p><button className="primary" disabled={busy} onClick={()=>change(`/members/${remove.user_id}`,'DELETE',{},()=>setRemove(null))}>Убрать из трайба</button></ToolDialog>}
  {newLeader!==null&&<ToolDialog title="Передать руководство трайбом" onClose={()=>setNewLeader(null)}><form className="tribe-form" onSubmit={event=>{event.preventDefault();change('/leader','POST',{user_id:Number(newLeader)},()=>setNewLeader(null));}}><Field label="Новый трайб-лидер"><select required value={newLeader} onChange={event=>setNewLeader(event.target.value)}><option value="">Выберите сотрудника</option>{(api.value.people||[]).filter(person=>person.id!==tribe.leader_id).map(person=><option value={person.id} key={person.id}>{person.display_name}</option>)}</select></Field><button className="primary" disabled={busy}>Передать руководство</button></form></ToolDialog>}
  {move!==null&&<ToolDialog title="Добавить проект в трайб" onClose={()=>setMove(null)}><form className="tribe-form" onSubmit={event=>{event.preventDefault();const project=data.projects.find(item=>item.id===Number(move));change('/projects','POST',{project_id:project.id,access_revision:project.access_revision},()=>setMove(null));}}><Field label="Проект"><select required value={move} onChange={event=>setMove(event.target.value)}><option value="">Выберите проект</option>{data.projects.filter(project=>Number(project.tribe_id)!==Number(id)).map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></Field><p>Проект станет закрытым. Владелец войдёт в состав трайба; остальные назначения работают для сотрудников этого трайба.</p><button className="primary" disabled={busy||!move}>Добавить проект</button></form></ToolDialog>}
 </div>;
}
