import test from 'node:test';
import assert from 'node:assert/strict';
import * as Y from 'yjs';
import {makeDocument,documentBody,replaceText,lineDiff} from '../src/lib/knowledge-crdt.js';
import {load} from './test-module-loader.mjs';
function clones(){const seed=makeDocument('План проекта'),a=new Y.Doc(),b=new Y.Doc(),update=Y.encodeStateAsUpdate(seed);Y.applyUpdate(a,update);Y.applyUpdate(b,update);seed.destroy();return [a,b];}
test('concurrent edits in one paragraph converge regardless of order and duplicate delivery',()=>{const [a,b]=clones();a.getText('body').insert(0,'Наш ');b.getText('body').insert(b.getText('body').length,' — согласован');const ua=Y.encodeStateAsUpdate(a),ub=Y.encodeStateAsUpdate(b);Y.applyUpdate(a,ub);Y.applyUpdate(a,ub);Y.applyUpdate(b,ua);assert.equal(documentBody(a),documentBody(b));assert.equal(documentBody(a),'Наш План проекта — согласован');a.destroy();b.destroy();});
test('concurrent replacement does not erase another client insertion and relative cursor follows text',()=>{const [a,b]=clones(),ta=a.getText('body'),tb=b.getText('body'),cursor=Y.createRelativePositionFromTypeIndex(ta,5);replaceText(ta,ta.toString(),'План релиза','local');tb.insert(0,'Новый ');const ua=Y.encodeStateAsUpdate(a),ub=Y.encodeStateAsUpdate(b);Y.applyUpdate(a,ub);Y.applyUpdate(b,ua);assert.equal(ta.toString(),tb.toString());assert.equal(ta.toString(),'Новый План релиза');const position=Y.createAbsolutePositionFromRelativePosition(cursor,a);assert.ok(position.index>=11);a.destroy();b.destroy();});
test('local undo keeps remote edits, including after a disconnected client catches up',()=>{const [a,b]=clones(),text=a.getText('body'),undo=new Y.UndoManager(text,{trackedOrigins:new Set(['local'])});a.transact(()=>text.insert(0,'Наш '),'local');b.getText('body').insert(b.getText('body').length,'!');Y.applyUpdate(a,Y.encodeStateAsUpdate(b),'remote');undo.undo();assert.equal(text.toString(),'План проекта!');Y.applyUpdate(b,Y.encodeStateAsUpdate(a));assert.equal(b.getText('body').toString(),text.toString());undo.destroy();a.destroy();b.destroy();});
test('minimal text replacement preserves surrogate pairs and document validation rejects extra roots or embeds',()=>{const doc=makeDocument('Привет 😀 мир');replaceText(doc.getText('body'),documentBody(doc),'Привет 😁 мир','local');assert.equal(documentBody(doc),'Привет 😁 мир');doc.getMap('secret').set('x',1);assert.throws(()=>documentBody(doc),/неизвестные/);doc.destroy();const embedded=makeDocument('');embedded.getText('body').insertEmbed(0,{image:'x'});assert.throws(()=>documentBody(embedded),/обычный текст/);embedded.destroy();});
test('line diff marks restoration changes and bounds work for large replacements',()=>{assert.deepEqual(lineDiff('Один\nДва\nТри','Один\nНовый\nТри').filter(l=>l.kind!=='same'),[{kind:'removed',text:'Два'},{kind:'added',text:'Новый'}]);assert.equal(lineDiff(Array(600).fill('a').join('\n'),Array(600).fill('b').join('\n')).length,1200);});
const article={id:1,space_id:1,status:'published',version_number:3,body:'Текст'},user={id:1,workspace_id:1},epoch='c08af190-c1a6-4e7d-aa2f-5f084495c015',client='5aeaa8f2-d040-46a6-9b77-17a380b933fa';
const req=(method,data)=>new Request('https://example.test/api/work/knowledge/1/collaboration/sync',{method,body:JSON.stringify(data)});
test('read-only participant cannot submit any document update',async()=>{let writes=0;const m=await load('work-knowledge-crdt.js',{'db.js':{transaction:async f=>f({query:async sql=>{if(sql.startsWith('SELECT * FROM knowledge_articles'))return [[article]];writes++;return [[]];}})},'knowledge-access.js':{knowledgeSpaceAccess:async()=>({level:'view'}),knowledgeAccessAtLeast:(level,required)=>level===required}});await assert.rejects(m.knowledgeCrdtApi(req('POST',{epoch,client_id:client,update:'AAA=',vector:'AAA='}),['knowledge','1','collaboration','sync'],user,article,async()=>{}),e=>e.status===403);assert.equal(writes,0);});
test('old document epoch fails before applying updates or overwriting restored text',async()=>{let writes=0;const m=await load('work-knowledge-crdt.js',{'db.js':{transaction:async f=>f({query:async sql=>{if(sql.startsWith('SELECT * FROM knowledge_articles'))return [[article]];if(sql.startsWith('SELECT * FROM knowledge_crdt'))return [[{epoch:'different'}]];writes++;return [[]];}})},'knowledge-access.js':{knowledgeSpaceAccess:async()=>({level:'edit'}),knowledgeAccessAtLeast:()=>true}});await assert.rejects(m.knowledgeCrdtApi(req('POST',{epoch,client_id:client,update:'AAA=',vector:'AAA='}),['knowledge','1','collaboration','sync'],user,article,async()=>{}),e=>e.status===409&&e.details.epoch_changed);assert.equal(writes,0);});
test('restoration requires an exact current version and does not silently overwrite edits',async()=>{let writes=0;const m=await load('work-knowledge-crdt.js',{'db.js':{transaction:async f=>f({query:async sql=>{if(sql.startsWith('SELECT * FROM knowledge_articles'))return [[article]];writes++;return [[]];}})},'knowledge-access.js':{knowledgeSpaceAccess:async()=>({level:'edit'}),knowledgeAccessAtLeast:()=>true}});await assert.rejects(m.knowledgeCrdtApi(req('POST',{version_number:2,restore_version:1}),['knowledge','1','restore'],user,article,async()=>{writes++;}),e=>e.status===409);assert.equal(writes,0);});
